### ISSUE TITLE
 SPIR-V: Question regarding Depth property of OpTypeImage

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#1107]
We have run into a difficulty when using depth-comparison sample functions such as `OpImageSampleDrefExplicitLod` and `OpImageSampleDrefImplicitLod`. The problem is that the drivers seem to expect images used with these functions to correctly declare the _Depth_ specification number for all image types. This is true, but with different behaviors, for both the latest AMD and Nvidia drivers. To me this looks like drivers are incorrect here after reading the Spirv-V spec, but it is not super obvious. DXC is currently specifying `0`, meaning "not a depth image", for all image types.

One option would be to use the special number `2`, which means "no indication whether it is depth or not depth", for _Depth_, indicating that it is not known weather the image is a depth image. This unfortunately has the consequence of causing internal compile errors inside of the nvidia driver.

Another option could be to heuristically guess the  _Depth_ number based on how an image is used in the shader. I am unsure weather this is a good idea or not which is why I decided to ask here.

A third option could be to create multiple aliases of each image and decide which alias to use depend on which sample function is used. I have not tested if this is a viable option.

**Comment by antiagainst** [comment]
Hey @tafuri,

Sorry for the late reply.

Based on my reading of the spec:

[Vulkan "Validation within a Module"](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#spirvenv-module-validation):

> The “Depth” operand of OpTypeImage is ignored.

[SPIR-V "OpTypeImage"](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpTypeImage):

> Depth is whether or not this image is a depth image. (Note that whether or not depth comparisons are actually done is a property of the sampling opcode, not of this type declaration.)

Correct me if I'm wrong, but I think using `0` as the "Depth" operand should be fine for all `OpSample*` instructions.

**Comment by tafuri** [comment]
Yes, basically I agree. I came to the same conclusion after reading the spec. But apparently both Nvidia, AMD and glslang thinks otherwise.

**Comment by antiagainst** [comment]
I think the spec is quite clear here that the "Depth" operand is just a kind of "hint" to the driver. The real semantics should come from the opcode, no matter what the "Depth" value we put in `OpTypeImage`. 

Changing to use `2` as the "Depth" value may be more preferable; however, still, I think we need Vulkan CTS tests to enforce this.

**Comment by tafuri** [comment]
Always writing 0 seems like a bug to me though. Because the hint will contradict what is actually true in some cases, currently making depth sampling unusable for DXC compiled spir-v shaders.
On the other hand, changing it to 2, which seems to at least be valid according to spec, will make DXC compiled spir-v shaders using any form of textures unusable NVIDIA hardware.

**Comment by antiagainst** [comment]
Yep. I understand your point. Neither plainly using `0` or `1` is good, if without first statically analyzing the code. I've filed a CTS issue for this. In the meantime, I think maybe we can change to use 1, like glslang, as a temporary workaround.

**Comment by tafuri** [comment]
Unfortunately using `1` or `2` together with regular texture sampling functions generate internal compiler errors in the NVIDIA driver, .

**Comment by antiagainst** [comment]
Ha. My previous comment was based on #1108, which suggests that Glslang uses `1` and the driver is happy with that. So I thought maybe we can also do that as a workaround for now. But you are experiencing otherwise. So I did a little bit digging.

If you have a single `Texture2D MyTexture` and using both `.Sample()` and `.SampleCmp()` on it, Glslang actually generates two SPIR-V variables for `MyTexture`: one of Depth-0 image type, the other of Depth-1 image type. The former is used for `.Sample()` and the later is used for `.SampleCmp()`. These two variables are mapped to the same Vulkan descriptor. So this looks like your third option in the above.

Based on my understanding of Vulkan, the image is just a bulk of data; the sampler determines how to sample it. It is also the sampler that dictates what kind of `OpImageSample*` instruction that can be used on an `OpTypeImage` variable:

15.3.1. Texel Input Validation Operations

> There are a number of cases where a SPIR-V instruction can mismatch with the sampler, the image view, or both. ... In such cases the value of the texel returned is undefined.
> * The SPIR-V instruction is one of the OpImage\*Dref\* instructions and the sampler compareEnable is VK_FALSE
> * The SPIR-V instruction is not one of the OpImage\*Dref\* instructions and the sampler compareEnable is VK_TRUE

I think this is also why the Vulkan spec says `The “Depth” operand of OpTypeImage is ignored.`

Considering the third option, I think it's allowed that you have both `.Sample()` and `.SampleCmp()` on the same texture variable in the same entry point. So we can end up generating two variables both referenced. How do we assign the descriptor for them? Assigning the same descriptor and doing reflection to fix and then using the single buffer to back up both images seems doable? But I'm not certain and it looks quite nasty.

I'm not quite clear about the second option. How do you guess? Don't we have the same problem as described above?

My preference is still to use `2` as the depth value; but I'm not opposed to workarounds to enable your flow. However the third option requires quite some work yet brings a big concern for me. I'm curious about your thoughts on this. How do you think?

**Comment by antiagainst** [comment]
Aside from the above problem, i.e., using both `.Sample()` and `.SampleCmp()` needs generating two variables, there is another issue regarding passing textures around in structs and functions.

HLSL is far more flexible than GLSL; we can create aliases of textures, put textures in structs, and pass them into functions. To set the correct hint for the Depth parameter in `OpTypeImage` for all the intermediate temporary textures, we now need to do complicated static analysis (which I think is more suitable to do in SPIRV-Tools). Sometimes, we may have incompatible results for some temporary textures. For example, for the following source code:

```hlsl
struct Textures {
  Texture2D tex;
};

Texture2D              gTex1;
Texture2D              gTex2;
SamplerState           gSamp;
SamplerComparisonState gSampCmp;

float4 main(float3 input : A) : SV_Target {
  Textures ts1 = {gTex1};
  Textures ts2 = {gTex2};
  return ts1.tex.Sample(gSamp, input.xy) + ts2.tex.SampleCmp(gSampCmp, input.xy, input.z);
}
```

Note that dynamically we are not calling `.Sample()` and `.SampleCmp()` on the same texture. Still, in the intial CodeGen, we need to generate two SPIR-V `OpTypeStruct`s for `struct Textures` because their `tex` fields have different Depth values. Further taking function parameters, access chains, etc. into consideration, the compounding complexity is very troublesome.

**Comment by antiagainst** [comment]
Another example regarding aliasing textures:
```hlsl
Texture2D gTexture;
SamplerComparisonState gSampler;

float4 main(float3 input : A) : SV_Target {
    Texture2D t = gTexture;
    return t.SampleCmp(gSampler, input.xy, input.z);
}
```
Glslang-generated code looks like (after legalization and optimization):

```llvm
         %14 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_14 = OpTypePointer UniformConstant %14
   %gTexture = OpVariable %_ptr_UniformConstant_14 UniformConstant

         %25 = OpTypeImage %float 2D 1 0 0 1 Unknown
         %26 = OpTypeSampledImage %25

         %56 = OpLoad %14 %gTexture
         %58 = OpLoad %21 %gSampler
         %59 = OpSampledImage %26 %56 %58

         %68 = OpImageSampleDrefImplicitLod %float %59 ...
```
Note that `gTexture` itself is defined as a Depth-0 image (`%14`), but the sampled image is derived from a Depth-1 image (`%25`). I think the types here are already inconsistent and wrong. (spirv-val does not have this check yet.)

But if that is what the driver expects, i.e, the `OpTypeImage` in `OpSampledImage` should have the correct hint regardless of the original `OpTypeImage`, I think I can throw in a hack (https://github.com/antiagainst/DirectXShaderCompiler/tree/image-depth-hack) to fix that.

@tafuri, @Cry-Mory: would any of you mind to do me a favor to check whether that is true and whether the above hack pleases drivers? Thanks!

**Comment by Cry-Mory** [comment]
@antiagainst  Amazing! :) 
I don't have access to my PC right now but I will check it tonight (in 3-4 hours)

**Comment by Cry-Mory** [comment]
@antiagainst Wonderful! Your proposed fix solve our shadow mask generation problem. Thanks a lot :)

Our test level:

**Before your fix:**
![image](https://user-images.githubusercontent.com/31104678/38167405-c75a4b30-3534-11e8-9b10-6ab6ec6a5d3d.png)

**After your fix:**
![image](https://user-images.githubusercontent.com/31104678/38167376-83f76404-3534-11e8-8efa-119238c99a53.png)

**Comment by antiagainst** [comment]
@Cry-Mory: Awesome! I'll put up a pull request then.

**Comment by antiagainst** [comment]
#1191 for the hack. @tafuri: Would you mind to check whether it fixes your problems? Thanks! :)

@Cry-Mory: Just curious. Which kind of card is your delicious pictures rendered on? Wanted to know whether the fix works for all cards. :)

**Comment by tafuri** [comment]
Sure, I will. I also spoke to the HW vendors to see what their response was. AMD has apparently already fixed this but I'm still waiting for feedback from Nvidia.

**Comment by tafuri** [comment]
After some internal testing I'm pretty sure this fix is good enough for me. Although I would rather see that the vendors follows the spec. Let's see what happens with the khronos CTS tests

**Comment by Cry-Mory** [comment]
@antiagainst Sorry for my late reply! I was testing all my implementations on AMD R9 280X, AMD R9 Nano, Nvidia 660 Ti, and Nvidia 940M. All work fine. Thanks again.

@tafuri Do you know if AMD fix is already in released AMD drivers? I have 18.3.3 which is pretty new but this issue is not fixed there.

**Comment by antiagainst** [comment]
Thanks for the updates! I'll merge #1191 then.

**Comment by tafuri** [comment]
@Cry-Mory Only pre-release. But it sounded like they expect it to be in the next release.

**Comment by antiagainst** [comment]
The workaround was already landed. Driver issues should be tracked separately. I'll close this.

**Comment by Cry-Mory** [comment]
@antiagainst Just for completeness of this thread, NVIDIA has released a bunch of fixes to Vulkan driver in their latest release (397.31). It is very likely that this one is also fixed there.

**Comment by antiagainst** [comment]
@Cry-Mory: Awesome! I've uploaded https://github.com/Microsoft/DirectXShaderCompiler/pull/1261 to use 2 as the depth value for `OpTypeImage`s. I'd very appreciate if you can give it a try on NV & AMD drivers if possible. Thanks!

**Comment by mmostajab** [comment]
@antiagainst I am sorry for the very late reply. I was on vacation. I tried our demos on vulkan and AMD with the latest DXC (I saw you have committed your change). Everything seems to be fine with this change.

In addition, many other bugs with compute shader which I wanted to report is fixed as well. Thanks a lot :)
