### ISSUE TITLE
HLSL extensions for compilers?

### ISSUE THREAD

**Issue by elviras9t** [Microsoft/DirectXShaderCompiler#1146]
Greetings to you, the developers of Microsoft. I know, maybe this is not the first topic. But despite the fact that HLSL already has the 6th shader model, do you have any desire to implement support for special extensions (NV, AMD, others) that, during compilation, this code will go to SPIR-V (1.3), or, possibly, in DXIL?

**Comment by mlrdevgit** [comment]
There's an extension API for intrinsics that might be a good fit for this, or perhaps you could extend the compiler by simply having additional unresolved calls to external functions (they essentially boil down to the same thing, the intrinsics help with cutting down on declarations and some of the lowering if you're looking at DXIL). You'll have to turn off validation for this to work (because these aren't part of the DXIL specification).

We're not looking at supporting special vendor extensions in DXIL right now (although you can use experimental mode for things of the sort course).

**Comment by antiagainst** [comment]
For the SPIR-V CodeGen, we sometimes need SPIR-V extensions to translate certain HLSL features. Examples include using SPV_KHR_multiview to translate SV_ViewID. This extension picking process is automatic ATM; the CodeGen decides which extension (first KHR ones then vendor specific ones) to emit depending on the HLSL source code. We are in the process of adding explicit control over which extensions are allowed to be used (#1151).

For Vulkan/SPIR-V features without HLSL native representation, we do it on a case-by-case base. See https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#vulkan-specific-features for all cases we've covered thus far.

**Comment by hekota** [comment]
As @mlrdevgit mentioned above - we're not looking at supporting special vendor extensions in DXIL right now.
