### ISSUE TITLE
Getting compiler error for vertex shaders that are not writing into a variable with SV_POSITION semantics

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1172]
I am wondering if a vertex shader which is not writing in SV_Position valid or not. As far as I know, directx compiler complains about vertex shaders that are not writing in SV_Position and pixel shaders that are not writing into SV_Target0. I believe we should get those errors with this compiler as well.

**Comment by tex3d** [comment]
Fxc gives an error only when targeting DX9 (10level9) targets, since the output of the VS can only be used to feed the rasterizer.  In DX10 and newer, the output may not be feeding the rasterizer directly, so not writing to SV_Position is allowed.  Dxc does not support the targets that disallow this, so it's not necessary to emit an error for this case.

Similarly for pixel shaders, since you can do more than just output pixel values in DX10 and above, SV_Target is also not a required output.  Fxc only emits an error for DX9 (10level9) targets here as well.
