### ISSUE TITLE
Setting up continuous integration

### ISSUE THREAD

**Issue by antiagainst** [Microsoft/DirectXShaderCompiler#118]
It would be nice to have a bot to automatically check pull requests to make sure they are not breaking the master branch. Appveyor is quite popular on GitHub as a Windows continuous integration service, and it is already [used by vscode](https://github.com/Microsoft/vscode/blob/master/appveyor.yml). Is it possible to enable Appveyor for this project? Or actually there are other plans for continuous integration?

cc @dneto0 @ehsannas

**Comment by marcelolr** [comment]
Thanks for bringing this up.

Right now we have a couple of internal systems that are keeping an eye on things for us, mostly because we have a pretty specific setup right now in terms of OS/hardware/drivers to run the execution tests. Perhaps a starting point would be to simply need to tweak stuff so we post back the results to the pull request threads.

I don't have experience with Appveyor myself, but I can educate myself and have a better-informed opinion. Again, thanks for bringing this up - I'll update this thread with progress.

**Comment by antiagainst** [comment]
Hi @marcelolr,

That's good to know. As for Appveyor, if it's OK to enable it for this project, I can contribute the configuration file.

Actually I've already started [one](https://github.com/antiagainst/DirectXShaderCompiler/blob/master/.appveyor.yml), but just experiencing some [problems](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/build/5) right now.

**Comment by antiagainst** [comment]
The problem is that `dxgi1_4.h` cannot be found during compiling. But it does exist in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared` as printed [here](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/build/11#L278). Not clear why yet.

**Comment by marcelolr** [comment]
@antiagainst, is there anything else missing to close this issue? thx

**Comment by antiagainst** [comment]
Nope, all done for this issue. I'll close it. :)
