### ISSUE TITLE
CMake support for DXC

### ISSUE THREAD

**Issue by Zingam** [microsoft/DirectXShaderCompiler#1271]
Add support to CMake for DXC.
While this request might be off-topic I think it is still relevant here as CMake is the preferred build system for Android NDK applications.
What do you think?

**Comment by antiagainst** [comment]
DXC is based on LLVM/Clang and is leveraging the original CMake configurations. The batch script used for building DXC is just invoking cmake with pre-defined options.

**Comment by Zingam** [comment]
I mean support for CMake to compile HLSL files with DXC.

**Comment by gongminmin** [comment]
1. This should be an issue of CMake, not DXC,
2. In current CMake, you can use VS_TOOL_OVERRIDE to do that.

**Comment by Zingam** [comment]
Android NDK for example provides toolchain files for CMake to consume. It will not rely on CMake.
In that context it makes sense for a tool to provide whatever necessary to help the integration with CMake. Microsoft Visual Studio has a pretty descent support for CMake already. I just wish it will start supporting deploying and debugging UWP and XBox targets with CMake projects directly.

**Comment by hekota** [comment]
Up-for-grabs - leaving this up to the GitHub community to see if someone wants to implement this.

**Comment by llvm-beanz** [comment]
While I do recognize that other projects do vend CMake modules, I think a better approach for language support in CMake is to make the change to CMake proper rather than to implement it as a module.

There are some limitations to what you can express in a CMake-only solution especially on some of the more complex IDE generators like Visual Studio and Xcode.

Longer term, as we move HLSL support into Clang we do expect that CMake support for HLSL should be much easier as the HLSL compiler will just be Clang.

As a last note we're not likely to dedicate resources to this task, in part because I'm unconvinced it is the right direction as stated above and in part because it isn't a priority. Rather than leaving it around to languish longer I'm going to close the issue.

If someone were to write a self-contained CMake module for compiling HLSL sources, and they wanted to contribute it to DXC we would consider accepting that as a PR.
