### ISSUE TITLE
[Spir-V] Failing simple tests

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#1344]
Hi,

we are considering moving over to dxc to translate hlsl to spir-v but our first simple test just fail.
Consider this:
```
ConsumeStructuredBuffer<uint> src : register(u0);
AppendStructuredBuffer<uint> dst : register(u1);

[numthreads(1,1,1)]
void main()
{
  dst.Append(src.Consume());
}
```
With this it reports an type mismatch error when you try to compile it with spir-v target turned on.
Tested with 0987e48b56a70eed1af185a33ffd8155c1ffe487

**Comment by ehsannas** [comment]
Hi! Thanks for reporting this issue. I'm investigating and will provide details soon.

**Comment by mmostajab** [comment]
ConsumeStructuredBuffer and AppendStructuredBuffer do not map to any valid structures on Vulkan. I am not sure if this should be supported by DXC at all.

**Comment by ehsannas** [comment]
We currently do [support ](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/type.consume-structured-buffer.hlsl)compiling {Append|Consume}StructuredBuffer.

I have found the root cause to be a corner case since the result of `src.Consume()` is passed directly to `Append`. Since these are intrinsic methods, they are treated with custom code in the compiler. I have a fix coming up.

**Comment by TiemoJung** [comment]
@mmostajab I have to disagree, they certainly do exist in DX12. And mapping to Vulkan exists as @ehsannas already stated.

**Comment by mmostajab** [comment]
Thanks for the replies and sorry for the wrong information. You are right about it (since shader model 5 supports it, dx12 should support it as well) but I am not aware of any GLSL structs mapping to them. On the C/C++ side, we can use storage buffer or an image for them, probably.

**Comment by TiemoJung** [comment]
DX12 has nativ support, on UAV create you supply a buffer that holds the counter.
On GL and Vulkan you are on your own.
