### ISSUE TITLE
Incorrect cbuffer selection when matrix is used

### ISSUE THREAD

**Issue by MichelVachon** [Microsoft/DirectXShaderCompiler#1364]
Using the following compilable vertex shader:
```
cbuffer Instance
{
    float4x3 Matrix;
};

cbuffer PreviousWorldTransform
{
    float4x3 PreviousMatrix;
};

float4 main( ) : POSITION0
{
    float4 p;
        
    p.x = PreviousMatrix[0].x;
    p.yzw = float3(0,0,0);

    return p;
}
```

The generated spirv uses Instance::Matrix instead of using PreviousWorldTransform::PreviousMatrix on line 
`p.x = PreviousMatrix[0].x;`

This problem doesn't occur if PreviousMatrix is not a matrix but a vector.

Thanks
Mike

**Comment by MichelVachon** [comment]
Also, the problem doesn't occur if the cbuffer declaration PreviousWorldTransform happens before cbuffer Instance

**Comment by antiagainst** [comment]
I think the CodeGen is correct. But there are a few confusing points I'd like to explain.

The optimized SPIR-V:

```llvm
               OpDecorate %PreviousWorldTransform DescriptorSet 0
               OpDecorate %PreviousWorldTransform Binding 1
  ...
%type_Instance = OpTypeStruct %mat4v3float
  ...
%PreviousWorldTransform = OpVariable %_ptr_Uniform_type_Instance Uniform
  ...
         %24 = OpAccessChain %_ptr_Uniform_mat4v3float %PreviousWorldTransform %int_0
         %25 = OpAccessChain %_ptr_Uniform_v3float %24 %uint_0
         %26 = OpAccessChain %_ptr_Uniform_float %25 %int_0
         %27 = OpLoad %float %26
```

Note that we are indeed accessing `%PreviousWorldTransform` here.

The confusing part is maybe the type of `%PreviousWorldTransform`, which is said to be `%type_Instance`. That's because we are **unifying** structs with the exact same members (ignoring names). SPIR-V allows that. Since the type for `Instance` and `PreviousWorldTransform` are the same, we only generate one SPIR-V `OpTypeStruct` for it. We are changing this behavior though, with #1367.

Maybe it will be easier to see with the unoptimized SPIR-V:

```llvm
               OpDecorate %Instance DescriptorSet 0
               OpDecorate %Instance Binding 0
               OpDecorate %PreviousWorldTransform DescriptorSet 0
               OpDecorate %PreviousWorldTransform Binding 1
  ...
   %Instance = OpVariable %_ptr_Uniform_type_Instance Uniform
%PreviousWorldTransform = OpVariable %_ptr_Uniform_type_Instance Uniform
```

Note that now we see a `%Instance` taking binding 0. Because `%Instance` is not accessed at all, it is eliminated during optimization. And in the optimized version, `%PreviousWorldTransform` is still taking binding 1.

**Comment by MichelVachon** [comment]
Ha yes ok, I misunderstood the issue. 

The problem is that the names in `spriv_cross::Resource` returned by `spirv_cross::CompilerHLSL` are unexpected. And so our shader reflection doesn't match things properly.

`spirv_cross::CompilerHLSL::get_name` returns the correct one.
But using that name doesn't work for all cases.

How do we know which one is ok?

thanks
Mike

**Comment by MichelVachon** [comment]
It looks like `spirv_cross::CompilerHLSL::get_name` returns the correct variable name instead of the type. Even for the case where the constant buffer definitions are shared.

Note that this is for shaders used at a particular spawn location.

I'll test for the entire shader dataset.

But this is on 1.0.293 which contains #1367, and the struct definitions are shared, meaning that our shader reflection doesn't understand the struct members.

**Comment by antiagainst** [comment]
Yeah, as said before, there are work to be done in spirv-opt to fully avoid unifying struct types of resources. Pull request is already up there: https://github.com/KhronosGroup/SPIRV-Tools/pull/1640. So you may want to wait for it to be landed and then try out. :)

**Comment by dneto0** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/pull/1640 has landed in SPIRV-Tools master

**Comment by antiagainst** [comment]
Refreshed SPIRV-Tools. This issue should be fixed now. Please reopen otherwise.
