### ISSUE TITLE
[spirv] Issue: DX Buffer Layout is not working. Feature Request: Making it work with a work around.

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1379]
I have a bug in one of my shaders (You can find it here: [sample.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2138580/sample.hlsl.txt)). The shader is pulling the vertices from a structured buffer and return them. The structured buffer is defined as follows:

```
struct SParticleAxes
{
  float3 XAxis;
  float3 YAxis;
};

StructuredBuffer<SParticleAxes>axesSRV:register(t12, space3);

```

Obviously, it is not std430 compatible but I was expecting that since I am using **-fvk-use-dx-layout**, this should work as it is in directx. The command I use to compile it is as follows:

> .\dxc.exe -spirv -O3 -fvk-use-dx-layout -Zpr .\sample.hlsl -Fo sample.spv -Fc sample.h_spv -T vs_5_0 -E PulledParticleVS -fvk-invert-y

I checked the spirv code (find it here: [sample.h_spv.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2138557/sample.h_spv.txt)). The offset, stride and alignments looks correct as follows:

```
OpMemberDecorate %SParticleAxes 0 Offset 0
OpMemberDecorate %SParticleAxes 1 Offset 12
OpDecorate %_runtimearr_SParticleAxes ArrayStride 24
```

But unfortunately, there is something wrong (may be the driver) which 

I changed my struct definition to the following one and then this worked:

```
struct SParticleAxes
{
  float XAxis_x;
  float XAxis_y;
  float XAxis_z;
  
  float YAxis_x;
  float YAxis_y;
  float YAxis_z;
};

```
I was thinking that it will be a good solution if DXC provides an option which decomposes the vector types to primitive types when it is necessary to fix this problem. I can also help with its implementation.

I wanted to know your opinion about it.

**Comment by antiagainst** [comment]
Note that we added `-fvk-use-dx-layout` merely for helping developers writing game targeting both DX and VK, because we see a lot of pain coming from it. It does not mean it is officially supported by VK. It is not at the moment. It just "happens to work" for the most of the time. We've raised the portability issue with the Khronos Group.

In the above you are placing two `float3`s together. That is where DX and VK rules differs greatly. As per VK's terminology, under the DX layout rules, the second `float3` is _improperly straddling_, because it crosses a 4-component vector boundary. Smaller discrepancies may work fine with the drivers, but on this big one, drivers are likely to error out.

I'm not sure decomposing the vector into elements would be an easy way to go. It's not just simply replacing the types, you will need to fix all operations using these variables, too. For example,

```hlsl
struct S {
  float3 a;
  float3 b;
};

StructuredBuffer<S> MyBuffer;

float3 main(uint index : A) : B {
  return MyBuffer[index].a[index] + MyBuffer[index].b.zyx.xyz.xyy.y;
}
```

It's not trivial to get the indexing/swizzling correct, considering the freedom you enjoys with it. And consider again with array types applied to this, and more nested structs...

Even doing this as a SPIR-V transformation in SPIRV-Tools is questionable. For that, you probably want a thorough solution instead of ad-hoc workaround fix. But generally converting vectors into scalars has indications over GPU register pressure that should be carefully thought out.

Instead of having workarounds with compilers, is it possible to modify the code to add paddings maybe? I feel that's practically much easier than waiting for spec/driver/compiler addressing this, but I don't know how hard would it be for you to change the source code.

**Comment by Cry-Mory** [comment]
Changing the source code can be an option for me. I can make Vulkan specific changes but it is nasty. I was wishing to find a better solution.

Regarding the padding solution you proposed, the padding needs to be done in both data and shader to work and in this case, it increases the data size by 30% which is bad in our case which the shader is used to render particle and the buffer size can go from 10MB-50MB and we have multiple of each of them.

**Comment by antiagainst** [comment]
Hey @Cry-Mory, is this still an issue for you? Or was it (hopefully) addressed by updating drivers or something?

**Comment by Cry-Mory** [comment]
Hey @antiagainst Unfortunately, new drivers did not address this issue. The only solution I have for it now is to decompose the float3 into 3 floats which is having performance drawbacks.

**Comment by antiagainst** [comment]
As you said in the above, padding is not the way to go because it bloats the data. Scalarizing the vector is also not the way to go since it impacts the performance. Then I'm not sure how the compiler can help for this case. Do you have other suggestions that how we can help? Another kinda weird suggestion is to use `float4` + `float2`, which should make the driver happy and still pack the data tightly without loosing the performance of vectors? But it depends on how you implement stuff in your source code.

**Comment by antiagainst** [comment]
Update on this: The Khronos Group recently published `VK_EXT_scalar_block_layout`, which, although not specially tailored for this issue, should address it. You can try to request `VK_EXT_scalar_block_layout` to see if it works.

I'll close this one since there is no one work DXC need to do for this. Thanks!

**Comment by kennyalive** [comment]
I tried to use VK_EXT_scalar_block_layout to make -fvk-use-dx-layout layout valid but it does not work for me. Validation layers still report an issue.
