### ISSUE TITLE
[SPIR-V] Support binding resources on the command line

### ISSUE THREAD

**Issue by mikeh001** [Microsoft/DirectXShaderCompiler#1442]
As an alternative to adding [[vk::binding]] directives into the shader source code would it be possible to implement a command line method of binding named resources to a specific descriptor set and binding index, similar to the --rsb/--resource-set-binding option in glslang?

**Comment by antiagainst** [comment]
Thanks for the suggestion, @mikeh001!

We already have multiple mechanisms for assigning binding numbers for resource:

* `[[vk::binding]]`
* `[[vk::counter_binding]]`
* `:register()`
* `-fvk-*shift`
* auto-assignment for unspecified

They together have introduced complicated compound effects; rules regarding who takes precedence are on the verge of being unmanageable. So generally speaking, we are conservative about adding more mechanisms to make the picture even complicated, unless seeing strong usage cases and improvements to developers' work flows.

With that said, would you elaborate a little bit on what exact assignment mechanism you want to achieve with the proposed command-line option so that we can understand and discuss better? Something like `--rsb t0 1 2` to map the resource in `t0` to set No.2 and binding No.1?

There are also questions regarding interactions with other mechanisms, too, like how to handle the optional space since we can have multiple `t0`s? And how to handle missing `:register()` decorations? Which mechanism takes precedence? Etc. Would be better to have answers to these questions too.

By the way, just wanted to point out that we already have `-fvk-*-shift` in case you are not aware of. Maybe they can solve your problem?

**Comment by mikeh001** [comment]
Hi, thanks for considering this request.

The primary motivation is to facilitate using dxc as a drop-in replacement for glslangvalidator. We are already using --rsb as described at https://github.com/KhronosGroup/glslang/blob/master/StandAlone/StandAlone.cpp, so "--rsb name set binding" e.g. "--rsb t0 1 2" for setting t0 to set 1 binding index 2.

The reason we do this is because our shader pipeline creates descriptor sets independently of the shader binaries and where possible we want to avoid binding lots of different sets. Therefore we need the shader compiler to be aware of the set and binding index a resource will be located. (Background info: we use the same hlsl shader source for both DX12 and Vulkan).

Unfortunately the existing mechanisms (-fvk-*-shift etc) are not flexible enough to allow us to do this. We could preprocess the shader source to insert [[vk::binding]] information for every resource but this is clunky, error prone, and slows down the compilation process.

Regarding how this would interact with other mechanisms I'm not 100% sure since we would want to specify all resources rather than use an automatic method. But I would think that it would be similar to a resource tagged with [[vk::binding]] but higher priority, so if you had a [[vk::binding]] in the shader source, that would be overridden by --rsb for the same-named resource. Alternatively that could be an error condition.

I hope this answers all the questions; let me know if anything is not clear.

Thanks,

-Mike

**Comment by antiagainst** [comment]
Thanks for the explanation! It's quite helpful. We'll look into this.

Another thing I'd like to clarify is how you want to handle the associated counters with {RW|Append|Consume}StructuredBuffers? They occupy different bindings from the main resources.

**Comment by antiagainst** [comment]
I've put up #1480  for this. Please check whether it satisfies your needs.

**Comment by antiagainst** [comment]
#1480 is merged. I'll close this.
