### ISSUE TITLE
[Spir-V] Generated Spir-v doesn't work on some Nvidia cards

### ISSUE THREAD

**Issue by Gaspard--** [Microsoft/DirectXShaderCompiler#1455]
Hello, I seem to have encountered a bug in the Spir-V generated by dxc. So far, I've only come accross this problem on certain Nvidia cards.

### Minimal repro steps
```hlsl
Texture2D<float> tex : register(t0);
SamplerState smp : register(s0);

void Mainfp (
	  in  float2 uv : LEGACY_TEXCOORD
	, out float output : SV_TARGET ) {
    output = tex.SampleLevel( smp, uv, 0 ).x;
}
```
Compiled with `-spirv -E Mainfp -DVULKAN -DVULKAN_PC -DMAIN_FP -T ps_6_3`:

```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 26
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %Mainfp "Mainfp" %in_var_LEGACY_TEXCOORD %out_var_SV_TARGET
               OpExecutionMode %Mainfp OriginUpperLeft
               OpSource HLSL 630
               OpName %type_2d_image "type.2d.image"
               OpName %tex "tex"
               OpName %type_sampler "type.sampler"
               OpName %smp "smp"
               OpName %Mainfp "Mainfp"
               OpName %in_var_LEGACY_TEXCOORD "in.var.LEGACY_TEXCOORD"
               OpName %out_var_SV_TARGET "out.var.SV_TARGET"
               OpName %type_sampled_image "type.sampled.image"
               OpDecorate %in_var_LEGACY_TEXCOORD Location 0
               OpDecorate %out_var_SV_TARGET Location 0
               OpDecorate %tex DescriptorSet 0
               OpDecorate %tex Binding 0
               OpDecorate %smp DescriptorSet 0
               OpDecorate %smp Binding 0
      %float = OpTypeFloat 32
%type_2d_image = OpTypeImage %float 2D 2 0 0 1 Unknown
%_ptr_UniformConstant_type_2d_image = OpTypePointer UniformConstant %type_2d_image
%type_sampler = OpTypeSampler
%_ptr_UniformConstant_type_sampler = OpTypePointer UniformConstant %type_sampler
       %void = OpTypeVoid
         %13 = OpTypeFunction %void
    %v2float = OpTypeVector %float 2
%_ptr_Input_v2float = OpTypePointer Input %v2float
%_ptr_Output_float = OpTypePointer Output %float
    %float_0 = OpConstant %float 0
    %v4float = OpTypeVector %float 4
%type_sampled_image = OpTypeSampledImage %type_2d_image
        %tex = OpVariable %_ptr_UniformConstant_type_2d_image UniformConstant
        %smp = OpVariable %_ptr_UniformConstant_type_sampler UniformConstant
%in_var_LEGACY_TEXCOORD = OpVariable %_ptr_Input_v2float Input
%out_var_SV_TARGET = OpVariable %_ptr_Output_float Output
     %Mainfp = OpFunction %void None %13
         %19 = OpLabel
         %20 = OpLoad %v2float %in_var_LEGACY_TEXCOORD
         %21 = OpLoad %type_2d_image %tex
         %22 = OpLoad %type_sampler %smp
         %23 = OpSampledImage %type_sampled_image %21 %22
         %24 = OpImageSampleExplicitLod %v4float %23 %20 Lod %float_0
         %25 = OpCompositeExtract %float %24 0
               OpStore %out_var_SV_TARGET %25
               OpReturn
               OpFunctionEnd
```

### Expected result
Shaders should be loadable / converted to native code succesfully.

### Actual result
This spirv once loaded into a nvidia pipeline (on some graphic cards only) causes the following error:
```
Link failed
(0) : fatal error C9999: Can't convert to expr: textureLod
```

### Further technical details
I found this related issue https://github.com/KhronosGroup/glslang/issues/252 which seems to talk about the same subject.
If I use spirv-cross to reflect the code to glsl, I get the following:
```glsl
#version 450

uniform sampler2DShadow SPIRV_Cross_Combinedtexsmp;

layout(location = 0) in vec2 in_var_LEGACY_TEXCOORD;
layout(location = 0) out float out_var_SV_TARGET;

void main()
{
    out_var_SV_TARGET = textureLod(SPIRV_Cross_Combinedtexsmp, in_var_LEGACY_TEXCOORD, 0.0).x;
}
```
Which looks similar to the invalid Spir-V in the linked issue.
Compiling with `glslc.exe -fshader-stage=frag glsl_repro.glsl` generates the following errors:
```
glsl_repro.glsl:3: error: 'binding' : sampler/texture/image requires layout(binding=X)
glsl_repro.glsl:10: error: 'textureLod' : no matching overloaded function found
2 errors generated.
```
The second one in particular looks suspiciously similar to one that would have been added because of the linked issue. Fixing the first compilation error doesn't affect the second.

**Comment by antiagainst** [comment]
Okay, TL;DR: I think the generated SPIR-V is fine. The issue is resulting from the `Depth` field of `OpTypeImage`.

We put `2` (means no indication as to whether this is depth image or not) as the `Depth` value for `OpTypeImage`. My guess is that SPIRV-Cross and NV drivers are somehow not recognizing it correctly. So `sampler2DShadow` is generated. The `sampler2DShadow`-overload of `textureLod()` requires the second parameter to be `vec4`, but here `uv`/`in_var_LEGACY_TEXCOORD` is `vec2`. So you see "no matching overloaded function found". On the contrary, Glslang [generates](http://shader-playground.timjones.io/9ed0f395799bf9d5da07b86a031453ac) `0` as the `Depth` value of `OpTypeImage`; SPIRV-Cross recognize that and generates `sampler2D`, whose overload of `textureLod()` takes `vec2` as the second parameter.

```glsl
float textureLod(sampler2DShadow sampler, vec4 P, float lod);
gvec4 textureLod(gsampler2D sampler, vec2 P, float lod);
```

Note that the `Depth` value is just a **hint**. The Vulkan spec clearly says that it should be ignored.  We also have CTS tests added to make sure the depth field is ignored: https://github.com/KhronosGroup/VK-GL-CTS/issues/88.

Why we are generating `2` as the `Depth` value? There is a lengthy discussion in #1107. In a word, it's because the fundamental difference between HLSL and SPIR-V: HLSL has the depth info on sampler types, but we want it on image type in SPIR-V. It requires non-trivial analysis to give the correct `Depth` hint, if ever possible.

**Comment by Gaspard--** [comment]
Hello,

We were able to confirm that your theory is correct: by patching the assembly and replacing the Depth field by 0, the shader is succesfully loaded / converted to native code.
It also seems spirv cross has a fix about this that I probably hadn't locally: https://github.com/KhronosGroup/SPIRV-Cross/issues/631
Testing with this bug fix emits the correct reflection.
Closing this issue because this is not a bug.

Thanks for your help!
