### ISSUE TITLE
[spirv] invalid spirv error

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1549]
I tried to compile [brokenshader.ps.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2389251/brokenshader.ps.txt) with latest DXC with the following command line:

`.\dxc.exe -spirv brokenshader.ps.txt  -T ps_5_0 -E STHPixelTaskPS`

I got the following error and obviously it did not generate the output shader:

> fatal error: generated SPIR-V is invalid: The selection construct with the selection header 130 does not dominate the merge block 147
>   %147 = OpLabel
> 
> note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

I would be appreciated if you take a look into it.

**Comment by antiagainst** [comment]
Thanks for the bug report. Looks like a spirv-opt issue since it works fine with `-O0`. We'll check.

**Comment by Cry-Mory** [comment]
@antiagainst I am not so sure if that is spirv-opt issue or not because this shader has a problem even when I generate DXIL and use it as a DX12 shader.

**Comment by antiagainst** [comment]
Sorry for the late reply. In case this is still an issue for you, I think it's your `do { ... break ... } while (0)` constructs causing problem.

Is it a must to retain the current `do { ... break ...} while (0)` pattern? Even if we make it work, it will likely cause grief for further optimizations and result in bad performance because this pattern is translated into loops and then optimized into phi nodes. The ability to handle loops is not very strong right now in spirv-opt.

**Comment by antiagainst** [comment]
A quick and easy fix would be to change the `if (...) break` statements inside do-while loop into `if (!...) { ... }`. Then the compiler can compile the source code.

**Comment by ehsannas** [comment]
I just checked with the DXC top-of-tree (which has a newer SPIRV-Tools version), and this issue has been resolved.
