### ISSUE TITLE
static atomic causes fatal error

### ISSUE THREAD

**Issue by emoon** [Microsoft/DirectXShaderCompiler#1566]
### Title
*When using a `static` for an atomic the compiler will generate a fatal error*  

### Minimal repro steps
*Compile the following shader*

```
static uint g_globalMeshCounter;

[numthreads(1, 1, 1)]
void csEntry(
	uint groupIdx : SV_GroupID,
	uint localIdx : SV_GroupThreadID)
{
	uint offset;
	InterlockedAdd(g_globalMeshCounter, 1, offset);
}
```

Using this command-line `dxc -E csEntry -T cs_6_0 -spirv file.hlsl`

### Expected result
*Expected is the code to not compile due to bad storage (needs to be groupshared or buffer for example)*  

### Actual result
*The compiler reports the following error:*
```
fatal error: generated SPIR-V is invalid: AtomicIAdd: expected Pointer Storage Class to be Uniform, Workgroup, CrossWorkgroup, Generic, AtomicCounter, Image or StorageBuffer
  %14 = OpAtomicIAdd %uint %g_globalMeshCounter %uint_1 %uint_0 %uint_1

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Comment by antiagainst** [comment]
Thanks for the bug report! We'll fix this.

**Comment by ehsannas** [comment]
@emoon , `static uint g_globalMeshCounter` translates into a variable in `Private` storage class, and it is in fact local to the thread. It is not shared among threads. So, I believe the validator's complaint is legitimate.

We should, however, have a better error message from DXC, rather than failing in SPIR-V validator. I'll make this change.

**Comment by emoon** [comment]
Yeah I think it's correct that it doesn't compile but as you say the error message should be better.
