### ISSUE TITLE
DXC ignores functions shadowing intrinsics

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#1887]
Repro:
```
int abs(int x) { return 42; }
int main() : OUT { return abs(-1); }
```
DXC output: `call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 0, i32 1)`
FXC output: `mov o0.x, l(42)`

**Comment by llvm-beanz** [comment]
This is very much still a bug (see: https://godbolt.org/z/j4h45xeqf). That said, I think it is unlikely to be prioritized by itself. We have 3 proposals up for HLSL 202x that may result in resolving this issue to varying degrees:
 * [Moving builtin functions into a namespace](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0001-hlsl-namespace.md)
 * [Adopting C++ overload resolution rules](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0007-const-instance-methods.md)
 * [Math mode namespaces](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0009-math-modes.md)
 
 Since this issue was filed by a team member and not an external source I'm going to close this issue.
