### ISSUE TITLE
Structures forward declaration

### ISSUE THREAD

**Issue by siliconvoodoo** [microsoft/DirectXShaderCompiler#1895]
I noticed that DXC accepts forward declarations of structures, while FXC does not.

IMHO forwards should be forbidden because HLSL is a by-value semantic language, where forwards bring nothing interesting to the table, since not fully defined types are unusable. And being available as non-error constructs misleads the users "it's accepted so I'll try hard using it, until I realize it makes no sense".

EDIT:
in fact it might make sense for function declarations:

```
struct S;
void func(S);

struct S {};
void func(S s) {}
```

**Comment by MrTrillian** [comment]
Fair point, thanks for reporting. Tagged as enhancement since it's not really a bug and doesn't break any scenario.

**Comment by simondeschenes** [comment]
Actually, because of the #include, it is quite nice that we finally have this feature.
Previously, we would have  to put a function in its own header file to make sure the first header that used it would include it as the first thing it does.

With forward declaration, we can actually #include files in random order and it doesn't matter.
Please keep it as is.

**Comment by llvm-beanz** [comment]
While I understand the original thinking. Removing forward declaration support in DXC would only be something we could do short-term since we have plans to add references to the language:
https://github.com/microsoft/hlsl-specs/blob/main/proposals/0006-reference-types.md
