### ISSUE TITLE
FXC vs DXC: Inconsistent offsets when using register(c#)

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#1900]
Hi!

I've been trying to figure out the rules around using `register(cX)`.

When trying to figure out the correct behavior, I noticed that DXC/DXIL does not generate the same output as FXC.

My HLSL code:
```hlsl
float x : register(c10);
float y;
float z: register(c1);

float4 main(float4 Pos : Position) : SV_Position {
  float4 output = Pos;
  output.x    += x;
  output.y    += y; 
  output.z    += z;
  return output;
}
```

Output from FXC(`fxc.exe -T vs_5_1 shader.hlsl`):
```
//
// Buffer Definitions:
//
// cbuffer $Globals
// {
//
//   float x;                           // Offset:  160 Size:     4
//   float z;                           // Offset:   16 Size:     4
//   float y;                           // Offset:   20 Size:     4
//
// }
//
```

Output from DXC/DXIL (`dxc.exe -T vs_6_0 shader.hlsl`):
```
; Buffer Definitions:
;
; cbuffer $Globals
; {
;
;   struct $Globals
;   {
;
;       float x;                                      ; Offset:  160
;       float y;                                      ; Offset:  164
;       float z;                                      ; Offset:   16
;
;   } $Globals                                        ; Offset:    0 Size:   168
;
; }
;
```

In both cases, `x` is at offset 160, and `z` is at offset 16.

But FXC places `y` at offset 20, whereas DXC places `y` at offset 164.

1- Is there any documentation about how offsets should be calculated when `register(cX)` is used?
2- Is this a bug in DXC? Or is it an intentional change?
3- For a global variable for which the offset is not specified using `register(c`, how do we calculate the correct offset? The DXC behavior shown above seems to suggest it assigns offsets **after the last offset that was calculated by the register annotation**. But the FXC behavior is not clear to me (it looks like it's trying to "fill the gap" by using unused offsets... but why doesn't it use offset 0?)

Thanks for your help :)

**Comment by MrTrillian** [comment]
It looks like FXC took care of all globals with an explicit register assignment first, and then proceeded to allocate the rest of them starting at where it left off, hence why it outputs z before y and lays out y right after z. In any case, this is a bizarre behavior and we're incompatible so it needs fixing. Thanks for reporting!

**Comment by ehsannas** [comment]
I'm wondering why FXC doesn't use offset 0 though?

**Comment by ehsannas** [comment]
Can I assume that the FXC behavior is the correct/intended one?

**Comment by MrTrillian** [comment]
Probably at least the one we should to stay compatible with. @tex3d , any more insights?

**Comment by tex3d** [comment]
This appears to be a bug in fxc's shader model 5.1 allocator.  All other shader models fxc compiles to match dxc's behavior.  I think it makes the most sense to stick with this behavior and consider the 5.1 difference a bug, since most existing content is not SM 5.1, and especially since the purpose of this register binding was specifically for DX9 constant registers, and is not commonly used for constant buffers.

**Comment by tex3d** [comment]
For more specific answers to the questions:
1. register(cX) was originally intended to give you control over what register constants were bound to in DX9, corresponding to the index provided to the SetVertexShaderConstantF API.  When translating this language construct to constant buffer elements for DX10, this translates to an offset into the constant buffer of this index * 16 bytes, since this corresponds to the float4 vector in the original vertex shader constants.  There doesn't appear to be any documentation I can easily find that describes the behavior of automatic allocation in the presence of partial explicit bindings.
2. Since all shader models, with the exception of 5.1, auto-allocate after highest explicit address, I would say that's basically the de-facto standard for supporting this situtation.
3. As I mentioned, it's calculated as the next available location (that fits with packing rules) after the explicitly bound element with the highest address.  fxc's 5.1 behavior appears to be using the last explicitly bound element in declaration order, rather than in address order, which is why it appears to be "filling in the gap" but doesn't start at 0.

Techically, the new way to do this sort of offsetting for DX10+ is with `packoffset` instead of `register`.  When using `packoffset`, it is illegal to mix explicit and automatic binding - you must use packoffset on every cbuffer element or struct member.  This ensures well-defined consistent behavior at least.  We should deprecate the register(c#) construct, I suspect, since it's more a source of bugs and confusion, than necessary and useful at this point (note: often people wonder why it doesn't impact the constant buffer binding slot itself, when placed on a global variable or on a cbuffer declaration (where it's supposed to be b#, not c#).

**Comment by ehsannas** [comment]
Thanks for the detailed explanation, @tex3d ! This makes everything much more clear.

**Comment by MrTrillian** [comment]
Following @tex3d 's recommendation, we're sticking with the current behavior and can close this.
