### ISSUE TITLE
[SPIR-V] Convert half to float resulting fatal error

### ISSUE THREAD

**Issue by gongminmin** [Microsoft/DirectXShaderCompiler#1914]
Try to mix using half and float, some warnings become fatal errors.

Here is the shader code:
```
void Func(half3 input, out half3 output)
{
    output = input;
}

float4 PS_Main() : SV_Target0
{
    float3 output;
    Func(cross(float3(1, 0, 0), float3(0, 1, 0)), output);
    return float4(output, 1.0f);
}
```
It can be reproed by these options:
`dxc shader.hlsl -E PS_Main -T ps_6_2 -enable-16bit-types -spirv`

The output message is:

> shader.hlsl:9:10: warning: conversion from larger type 'vector<float, 3>' to smaller type 'half3', possible loss of data
>     Func(cross(float3(1, 0, 0), float3(0, 1, 0)), output);
>          ^
> shader.hlsl:9:51: warning: conversion from larger type 'float3' to smaller type 'half3 &', possible loss of data
>     Func(cross(float3(1, 0, 0), float3(0, 1, 0)), output);
>                                                   ^
> **fatal error: generated SPIR-V is invalid: Result type (OpTypeFloat) does not match the type that results from indexing into the composite (OpTypeFloat).
>   %19 = OpCompositeExtract %float %18 0**
> 
> note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

**Comment by ehsannas** [comment]
Thanks for reporting. I'll take a look.

**Comment by ehsannas** [comment]
The error is because the generated SPIR-V code is trying to pass `output` which is a `float3` directly to a function that takes a `half3` as argument.

**Comment by ehsannas** [comment]
This case seems to be due to a bad AST. Here's the AST for the above code:

```
-CallExpr 0x2a793152da0 <line:9:5, col:57> 'void'
 |-ImplicitCastExpr 0x2a793152d88 <col:5> 'void (*)(half3, half3 &__restrict)' <FunctionToPointerDecay>
 | `-DeclRefExpr 0x2a793152d08 <col:5> 'void (half3, half3 &__restrict)' lvalue Function 0x2a793143d88 'Func' 'void (half3, half3 &__restrict)'
 |-ImplicitCastExpr 0x2a7931531f0 <col:10, col:48> 'vector<half, 3>' <HLSLCC_FloatingCast>
 | `-CallExpr 0x2a793152c80 <col:10, col:48> 'vector<float, 3>':'vector<float, 3>'
 |   |-ImplicitCastExpr 0x2a793152c68 <col:10> 'vector<float, 3> (*)(vector<float, 3>, vector<float, 3>)' <FunctionToPointerDecay>
 |   | `-DeclRefExpr 0x2a793152bd0 <col:10> 'vector<float, 3> (vector<float, 3>, vector<float, 3>)' lvalue Function 0x2a7931529a8 'cross' 'vector<float, 3> (vector<float, 3>, vector<float, 3>)'
 |   |-CXXFunctionalCastExpr 0x2a793144680 <col:16, col:30> 'float3':'vector<float, 3>' functional cast to float3 <NoOp>
 |   | `-InitListExpr 0x2a7931444e0 <col:23, col:29> 'float3':'vector<float, 3>'
 |   |   |-ImplicitCastExpr 0x2a793144498 <col:23> 'float' <IntegralToFloating>
 |   |   | `-IntegerLiteral 0x2a793144420 <col:23> 'literal int' 1
 |   |   |-ImplicitCastExpr 0x2a7931444b0 <col:26> 'float' <IntegralToFloating>
 |   |   | `-IntegerLiteral 0x2a793144448 <col:26> 'literal int' 0
 |   |   `-ImplicitCastExpr 0x2a7931444c8 <col:29> 'float' <IntegralToFloating>
 |   |     `-IntegerLiteral 0x2a793144470 <col:29> 'literal int' 0
 |   `-CXXFunctionalCastExpr 0x2a7931447d0 <col:33, col:47> 'float3':'vector<float, 3>' functional cast to float3 <NoOp>
 |     `-InitListExpr 0x2a793144778 <col:40, col:46> 'float3':'vector<float, 3>'
 |       |-ImplicitCastExpr 0x2a793144730 <col:40> 'float' <IntegralToFloating>
 |       | `-IntegerLiteral 0x2a7931446b8 <col:40> 'literal int' 0
 |       |-ImplicitCastExpr 0x2a793144748 <col:43> 'float' <IntegralToFloating>
 |       | `-IntegerLiteral 0x2a7931446e0 <col:43> 'literal int' 1
 |       `-ImplicitCastExpr 0x2a793144760 <col:46> 'float' <IntegralToFloating>
 |         `-IntegerLiteral 0x2a793144708 <col:46> 'literal int' 0
 `-DeclRefExpr 0x2a793152cb8 <col:51> 'float3':'vector<float, 3>' lvalue Var 0x2a7931442d0 'output' 'float3':'vector<float, 3>'
```

Even though the function signature is:
```
 'void (*)(half3, half3 &__restrict)'
```
the second argument (which is a float3) is passed to the function **without** a Cast AST node:
```
DeclRefExpr 0x2a793152cb8 <col:51> 'float3':'vector<float, 3>' lvalue Var 0x2a7931442d0 'output' 'float3':'vector<float, 3>'
```

Interestingly, the first argument is properly casted to half3 before being passed to the function:
```
ImplicitCastExpr 0x2a7931531f0 <col:10, col:48> 'vector<half, 3>' <HLSLCC_FloatingCast>
```

@MrTrillian @tex3d , can someone on your side fix the AST?

**Comment by MrTrillian** [comment]
I happen to be looking into similar bugs. Unfortunately, FXC allows passing an lvalue of a convertible type as the argument to an `inout` or `out` parameter, and it implies potentially a conversion to and from the lvalue type (float lvalue -> inout half -> float lvalue after the call). This cannot be expressed by a cast because

1. Casts always result in rvalues (since HLSL has no references), which cannot be bound to an inout/out param. (This is not always the case in the AST, which is what I'm looking into).
2. Casts are only for one-way conversions, we can't run the cast in reverse for inout parameters after the function executes.

So I think HLSL has to allow binding convertible lvalues as byref arguments. Unfortunately this means that the conversion has to happen automagically by some other part of the code, a bit like flat conversions between structures which imply a whole lot of individual element conversions that never appear in the AST. Although maybe there is a way to store the in/out conversions as part of whatever clang uses to represent arguments in the argument list - I'm not yet quite familiar with that code.

**Comment by ehsannas** [comment]
I see. Thanks for the explanation @MrTrillian

**Comment by ehsannas** [comment]
Fixed.
