### ISSUE TITLE
Inconsistent RWByteAddressBuffer uint64_t store behavior between SM6.2 and 6.3

### ISSUE THREAD

**Issue by MrTrillian** [Microsoft/DirectXShaderCompiler#1972]
Repro:
```
RWByteAddressBuffer buf;
void main() { buf.Store(0, (uint64_t)0x7766554433221100); }
```
vs_6_2 output (truncation to i32 + output as i32):
`call void @dx.op.rawBufferStore.i32(i32 140, %dx.types.Handle %buf_UAV_rawbuf, i32 0, i32 undef, i32 857870592, i32 0, i32 undef, i32 undef, i8 3, i32 8)`
vs_6_3 output (truncation to i32 + output as i64):
`call void @dx.op.rawBufferStore.i64(i32 140, %dx.types.Handle %buf_UAV_rawbuf, i32 0, i32 undef, i64 857870592, i64 undef, i64 undef, i64 undef, i8 1, i32 8)`

**Comment by tex3d** [comment]
This is appears to be a bug with hex parsing of literal ints.  It doesn't appear to support 64-bit value without the long long suffix (LL).

**Comment by tex3d** [comment]
The rest of the behavior is expected.
SM 6.2 doesn't support the i64 overload on the DXIL op, so it splits it into two i32 arguments (the second being i32 0).  Note that the mask is 3, not 1.
SM 6.3 supports the i64 overload, so outputs an i64 because you asked for one.
The original value is a hex parsed value, but the hex parser will not automatically produce a 64-bit value without `LL` suffix.  So the value is truncated.

**Comment by MrTrillian** [comment]
@tex3d Oh, good catch! I'm closing this in favor of: #1973 then
