### ISSUE TITLE
[SPIRV] Emit ShaderRecordBufferNV in ray hit shader

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#2019]
It looks like this may have been an oversight in #1920  but right now it seems impossible to read the extra data that one can insert in the shader binding table. I know there are some differences here with how DirectX does things but it's critical to be able to read SBT data in the hit shaders.

**Comment by ehsannas** [comment]
Thanks for reporting @Jasper-Bekkers !

**Comment by ehsannas** [comment]
@alelenv @sparmarNV Would you please share your thoughts?

**Comment by alelenv** [comment]
@Jasper-Bekkers : 
HLSL does not expose SBT buffer in shading language directly as Vulkan GLSL does. Resources in SBT are exposed via local root signatures in API.
Currently there is no support for local root signatures only global. We hope to add support for local root signatures in the short term
Thanks

**Comment by Jasper-Bekkers** [comment]
@alelenv My use case right now is just to read a simple integer from the SBT and have no need directly to bind buffers in the SBT like one would in DirectX. I think once we at SEED full on start our Vulkan port we'll run into that though, but I'm not sure if shader-compiler emulation is preferable over a spec change for this.

**Comment by alelenv** [comment]
Since there is nothing in HLSL, by spec change do you mean something looking like this?
[[vk::shaderrecordnv]] struct S { int memA; float4 memB; }

Or do you have any other suggestions for your use case?

**Comment by Jasper-Bekkers** [comment]
Either that, or an amendment to the VK_NV_ray_tracing to allow for local root signatures.

**Comment by Jasper-Bekkers** [comment]
@alelenv alternative suggestion would be to reuse the `register` syntax:

`struct S { int memA; float4 memB; } : register(shaderrecordnv)`

**Comment by Jasper-Bekkers** [comment]
Had a discussion with @dgkoch about this and he mentioned one should be able to use EXT_buffer_device_address to put addresses to buffers into the SBT which might also be relevant for this ticket.

**Comment by punkUser** [comment]
We should sync more on this but since these are effectively "local root constants" the cleanest way is likely to map them to a cbuffer binding in HLSL, as would be the case if you make a local root signature with root constants. Ideally if we could configure which space it mapped to from Vulkan that would be perfect, but failing that mapping it to some "special" space might work, i.e. `ConstantBuffer<MyConstants> myConstants : register(b0, space7362);`

Obviously not that particular space, but given that's the namespacing mechanism in HLSL using that seems the cleanest.

**Comment by alelenv** [comment]
After discussing internally and with devs we are proposing adding [[vk::shader_record_nv]] annotation on ConstantBuffer/cbuffer which will be mapped to a read-only block in ShaderRecordBufferNV storage class

This allows same source to be used for with DXR as well as being compatible with slang as pointed out by @tfoleyNV in issue above.
Similar to push constants, it is an error to use vk::binding annotation and no more than one shader record block can be statically used by an entry point otherwise results are undefined.

@ehsannas : Any thoughts on this proposed feature?
Thanks!

**Comment by punkUser** [comment]
Naively that seems like it would work and unblock our immediate use cases. Long term I'd love to come up with a cleaner way to unify the binding between the two APIs further but as binding is a major area where there's likely to be divergence, marking one of our cbuffers as the "local" one (and avoiding using multiple of them in the same shader) seems like a workable solution for now and indeed less hacky than a magic "space" or similar.

**Comment by alelenv** [comment]
@ehsannas : Can you take a look so we that could upstream a PR soon?
Thanks!

**Comment by ehsannas** [comment]
@alelenv I'm reviewing the issue, and trying to see if there is a more fundamental change/"fix" that could be made with wider benefits. I'll get back to you by the end of next week. Thanks for the great discussion everyone.

**Comment by ehsannas** [comment]
Hi @alelenv 
Sorry for the delay. I have been trying to get in touch with the people at Vulkan to see if there is a better / more fundamental solution for bridging the root signature gap and aligning the two APIs more closely. Crystalizing and executing that will take some time -- and I don't want you and others to be blocked by that. So, please feel free to put up a PR for your `[[vk::shader_record_nv]]` proposal.

If/once there is a better solution, we can implement a new methodology and deprecate older methods if necessary.

Thanks for your help! :)

**Comment by ehsannas** [comment]
Thanks for the implementation folks. This has been merged.
