### ISSUE TITLE
Crash on calling Interlocked*** with non-int/uint type

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#2077]
Repro (`-T vs_6_2 -enable-16bit-types`):
```
groupshared uint gs_uint;
groupshared int gs_int;
groupshared bool gs_bool;
groupshared float gs_float;
groupshared int16_t gs_int16;
groupshared int64_t gs_int64;

void main()
{
  InterlockedAdd(gs_uint, 1);
  InterlockedAdd(gs_int, 1);
  // All the below crash
  InterlockedAdd(gs_bool, 1);
  InterlockedAdd(gs_float, 1);
  InterlockedAdd(gs_int16, 1);
  InterlockedAdd(gs_int64, 1);
}
```

This is likely due to the weird special cases we have for `Interlocked***`'s first parameter not being marked `inout` but being special-cased to become a reference type.

**Comment by pow2clk** [comment]
This is related to the special case that makes the first argument a reference. Because of that, an `addrspacecast` is used, but dxilgen explicitly ignores such casts so the pointer that is ultimately passed to `InterlockedAdd` is of the wrong type.

For this reason, all `interlocked*` intrinsics should have `NOCAST` types for this parameter. Soon they shall!
