### ISSUE TITLE
[HLSL] Feature request: user defined class templates.

### ISSUE THREAD

**Issue by thatname** [microsoft/DirectXShaderCompiler#2145]
Hi !
If we have user defined Templates / Generics in HLSL, like NVIDIA's Slang shading language, we can write complex shaders easier.  DXC is based on Clang, a C++ compiler which supports templates.  Is it possible to enable this syntax for DXC ?

**Comment by thatname** [comment]
I've forked and modified the code, It seems like my fork accepts user defined templates now.

**Comment by MrTrillian** [comment]
This is something we're thinking about but we don't have short-term plans to enable this. Clang does support it but HLSL semantics are different, so I expect many edge cases.

It helps to know what your scenario is, though. Are you doing math and templating on the numeric type?

**Comment by simondeschenes** [comment]
I have been coding a "second" preprocessor that now sits between the preprocessor and the actual compilation phase in order to re-implements the interface/class paradigm that allowed generic programming (that disappeared between FXC and DXC).

Templates would actually provide the same flexibility.

So, here is how it works :
- First I preprocess the shader using the standard preprocessor
- Then I preprocess the interfaces with my "in-between" parser/preprocessor which also adjust the #line preprocessors for duplicated code
- Then I call DXC

My "in-between" preprocessor converts this code :
`interface ILight
{
    float3 ComputeDiffuse(...);
};
 
class PointLight : ILight
{
    float3 position;
    float3 intensity;
    float radius;

    float3 ComputeDiffuse(...)
    {
        ...
    }
};
 
class DirectionalLight : ILight
{
    float3 direction;
    float3 intensity;

    float3 ComputeDiffuse(...)
    {
        ...
    } 
}

float4 ShadePixel(ILight aLight, ...)
{
    ...
    float3 diffuse = light.ComputeDiffuse(aLight, ...);
   ...
}

float4 PSMain() : SV_Target
{
    DirectionalLight dirlight;
    dirlight.direction = float3(0.0f, 0.0f, -1.0f);
    dirlight.intensity = float3(1.0f, 0.0f, 0.0f);

    PointLight pointLight;
    pointLight.position = float3(0.0f, 0.0f, 1.0f);
    pointLight.intensity = float3(0.0f, 1.0f, 0.0f);

    return ShadePixel(dirlight, ...) + ShadePixel(pointLight, ...);
}
`

to 

`struct PointLight
{
    float3 position;
    float3 intensity;
    float radius;
};
 
float3 ComputeDiffuse_PointLight(PointLight aSelf, ...)
{
    ...
}

struct DirectionalLight
{
    float3 direction;
    float3 intensity;
}

float3 ComputeDiffuse_DirectionalLight(DirectionalLight aSelf, ...)
{
    ...
}

float4 ShadePixel_PointLight(DirectionalLight aLight, ...)
{
    ...
    float3 diffuse = ComputeDiffuse_PointLight(aLight, ...);
   ...
}

float4 ShadePixel_DirectionalLight(DirectionalLight aLight, ...)
{
    ...
    float3 diffuse = ComputeDiffuse_DirectionalLight(aLight, ...);
   ...
}

float4 PSMain() : SV_Target
{
    ...

    DirectionalLight dirlight;
    dirlight.direction = ...;
    dirlight.intensity = ...;

    PointLight pointLight;
    pointLight.position = ...;
    pointLight.intensity = ...;
    ...

    return Shade_DirectionalLight(dirlight, ...) + Shade_PointLight(pointLight, ...);
}`

As you can see, "ShadePixel", just like every function that receives a types that implement an interface will be copy-pasted with the argument shuffled and the function calls altered.

That isn't that bad, now that I am done doing this.
However, it would have been nice to have either templates or support for interfaces and classes like we had before.

A thing to note is that I didn't want to modify DirectXShaderCompiler itself and have to maintain the fork while DXC gets updated. This is why I went that route instead of doing what @thatname did.

I never had any use for doing math on the numeric type of a template in shader code though. So, even if only "type genericity" was supported, I would have been happy.

**Comment by simondeschenes** [comment]
It should also be noted that function overload, even if the types are different doesn't always work. It looks like it considers unrelated structs as ambiguous. So, I actually have to rename methods with _Type for each permutation.

However, this seems to be the same behaviour as FXC. It is surprising to see that sometimes function overload work, and sometimes it doesn't. I haven't figured why.

**Comment by MrTrillian** [comment]
That's a cool proof of concept! Note that overloading works differently in HLSL and C++ because the type system works differently: two structs with identical layouts are considered aliases of each other, so you would get an ambiguity if both of your classes held 7 `float` values, for example.

**Comment by simondeschenes** [comment]
Thanks for the explanation about the ambiguity and identical layouts. It is a little unfortunate to have these differences between HLSL and C++, but I suppose it helps generating more efficient code to consider all structs that have the same layout as the same type.

**Comment by MrTrillian** [comment]
It's really for historical reasons and due to the way the language evolved. Changing that would break a lot of code.

**Comment by gabadie** [comment]
> That's a cool proof of concept! Note that overloading works differently in HLSL and C++ because the type system works differently: two structs with identical layouts are considered aliases of each other, so you would get an ambiguity if both of your classes held 7 float values, for example.

> It's really for historical reasons and due to the way the language evolved. Changing that would break a lot of code.

We have **nowhere** in UE4's production code base where we use that on purpose, because let's be honest: it's unreadable, and let me just illustrate why: "what override of the function `Add(A, B)` is this going to use for my `struct DenoisingSample`? oh now I need to compare memory layout of my `DenoisingSample` structure with all the one that have overriden `Add()` instead of `ctrl+f` for `Add(DenoisingSample` in the code base... Great..."

We have few shaders, like the denoiser, that are about **8500+ lines of code**, and is becoming challenging/impossible to maintain and improve performance without templates.

What about a compiler option to compile as "legacy hlsl" to smooth transition on per shader basis for code bases that might have relied on this?

**Comment by kayru** [comment]
> What about a compiler option to compile as "legacy hlsl" to smooth transition on per shader basis for code bases that might have relied on this?

There's already a compiler option to select the HLSL version. We are indeed completely fine with dropping the old overloading rules and other legacy, getting us closer to C++. Some of the compilers that we use do not follow HLSL rules already.

Getting function templates plus few other C++ features such as constexpr and lambdas is going to significantly improve the maintainability and quality of shaders in Unreal Engine. This is not a theoretical statement either, as we already use these features on some platforms (in certain platform-specific shaders that are never compiled by fxc/dxc).

Without templates, we have to use macros and trust in perfect const folding / DCE optimizations. In practice, we have a few examples in the engine where DXC is actually unable to perform the same optimizations as FXC, resulting in worse codegen, failure to remove access to some textures, etc.

**Comment by MarcusWassmerEPIC** [comment]
Agreed.  EPIC is extremely interested in improvements in this area.

**Comment by gwihlidal** [comment]
+1    Improvements here would be most appreciated.

**Comment by vaspoul** [comment]
Came here looking for this exactly. Template support for newer shader models would be absolutely fantastic!
I'm also looking at a preprocessor / language extender as the OP.

**Comment by john-h-k** [comment]
Agreed. Templates would make writing a lot of numeric operations a lot prettier

**Comment by pow2clk** [comment]
Preliminary support by @tcorringham has been merged into a side branch with plans to bring it to master when more mature (see #3533) `-enable-templates` flag is required. Support is roughly at the level of c++98

**Comment by simondeschenes** [comment]
Wonderful news. I will try it.

**Comment by anooprthomas** [comment]
is there an ETA to when this feature will be merged in to master? Here's my use case: 

template<T>
T GetBufferElement(int descriptorIndex, int index)
{
	ByteAddressBuffer rawBuffer = ResourceDescriptorHeap[descriptorIndex];
	T element = rawBuffer.Load<T>(index);
	return element;
}

I'm forced to use ByteAddressBuffers due to supporting bindless on both D3D12 and Vulkan API's. Having the above templated code work would help a lot.

**Comment by pow2clk** [comment]
Templates have been merged into main as part of HLSL202. Use `-HV 2021` to enable them
