### ISSUE TITLE
error: local resource not guaranteed to map to unique global resource. Use /Zi for source location.

### ISSUE THREAD

**Issue by galop1n** [microsoft/DirectXShaderCompiler#2246]
Hi,

We are encountering the error shown in the issue subject line in some of our shaders. There was a reference of it found in google cache of the github with the minimal repro below. The major issue is that the /Zi flag does not produce any details to pinpoint the problem.
 
// RUN: dxc -T lib_6_3 -Zi %s
// resource uses must resolve to a single resource global variable (single rangeID)
// CHECK: error: local resource not guaranteed to map to unique global resource
RWStructuredBuffer<float2> buf0;
RWStructuredBuffer<float2> buf1;
void Store(bool bBufX, float2 v, uint idx) {
RWStructuredBuffer<float2> buf = NonUniformResourceIndex(bBufX) ? buf0: buf1;
buf[idx] = v;
}

**Comment by tex3d** [comment]
With the following fixed repro:
```
// RUN: %dxc -T lib_6_3 -Zi
// resource uses must resolve to a single resource global variable (single rangeID)
// CHECK: error: local resource not guaranteed to map to unique global resource
RWStructuredBuffer<float2> buf0;
RWStructuredBuffer<float2> buf1;
export void Store(bool bBufX, float2 v, uint idx) {
  RWStructuredBuffer<float2> buf = NonUniformResourceIndex(bBufX) ? buf0: buf1;
  buf[idx] = v;
}
```

This is what I get:
```
> dxc repro.hlsl -T lib_6_3 -Zi
error: repro.hlsl:7:36: local resource not guaranteed to map to unique global resource.
warning: no output provided for debug - embedding PDB in shader container.  Use -Qembed_debug to silence this warning.
```

`-Zi` enables the source location of the expression that does not map to a single global resource.  What is the behavior you're seeing?  Perhaps in a complex scenario, source location gets lost, so it's unable to provide it.  If so, we are working to improve the debug information, and know there are still holes here.  If you can share a real repro with us, it improves the chances that the problem will be fixed earlier rather than later.

Note: `export` is required (or `-default-linkage` external option) in this case so the library won't be empty.

**Comment by tex3d** [comment]
Closing, as the simple repro does show source location.  Re-open with new repro that shows a missing source location with -Zi.
