### ISSUE TITLE
ByteAddressBuffer.Load<T> with normalized signed short

### ISSUE THREAD

**Issue by galop1n** [microsoft/DirectXShaderCompiler#2260]
I replaced some unpacking of vertex data read from a ByteAddressBuffer in hope the driver code gen can take advantage of typed load behind the scene. I got it work for halfs values. And i wonder if i can do better for the snorm shorts case.

Both compiles but :
Incorrect result : `float4 tbn = vertices.Load<snorm half4>(stride * i + 8);`
Correct result : `float4 tbn = vertices.Load<int16_t4>(stride * i + 8) / float(0x7FFF);`

The way i understand the snorm tag for UAV types should be the same here and i would have expect that to work. 

Subsidiary question, why does the compiler reject short4 and only accept int16_t4, it even complains that short is a reserved keyword in the first place, the compiler arguments have `-HV 2018 -enable-16bit-types` and it is needed even for the typed half load, but i wonder if it should be enforced in that context. Especially because nVidia GPU does not support min precision on their device anyhow…

**Comment by MrTrillian** [comment]
Hi galop1n! `snorm` isn't the same as loading an `int16_t` and dividing by `float(0x7FFF)`. `snorm` means "load a value from a typed buffer using its application-defined format which is one of the _SNORM ones". Your shader resource view format like `DXGI_FORMAT_R8G8B8A8_SNORM` or `DXGI_FORMAT_R16_SNORM` is what determines how much data is read, the `snorm` only indicates how to interpret it as a floating-point value (it needs to match between your DXGI_FORMAT and HLSL), and then your use of `half` or `float` in hlsl is just how you want to consume that value. `snorm` should not be viewed as a different kind of float and doesn't do anything in non-typedbuffer contexts.

The problem here is that a `ByteAddressBuffer` is not a typed buffer and so does not support these kinds of format conversions which depend on the shader resource view format. If that's what you need, use a `[RW]Buffer`.

**Comment by galop1n** [comment]
Let me reformulate what i meant, because, no, what i need is not a [RW]Buffer.

In the context of regular draws, the vendors do not have the input assembler anymore, they rely on typed load instruction, that are not expose in the HLSL language.

In the context of raytracing, or within a compute, or any manual vertex fetching technique, you have to rely on a ByteAddressBuffer and perform manual decoding of your interleaved data. As such, you have to write boiler code ( shifting, masking, scaling, ...) that the vendors are less likely to recognize, it means less than optimal shader generation.

The Load<T> of the ByteAddressBuffer looks like a good candidate to keep things clean on the DXIL bytecode side. The requirement for it to work, is the ability to describe the type you want to read.

In that sense, mapping the original `DXGI_RGBA16_SNORM` to `snorm half4` in HLSL is exactly how you would have done it with a [RW]Buffer in the first place. But because it is interleaved vertex data, you have to rely on ByteAddressBuffer.

And in any case, if it is an invalid scenario, at the very least, the compiler should have reject the syntax.

**Comment by MrTrillian** [comment]
I see what you mean, but you would need more information than `snorm half2` to distinguish between `DXGI_FORMAT_R16G16_SNORM` and `DXGI_FORMAT_R8G8_SNORM`, for example. You would need to be able to specify that enum in HLSL or something similar. I'm taking note of this but feel free to file a feature request issue. The team is currently on hardware-facing features and bugfixing will likely be for the coming 6+ months, but we do plan on adding language features afterwards.

You're right that we accept the `snorm`/`unorm` syntax too broadly, I've filed a bug on it: #2264
