### ISSUE TITLE
DXC: Validation error

### ISSUE THREAD

**Issue by jirzynek** [microsoft/DirectXShaderCompiler#2268]
Hi,

When compiling with the DXC (latest github) the following code
```
// dxc.exe test.hlsl -nologo -flegacy-macro-expansion -O3 -Tcs_5_1 -Etest_cs -Fo"test.bin"

RWTexture2D<float2> uav;

[numthreads(1, 1, 1)]
void test_cs(min16uint3 tid : SV_DispatchThreadID)
{
    min16uint2 val = 2; // ERROR
    //min16uint2 val = 0;  // OK
    
    if (tid.x >= val.x)
        return;

  uav[uint2(0, 0)] = 0;
}
```

I'm getting:
```
error: validation errors
invalid record
Validation failed
```
error. However if I change val = 2 to val = 0 then it compiles fine.

EDIT: There is also no line/file information in the error. This makes narrowing it down difficult and time consuming especially when the shader code base is large.

**Comment by tex3d** [comment]
The compiler is going off the rails earlier because of the input `min16uint3 tid : SV_DispatchThreadID`.  It asserts when getting the overload for the intrinsic, since it only expects `uint3` here, not `min16uint3`.  This should have been caught and possibly translated to a `uint3` input earlier (if we should support it - I suppose we will have to if fxc does).

Normally, line/file information can be obtained for validation errors by supplying the `-Zi` option to include debug information, so source information is still available at that point, but in this case, I doubt it would have helped.

Thanks for the report!
