### ISSUE TITLE
[SPIRV] SPIR-V OpLine Line Numbers Off By One

### ISSUE THREAD

**Issue by greg-lunarg** [microsoft/DirectXShaderCompiler#2333]
The line numbers in the OpLine operations in the SPIR-V generated by dxc for the attached shader are off by 1, specificially 1 larger than they should be.

FWIW, I am guessing its because dxc is using the preprocessed version of the HLSL which has a #line inserted at the top which increases all original line numbers by one.

Here is the dxc command line which generates the bad SPIR-V:

dxc.exe -spirv -E MainPs -T ps_6_0 -fspv-debug=line -fspv-target-env=vulkan1.1 -Od -Zi hlsl.pp.line2.frag -Fo hlsl.pp.line2.frag.spv

The HLSL is attached. Remove the .txt suffix before compiling.

[hlsl.pp.line2.frag.txt](https://github.com/microsoft/DirectXShaderCompiler/files/3383949/hlsl.pp.line2.frag.txt)

**Comment by ehsannas** [comment]
@greg-lunarg you're certainly right. It is off by 1 because it is using the preprocessed version of the HLSL which has a #line inserted at the top.

We've been back and forth on what's the right way to do it -- the way it is today, the line numbers are correct when you look at the `OpSource` at the top of the SPIR-V module which contains the preprocessed HLSL.

**Comment by greg-lunarg** [comment]
I see your viewpoint. However, my vote would be to decrease the line numbers by 1 as that is what the validation layer will expect when they attempt to navigate the code in the OpSource and print the actual line of source. The validation layer will expect that line 1 of hlsl.pp.line2.frag will be the line that follows "#line 1 hlsl.pp.line2.frag", that is, the line "#line 1 foo.frag".

**Comment by ehsannas** [comment]
I'm just wondering what's correct line number in cases where `#include "another_shader.hlsl"` is performed? @jaebaek has been doing a lot of work in this area.

**Comment by ehsannas** [comment]
We refer to the line numbers in the preprocessed HLSL that has all the concatenated code for includes.

**Comment by greg-lunarg** [comment]
> I'm just wondering what's the correct line number in cases where #include "another_shader.hlsl" is performed? @jaebaek has been doing a lot of work in this area.

> We refer to the line numbers in the preprocessed HLSL that has all the concatenated code for includes.

The validation layers (and pretty much any other tool, I think) ultimately must rely on the source that is supplied using OpSource commands.

I think it is fine if there is one OpSource instruction and its contents do not exactly match the original source file. For example, it is fine if there is just one OpSource instruction and it contains the results of running a textual preprocessor on the original file.

I think the best way to think about it is that the validation layers (and probably any other tool) will use the #line's in the OpSource to navigate. If they are trying to find line L of file F, they will search all OpSources for #lines for file F and search below for line L, if it is there. If the OpSource does not start with a #line, it will assume it starts with a #line for line 1 of the filename in the OpSource instruction.

This means that the compiler should create OpLine instructions by the following rule: given a (non-#line) line of source in an OpSource, search up until you find a #line %filename L. The filename of the line is %filename and the line is L + (S - 1) where S is the number of lines you had to search up to get to the #line. If no #line is found, assume the OpSource starts with a #line for line 1 of the filename in the OpSource instruction.

Obviously all of this is just based on how we decided to navigate the source and line info using the validation layers, but I do think it is consistent with the way renderdoc does things as well.

Let me know if you have further questions, concerns.

**Comment by jaebaek** [comment]
@greg-lunarg Thank you for the kind explanation. I was confused about two concepts: information from (filename, line number, column number) and the information of `OpSource`. Actually, based on `OpLine` spec, they are independent information.

I agree with your opinion, but let me doublecheck my understanding. The correct (or more reasonable) approach for this issue is that we must use the line number and column number information based on **its original source file**, not based on `OpSource`, right?

If a SPIR-V file is generated by multiple HLSL files because of `#include`, we must provide multiple file names and each `OpLine` must refer a correct file name, but the line and column numbers must be based on its original location. Please let me know if I misunderstand something here.

**Comment by greg-lunarg** [comment]
> we must use the line number and column number information based on its original source file, not based on OpSource, right?

Yes.

> If a SPIR-V file is generated by multiple HLSL files because of #include, we must provide multiple file names and each OpLine must refer a correct file name, but the line and column numbers must be based on its original location.

Yes.

**Comment by greg-lunarg** [comment]
Appears fixed with #2344. Thanks!
