### ISSUE TITLE
Add validation rule against sampler feedback being used with different textures

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#2358]
It should be illegal to use a `FeedbackTexture2D` with different `Texture2D`s. We'll have to be conservative in implementing this rule since it may not always be verifiable statically.

**Comment by clandrew** [comment]
While it is true that you can't use one FeedbackTexture2D with different Texture2Ds, i.e., the spec has

> When a feedback map is bound to a resource, the feedback map can not be used for writing feedback for other resources and the resource cannot be used with other feedback maps.

I don't think the compiler is the right place to validate this kind of behavior because this is basically a "UAV write to non-existent binding" situation. The usual pattern when you try to write to an unbound UAV to simply have the right be a no-op, rather than have the compiler try to reason about it. And, like you say, oftentimes you can't statically know.

Because this type of validation belongs inside GBV rather than in the compiler, we should close this and pursue that instead.
