### ISSUE TITLE
Provide API or documentation precisely explaining packing rules in CBuffers

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2375]
The old FXC compiler has packing rules precisely specified here:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-packing-rules

The old Effects framework was able to provide developers with precise information about sizes, offsets, for all struct members, array elements, etc.

The New DXC does not have this API, and I found no documentation describing the rules.

There's some minimal info here:
https://github.com/microsoft/DirectXShaderCompiler/wiki/16-Bit-Scalar-Types
But it's incomplete.

And the D3D12 reflection API is very limited, provides info only for root constants/parameters in the cbuffer
`ID3D12ShaderReflectionVariable *var=cb->GetVariableByIndex(i)`
but if 'var' is a struct, or array, and you want to check the offsets/sizes of its members, then you're doomed. No API and no Docs.

**Comment by LautrecOfCarim** [comment]
Hi @GregSlazinski 

There is a detailed explanation of the packing rules found here:
https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#memory-layout-rules

It covers both constant and regular buffers' packing rules. The example struct they provide is good at identifying the different rules.

For any structure you doubt, you can test it directly by looking at the emitted code:
http://shader-playground.timjones.io/e2daa5a5d3cf4807a40013652425b65a

It will include the offset for every element in the ConstantBuffer. You'll have to actually reference it in your code of course, otherwise it gets removed.

**Comment by tex3d** [comment]
I hope this Wiki page satisfies the documentation request here:
https://github.com/microsoft/DirectXShaderCompiler/wiki/Buffer-Packing

It's a start that can be elaborated on, but should describe most (if not all) of the rules.  It describes a lot of cases the previous documentation did not.

**Comment by ehsannas** [comment]
This is very useful. Thanks @tex3d

**Comment by pow2clk** [comment]
Closing. If the docs are insufficient, please file a new bug on how it can be improved.
