### ISSUE TITLE
[spirv] Interlock operation error on unnecessary swizzle

### ISSUE THREAD

**Issue by Slagh** [microsoft/DirectXShaderCompiler#2409]
With the command-line ` -E main -T vs_6_0 -spirv` and this short repro:
```
RWTexture3D<uint> target			: register(u1);

struct VS_OUTPUT
{ 
    float4	Pos				: SV_Position;
};

void main(VS_OUTPUT input)
{
	uint3 index = uint3(0,0,0);
	InterlockedAdd(target[index].r, 1);   <<< ERROR
}
```

I receive the error 
> error: using static variable or function scope variable in interlocked operation is not allowed

Given that the type of `target` is already `uint`, the swizzle is unnecessary but also harmless. Removing the swizzle fixes the error.

(To me it appears that the `.r` swizzle on `target[index].r` is generating a temporary which is passed to the InterlockedAdd.)

Version: `dxcompiler.dll: 1.5 - 1.4.0.2338 (master, f8d0271d)`

**Comment by ehsannas** [comment]
Thanks for reporting @Slagh :)

**Comment by ehsannas** [comment]
The DXIL side also crashes on this shader. I'm wondering whether this should be considered invalid HLSL.

We currently don't generate a temporary variable for `.r`. We try to extract the value and pass it by value to the interlocked method (and therefore we recognize this is an error and we deliver the error to the user).

On the SPIR-V side, `target[index]` translates to and ImageRead:
```spir-v
          %8 = OpConstantComposite %v3uint %uint_0 %uint_0 %uint_0
         %18 = OpLoad %type_3d_image %target
         %19 = OpImageRead %v4uint %18 %8 None
```

The interlocked method does not (and should not) take its argument by value. Now, there is no way for us to pass `target[index].r` by reference to `InterlockedAdd`. Why?
* We cannot pass `%target` to the method (the method only takes **uints** by reference).
* We cannot create a temporary variable for `.r` because the argument to the interlocked method should not have a "Function" scope.
* We cannot create a reference (&) to the result of ImageRead because `OpAccessChain` is not allowed on image types (it is only allowed on structs, vectors, matrices, and arrays.

**Comment by ehsannas** [comment]
@jaebaek It looks like we may be able to use `OpImageTexelPointer`.

Meaning, instead of performing an `OpImageRead`, we can probably do:
```spir-v
OpImageTexelPointer --> takes a Coordinate as argument. Returns a pointer.
OpAtomicIAdd --> Use the pointer that results from the previous instruction.
```
Note that the `index` used in `target[index]` is in fact the coordinate (it's uint3).
