### ISSUE TITLE
DXC crashes (in Debug mode) for templated buffer Store

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#2438]
The shader:
```
// Run: %dxc -T cs_6_2 -E main -enable-16bit-types

ByteAddressBuffer buf;
RWByteAddressBuffer buf2;

struct S {
  float16_t3 a[3];
};

[numthreads(64, 1, 1)]
void main(uint3 tid : SV_DispatchThreadId) {
  S sArr[2] = buf.Load<S[2]>(tid.x);
  buf2.Store<S[2]>(tid.x, sArr);
}
```

Command:
```
dxc.exe -Tcs_6_2 test.hlsl -enable-16bit-types
```

This is the assert that's being triggered:
https://github.com/microsoft/DirectXShaderCompiler/blob/f89e3b7150b70e3dc417ed7fa87331a7a4c683d9/lib/HLSL/HLExpandStoreIntrinsics.cpp#L77-L78

(note that it'll only trigger in Debug builds)

**Comment by pow2clk** [comment]
This occurs because, for explicit templates with only one parameter that is an aggregate type that only contains numeric types, the return value is replaced with the type of the template parameter. This was first introduced in #804, but has been tweaked several times since. The change that introduce it didn't explain why it was needed, nor did any followup. Removing it passed unit testing. I'm not certain it's necessary.

This is all HL intrinsics, so they get completely replaced during dxilgen anyway. Still it's odd.

**Comment by pow2clk** [comment]
I worked it out. #2176 added a more generalized templating mechanism that the earlier TODO pined for, but failed to remove the explicit assignment that was meant only for the return type of the load. Now that type and the store argument that depend on the explicit template type are set as part of MatchArguments. The remaining assignment is unnecessary or, in the case of store, harmful. 

When support for templated store was added, instead of removing this assignment, it was left as-is and the store intrinsic took that path as well, converting its void return into one that the explicit template required. It was harmless except for the assert, but it's better to fix it anyway.
