### ISSUE TITLE
Implicit truncation of vector to constant causes crash

### ISSUE THREAD

**Issue by tafuri** [microsoft/DirectXShaderCompiler#2445]
Trying to compile the following invalid shader will cause a crash inside of `ConstExprEmitter::VisitCastExpr` instead of a compile warning/error.

```hlsl
float4 main() : SV_Target0
{
	const float error = float4(0,0,0,0);
	return error;
}
```

**Comment by vcsharma** [comment]
@tafuri Thanks for reporting this issue. This is actually a valid case which should compile. Compiler should do an implicit truncation from vector to scalar type as you have also indicated in the bug title.

I investigated this more and it turns out that there are other related scenarios as well where compiler fails to compile. Here is the bug reference #3522.
