### ISSUE TITLE
Adding root signature to shader binary fails

### ISSUE THREAD

**Issue by MehdiNS** [microsoft/DirectXShaderCompiler#2551]
Hello,

I'm trying to add a root signature inside a shader binary. 

What I do : 
- call Load() to load my shader inside a container
- call AddPart(FOURCC_RTS0, rootSignatureBlob)
- call SerializeContainer(&result) to reconstruct the shader

Problem : a `hlsl::Exception` exception is raised when I serialize the container.

In CompilerTest.cpp, I saw a test for root signature removal, but not for root signature addition. Could it be that this feature doesn't work?

Cheers,
Mehdi

**Comment by tex3d** [comment]
Exceptions should not leak out of the API.  The API should return a result interface with an error status and possible error messages, unless there's a more serious error, in which case it should return an error HRESULT directly, such as for E_OUTOFMEMORY or E_INVALIDARG.

Are you running under a debugger with the option to break on exceptions, even when they may be handled?

I updated the test you mentioned to add a root signature back to the container that does not have one, and see no problem in the basic functionality.

It's possible root signature validation is failing.  When you add a root signature to the container, it will be validated against the shader in that container, ensuring the root signature is usable for the shader.  The SerializeContainer call will fail (provide failure result with error buffer) if this validation fails.  Could this be what you're seeing?

**Comment by MehdiNS** [comment]
I tried to add a root signature back after removing it. I break on 2 or 3 exceptions inside `SerializeContainer`. As you said the callstack indicated something went wrong during validation. The first exception is raised inside a call to `DeserializedRootSignature`. When I continue, the HRESULT of the call to `SerializeContainer` is S_OK, but I checked the error buffer, and indeed I got a 'Validation fails'.

My shader is the same that the one I talked about in your test, a simple pixel shader with an empty root signature. Could it be the root signature I'm passing to `AddPart `does not have the right format? Right now, I pass a blob created from the following string "[RootSignature(\\"\\")]". Should I compile the root signature first?

**Comment by MehdiNS** [comment]
Update : I downloaded the version of dxc with your recent changes regarding root signature validation (https://github.com/microsoft/DirectXShaderCompiler/pull/2560). A mistake I made was I didn't know I should use GetDxilPartByType to retrieve the data of my root signature. But I still have some validation issues.

I made several tests : 
- As in the test you added recently, I remove the root signature from the binary and add it right back. Looking at the generated binary, the root signature is indeed the same before removal and after adding it back. Great.
- Remove the root signature, and add a root signature created from a string (`std::string rootSignatureSource = "#define pipelineRoot \"\"";`) When I try to compile this new root signature, the validation fails.
- Same thing, but disabling the validation with `-Vd` when compiling the root signature. I can see that the binary generated for the original root signature and the new one are not exactly the same. Is that a problem?

You'll find attached a minimal repro of my validation problems.
Ultimately, what I want to do is replace a root signature if a shader already has one, and just add a new root signature otherwise. How should I proceed?

[ReproRootSignaturePatching.zip](https://github.com/microsoft/DirectXShaderCompiler/files/3820616/ReproRootSignaturePatching.zip)

**Comment by tex3d** [comment]
My recent change for root signature validation (#2560) was the DxCompiler.dll side of a change going in to the next version of DXIL.dll as well.  There is a bug in the current DXIL.dll release that causes it to be unable to validate and sign a root signature by itself.  It can do this when attached to a shader, but will not validate and sign a blob that was compiled to a root signature target, such as `rootsig_1_0`.  This is why validation fails when compiling to rootsig_1_0 without /Vd when DXIL.dll is present.

As for the difference in root signatures between the one compiled with the shader and the one compiled separately, this is likely due to the root signature version, which defaults to `rootsig_1_1` for shaders unless you use the `-force_rootsig_ver` option when compiling the shader.  This isn't a problem, but `rootsig_1_1` allows for more descriptor optimization flexibility unless you supply a flag that disallows that.

If what you are doing is replacing a root signature in a shader with one compiled independently to a root signature target (like `rootsig_1_1`), you don't need validation of the root signature compilation, since it will validate it with the shader when you add it there.  So I would recommend for this scenario that you simply always supply the `-Vd` argument when compiling to `rootsig_1_*` for now.

**Comment by MehdiNS** [comment]
Thanks for the explanations! Did as you said and it works perfectly now.

**Comment by MehdiNS** [comment]
@tex3d Sorry, but I have to reopen the issue. I have another question related to my root signature patching issue

As of now, I have to use GetDxilPartByType to retrieve the data of the compiled root signature I want to inject in a shader. It creates a dependency on DxilContainer.h & its corresponding library LLVMDxilContainer.lib

Without going into details, I need to cut that dependency. Is there a way to achieve the same goal with just dxcapi.h? I saw some important changes were made in that header recently, but I couldn't find a replacement to GetDxilPartByType.

Thanks

**Comment by tex3d** [comment]
You should be able to use the `IDxcContainerReflection` interface and `FindFirstPartKind` with DXC_PART_ROOT_SIGNATURE to get the index to that part, then `GetPartContent` to get the root signature contents.  These are all defined in dxcapi.h.
