### ISSUE TITLE
Results of compute shader writes to groupshared structures change according to member types

### ISSUE THREAD

**Issue by MichelVachon** [microsoft/DirectXShaderCompiler#2553]
Considering a groupshared array size of 4: 
``` 
struct SLocalVertex {
    float3 position;
    int3 binormal; };
groupshared SLocalVertex localVertices[4];
```
With:
thread 0 writing indices 0 and 1
thread 1 writing indices 2 and 3 

With each thread setting:
localVertices[].position = float3( 1, 2, 3 );
localVertices[].binormal = 0;

The values stored for position yield:
1, 2, 3
1, 2, 3
0, 0, 3
2, 2, 3

If I change the type of position to float4, the stored values are ok with:
1, 2, 3
1, 2, 3
1, 2, 3
2, 2, 3

This happens with version 1.0.2481 when running vulkan with spirv.
It does not happen with dx12.
Optimisations are done with DXC and not with spirv-tools.
Turning optimisations off doesn't fix it.

Repro:

```
#if 1
struct SLocalVertex
{
    float3 position;	//with the issue
    int3 binormal;
};
#else
struct SLocalVertex
{
    float4 position;	//the workaround
    int3 binormal;
};
#endif

groupshared SLocalVertex localVertices[4];

[numthreads(2,1,1)]
void main( uint groupId : SV_GroupID, uint groupThreadId : SV_GroupThreadID )
{
    for ( ndU32 i = 0 ; i < 2 ; ++i )
    {
        localVertices[i+groupThreadId*2].position.xyz = float3( 1, 2, 3 );
        localVertices[i+groupThreadId*2].binormal = 0;
    }

    GroupMemoryBarrierWithGroupSync();
}
```

Thanks!

**Comment by tex3d** [comment]
_Side note:_ For a 1D flattened thread index, use SV_GroupIndex, not SV_GroupThreadID.  You're code is getting the 3D index and just reading the x component of that.  It is equivalent in this case, but future code readers might be misled by the type of the variable here.

It sounds like you saying that this is **not** a bug that occurs on dx12, correct?  If so, I'll tag the bug appropriately.  Then, you'll likely have to figure out whether this is in fact incorrect SPIR-V generated by the compiler, with a complete repro, or reach out to your hardware vendor otherwise.

**Comment by MichelVachon** [comment]
true, I took for granted that it was bad spirv.
Indeed the issue happens on nVidia and not AMD.
