### ISSUE TITLE
Questions about SM 6.1..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#256]
Hi,
just seen commits with new shader model 6.1 features..
Hope more news will be shared @Build 2017 conference next month but just posting basic questions in case you can answer now:
*Will require new a Windows update or will be supported on Creators update via new drivers from IHVs?
thanks..
*Are all SM6.1 features already exposed on commits (viewid,barycentrics) or still more instructions will be added?

thanks..

**Comment by marcelolr** [comment]
ViewID and barycentrics are everything we have planned for the 6.1 update. We have more things in the backlog that will likely roll into a 6.2 shader model, but this should keep IHVs busy for a while and enable some cool things.

Our current model is that new capabilities go hand-in-hand with driver updates, runtime updates and debug layer updates, so these roll into a Windows release incrementally, without back-patching prior systems. So no, Creators Update won't run these.

There are more things we'll be doing at the language level (note there's an option for HLSL 2017 that doesn't really change anything at the moment), but because these won't be affecting the generated DXIL, they can be updated independently of the operating system and drivers.

**Comment by unit-a-user** [comment]
Please, reopen this or some issue for `VK_KHR_fragment_shader_barycentric` extension (Vulkan 1.3.215).
