### ISSUE TITLE
[SPIRV] Matrices unoptimized code

### ISSUE THREAD

**Issue by Vincent-P** [microsoft/DirectXShaderCompiler#2598]
Hi, I am having huge performance drop because of the following unoptimized code:

HLSL
```hlsl
struct PSInput
{
    float4 color : COLOR;
};

cbuffer bob
{
    float4x3 matrices[3];  
};

struct compute_params
{
    uint index;
    float4x3 input_matrices[3];  
};

inline float3 compute_result(float4x3 input_matrices[3], uint index)
{
    return input_matrices[index][0];
}

float4 main(PSInput input) : SV_TARGET
{
    float4 result = input.color;
    
    compute_params p;
    for (uint i = 0; i < 3; i++) {
        p.input_matrices[i] = matrices[i];
    }
    p.index = 0;
    
    result.xyz += compute_result(p.input_matrices, p.index);
    return result;
}
```

GLSL generated from the spirv:
```glsl
#version 450

layout(binding = 0, std140) uniform type_bob
{
    layout(row_major) mat4x3 matrices[3];
} bob;

layout(location = 0) in vec4 in_var_COLOR;
layout(location = 0) out vec4 out_var_SV_TARGET;

void main()
{
    mat4x3 _30[3];
    for (uint _33 = 0u; _33 < 3u; )
    {
        _30[_33] = bob.matrices[_33];
        _33++;
        continue;
    }
    mat4x3 _29[3] = _30;
    vec3 _45 = in_var_COLOR.xyz + _29[0u][0u];
    out_var_SV_TARGET = vec4(_45.x, _45.y, _45.z, in_var_COLOR.w);
}
```

This copy `mat4x3 _29[3] = _30;` makes the performance drops significantly with my setup (RTX2070, drivers are 441.20). When editing the SPIRV in RenderDoc to use directly the `_30` matrice, the performance is similar to the generated DXBC from fxc.
For reference, the duration in RenderDoc for the draw using this shader is ~1300μs with the copy and ~75μs without.

Note that there is no copy if:
- the function return `return input_matrices[0][0];` instead of `return input_matrices[index][0];`
- the loop `p.input_matrices[i] = matrices[i];` is just replace by `p.input_matrices = matrices;`

It may be related to #2401 but Im not sure.

**Comment by ehsannas** [comment]
Thanks for reporting @Vincent-P .

**Comment by ehsannas** [comment]
I'm curious: how are you measuring the performance? 
Are you running HLSL->DXC->SPIRV->GPU?
or are you doing HLSL->DXC->SPIRV->(SPIRV-Cross??)->GLSL->(glslang??)->SPIRV->GPU?

(I mean, I'm not sure why we're looking at the GLSL code here)

**Comment by ehsannas** [comment]
A few notes:
- This does look similar to #2401, but it's not the same issue. (#2401 is modifying matrix rows using `OpCompositeInsert`, whereas here we are dealing with copying whole matrices using `OpLoad` and `OpStore`).
- Flows involving several tools/compilers could result in sub-optimal results
- I inspected the current SPIR-V generated by DXC for the HLSL shader, and it looks good to me. **_if_** there is any way to make things more optimized, it'll have to be in SPIRV-Tools optimizer.
- The HLSL code **_is in fact making a copy_** of an array of matrices to a local function scope. The optimizer can only eliminate that copy if it can statically guarantee functional equivalence.

>there is no copy if: the function return return input_matrices[0][0]; instead of return input_matrices[index][0];

_I think_ this is because the optimizer can now inline `compute_result` function into `p.input_matrices[0]`. Hence `input_matrices[1]` and `input_matrices[2]` are not used at all. and are eliminated by the optimizer. The loop then becomes a single assignment which can be simplified to an "alias". So it could theoretically use `matrices[0]`. _Maybe_ the optimizer could be smarter and figure out p.index is always 0...


>there is no copy if p.input_matrices = matrices; is used

_I think_ this is because we'd no longer be modifying each element of the matrix array, and `p.input_matrices` becomes an alias for `matrices`. (It is difficult to guarantee equivalence when you have a loop. For example, imagine if `p.input_matrices` was an array of size 5, and `matrices` was an array of size 3).

**Comment by Vincent-P** [comment]
The GLSL here was just to show that a copy happen in the SPIRV generated from DXC, I find it easier to read GLSL than SPIRV.
The duration of the draw call was from RenderDoc.
