### ISSUE TITLE
Regression in culling of called functions based on constant bools

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#2607]
In our shader system we use a lot of constant bools (i.e. `bool` variables set to literal values, via code gen), and are quite reliant on the compiler being good at stripping things that are known to be unused based on the value of those bools. We recently found a regression in this area, that caused one of our related unit tests to fail.

Specifically, the compiler no longer seems able to strip away calls to external functions (in a lib target) when that call is predicated on a constant bool variable. Strangely, it _is_ still able to strip reads from resources in the same situation, and it is also still able to strip the call when the bool variable is replaced with an inline literal. It's only the specific combination of a function call and a bool variable.

Hopefully an example/repro case will make this clearer. Compile the following with `lib_6_3` target and  `-exports func` as arguments.

```
float otherFunc();

float func()
{
	bool b = false;
	return b ? otherFunc() : 0;
}
```

This produces the following dxil:

```
define float @"\01?func@@YAMXZ"() #0 {
  %1 = call float @"\01?otherFunc@@YAMXZ"() #2
  ret float 0.000000e+00
}
```

Note the call to `otherFunc` is still present, despite being obviously not actually called. If you replace `b` in the return statement with `false`, the function call goes away.

I'm afraid I don't know exactly when this broke, but I know it was working correctly (i.e. no call to otherFunc) in commit 7eceecf0.

**Comment by tex3d** [comment]
The ternary operator and Boolean expressions do not short-circuit in HLSL, unlike C/C++.  This can be confusing, but it's to designed to map directly to vector select operations without adding potentially costly flow control.  Consider the vector form:

```
float4 fnA();
float4 fnB();
bool4 b4 = ..;
return b4 ? fnA() : fnB();
```

Both `fnA` and `fnB` are invoked and their results are mixed into the resulting vector based on each bool component of `b4`.  Supporting short-circuiting when possible here could lead to unexpected side effects or special cases when compared with this behavior.  There may have been a bug fixed here at some point to prevent inconsistent behavior in HLSL with this operator.

If you have a similar shader in fxc, where the function has a side effect, you'll see that the side effect is unconditionally performed before the constant value is returned.  Therefore the behavior is in keeping with HLSL language and fxc compatibility.

If you want constant branching behavior, use `if`/`else` instead of the ternary operator, and don't expect Boolean expressions to short-circuit either for the same reason (like: `(fnA() || fnB())` - both will be called and results selected on a per-component basis for consistency with vector form).
