### ISSUE TITLE
Building - prerequisites & versions mismatches

### ISSUE THREAD

**Issue by RayDobe** [microsoft/DirectXShaderCompiler#2616]
The build instructions miss mentioning Cmake as a prerequisite. Also, no versions are discussed, so I installed the latest Cmake and python. 
- If you run hctbuild for vs2017, it informs you only CMake 3.4.3, 3.7.2, 3.9.0 or 3.11.2 versions of Cmake are supported, the latest of which is 3.11.2. However, if you hit any errors, it then says only 3.4.3 is supported. Installing that provides another level of issues: 
- Cmake 3.11.2 is unaware of the latest python version, 3.8.
- Cmake 3.11.2 can't find python 3.7 as FindePythonInterp assumes Python installers set registry keys in `HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\`. At least Python 3.7 and 3.8 don't.
I dodged around this by moving to latest Cmake, and in CMakeLists.txt, changing `find_package(PythonInterp 3 REQUIRED)` to `find_package(Python3 REQUIRED)`

Also hctgettaef.py failed, as urllib.request is no longer supported. To get around that, changed the import from `import urllib.request` to `import urllib` and the urlopen from `response = urllib.request.urlopen(url, context=ctx)` to `response = urllib.urlopen(url, context=ctx)`

That got me building up to the point where hlsl.bin fails due to
`F:\Repos\hlsl.bin\utils\version\version.inc(12): error RC2237: numeric value expected at () [F:\Repos\hlsl.bin\tools\clang\utils\TableGen\clang-tblgen.vcxproj]

F:\Repos\hlsl.bin\utils\version\version.inc(12): error RC1013: mismatched parentheses [F:\Repos\hlsl.bin\tools\clang\utils\TableGen\clang-tblgen.vcxproj]

F:\Repos\hlsl.bin\utils\version\version.inc(12): error RC2135: file not found: () [F:\Repos\hlsl.bin\tools\clang\utils\TableGen\clang-tblgen.vcxproj]`

Haven't looked to see what needs to happen there yet. Anyhow, suffice it to say the build process is not smooth following the current instructions, and some light changes are needed to work with current tools.

**Comment by llvm-beanz** [comment]
A lot has changed since this issue was filed, but there was still room for improvement. I posted a PR to raise DXC's requirements to 3.17.2, which matches the SPIRV-Tools requirement. This makes DXC's minimum required version equal to the highest minimum required version of any of its dependencies (which seems sane).

In terms of the Python and resource compiler issues commented in this issue I haven't encountered or been able to reproduce them. If you're still encountering issues building DXC with CMake 3.17.2 or later, please comment on this issue, otherwise we will close this issue in conjunction with the version update and doc change.

**Comment by RayDobe** [comment]
Thanks for doing the updates! In the intervening years I've moved on to other things, so I'll assume all is good with the version update and doc change and close the issue.
