### ISSUE TITLE
[SPIRV] Invalid spir-v generated for loop

### ISSUE THREAD

**Issue by tbroph** [microsoft/DirectXShaderCompiler#2625]
DXC is failing to generate valid SPIR-V when running on the following (minimal reproduction from our actual use case):

```
bool TestFunction( )
{

    uint bits = 0;

    for( uint i = 0; i < 8; i ++ )
    {
        bits |= 1 << i;
    }

    if ( bits == 0xFF )
    	return false;

    return true;
} 

RWByteAddressBuffer counterBuffer;

[ numthreads ( 32 , 1 , 1 ) ]
void main ( uint groupIndex : SV_GroupID , uint localThreadID : SV_GroupIndex )
{

    uint valueA = 0xFF;
    uint valueB = 0x00;

    if ( TestFunction ( ) )
        valueA = 0;

    uint bitcount = countbits ( valueA );

    counterBuffer . InterlockedAdd ( 0, bitcount, valueB );
}
```

Command line options: 

> -Zi -WX -spirv -Zpc -fvk-use-dx-layout -fvk-use-dx-position-w -T cs_6_0 -E main

Output:

> fatal error: generated SPIR-V is invalid: OpLoopMerge must immediately precede either an OpBranch or OpBranchConditional instruction. OpLoopMerge must be the second-to-last instruction in its block.
>   OpLoopMerge %24 %25 None

**Comment by ehsannas** [comment]
Thanks for reporting @tbroph . This might be related to the debug info generation (e.g. OpLine) which is enabled by `-Zi`.

**Comment by jaebaek** [comment]
Thank you for reporting this issue. I believe that this is an issue of spirv-opt because it works fine when I added `-fcgl` argument at the end of your command line arguments.

I will open an issue in [SPIRV Tools repo](https://github.com/KhronosGroup/SPIRV-Tools) and add a pass to handle OpLine.
I will let you know after discussing this issue with SPIRV Tools folks.
