### ISSUE TITLE
[SPIRV] Shaders using [[vk::push_constant]] fail validation

### ISSUE THREAD

**Issue by DrGr4f1x** [microsoft/DirectXShaderCompiler#2630]
DXC appears to assign a descriptor set/slot in SPIR-V to constants tagged with [[vk::push_constant]], but push constants should not need a descriptor.  Validation fails with the following error, if the pipeline layout does not have a descriptor for the push constants:

ERROR: [Validation] Code 0 :  [ UNASSIGNED-CoreValidation-Shader-MissingDescriptor ] Object: VK_NULL_HANDLE (Type = 0) | Shader uses descriptor slot 0.1 (expected `VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT`) but not declared in pipeline layout

Here is a shader that repros the issue:

struct VSInput
{
	float3 position : POSITION;
	float3 normal : NORMAL;
	float3 color : COLOR;
};

#define LIGHT_COUNT 6

struct VSOutput
{
	float4 position : SV_Position;
	float3 normal : NORMAL;
	float3 color : COLOR;
	float4 lightVec[LIGHT_COUNT] : TEXCOORD0;
};

cbuffer VSConstants
{
	float4x4 projectionMatrix;
	float4x4 modelMatrix;
	float4 lightDir[LIGHT_COUNT];
};

struct LightStruct
{
	float4 lightPos[LIGHT_COUNT];
};

[[vk::push_constant]]
LightStruct lights;

VSOutput main(VSInput input)
{
	VSOutput output = (VSOutput)0;

	output.normal = input.normal;
	output.color = input.color;

	float4x4 modelToProjection = mul(projectionMatrix, modelMatrix);
	output.position = mul(modelToProjection, float4(input.position, 1.0f));

	for (int i = 0; i < LIGHT_COUNT; ++i)
	{
		output.lightVec[i].xyz = lights.lightPos[i].xyz - input.position.xyz;
		output.lightVec[i].w = lights.lightPos[i].w;
	}

	return output;
}

**Comment by ehsannas** [comment]
Thanks for reporting @DrGr4f1x

**Comment by jaebaek** [comment]
Hi @DrGr4f1x , it seems that your code uses `cbuffer VSConstants` which needs a descriptor set and a binding, but `[[vk::push_constant]] LightStruct lights;` does not need a descriptor set and a binding.
If you remove the `cbuffer VSConstants`, it does not report a Vulkan validation error when I do not provide any descriptor set and binding.

I quickly tested the following code and confirmed that it works fine without a descriptor set and a binding:
```
struct VSInput
{
  float4 position : POSITION;
  float4 color : COLOR;
};

#define LIGHT_COUNT 6

struct VSOutput
{
  float4 position : SV_Position;
  float4 color : COLOR;
};

struct LightStruct
{
  float4 lightPos;
};

[[vk::push_constant]]
LightStruct lights;

VSOutput main(VSInput input)
{
  VSOutput output = (VSOutput)0;

  output.color = input.color;
  output.position = input.position + lights.lightPos;

  return output;
}
```

I also checked disassembled SPIR-V code for your code and my code. Both have correct compilation results. If it has a validation error, it is not a compiler issue because our compiler correctly generates SPIR-V code.

If you still have this bug, please doublecheck that your DXC is the top of tree.

**Comment by DrGr4f1x** [comment]
That's not really a solution (and yes I'm at or very near head on my DXC version).  Removing the cbuffer changes the shader behavior (completely breaks it).  There is no restriction on using push constants and cbuffers (uniform buffers) in a single shader in GLSL/SPIR-V that I'm aware of.  My example shader was directly transliterated from Sascha Willem's equivalent shader in his push constants example.  That shader, which has a uniform buffer and push constant block, compiles correctly with GLSLC, without validation errors, and works identically to my shader.  DXC has a bug in this area.

**Comment by jaebaek** [comment]
I executed the Sascha Willem's example, but the error message is not related to push constant.
```
$ export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation

$ ./bin/pushconstants 
UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch(ERROR / SPEC): msgNum: 0 - Type mismatch on location 2.0: 'ptr to output arr[6] of vec4 of float32' vs 'ptr to input vec3 of float32'
    Objects: 1
       [0] 0x33, type: 15, name: (null)
Validation(ERROR): msg_code: 0:  [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object: 0x33 (Type = 15) | Type mismatch on location 2.0: 'ptr to output arr[6] of vec4 of float32' vs 'ptr to input vec3 of float32'
UNASSIGNED-CoreValidation-Shader-InputNotProduced(ERROR / SPEC): msgNum: 0 - fragment shader consumes input location 8.0 which is not written by vertex shader
    Objects: 1
       [0] 0x34, type: 15, name: (null)
Validation(ERROR): msg_code: 0:  [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object: 0x34 (Type = 15) | fragment shader consumes input location 8.0 which is not written by vertex shader
```

The error message pointed that the output of HLSL shader you wrote does not match with the input of GLSL fragment shader of [Sascha Willem's shader](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/pushconstants).

First of all, I cannot find any issue of push constant in the HLSL shader.
In addition, your HLSL shader is different from [Sascha Willem's GLSL shader](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/pushconstants) even though they look similar.

Please check the assembled SPIR-V code.
DXC interprets your HLSL shader uses **4 locations for output** while glslang understands the Sascha Willem's GLSL shader uses **3 locations for output** because glslang considers `vec4 gl_Position` as a builtin position (not consume any location for it).
On the other hand, DXC consumes 1 location for `float4 position : SV_Position;`.

I think this is not an issue, but just a difference between DXC and glslang.
As far as the interface between vertex shader output and pixel shader input which is generated by DXC has a common agreement, this looks fine.

**Comment by jaebaek** [comment]
@DrGr4f1x Based on my investigation and given information, I have no idea what is the exact problem you pointed. Please give me the exact error message, pixel shader you tested, the Vulkan application if you changed the Sascha Willem's example.
