### ISSUE TITLE
Runtime loading dxcompiler on mac/linux

### ISSUE THREAD

**Issue by rellensb** [microsoft/DirectXShaderCompiler#2680]
Hi, I'm wondering if there's currently a supported way to dlopen dxcompiler on mac/linux without linking against the lib. There doesn't seem to be a way to grab the REFIID for types without having access to the static `Interface::Interface_ID` symbol which will be name mangled.

Would adding an exported C function that can do a lookup be a viable option, or is there some existing workaround that I've missed?

**Comment by pow2clk** [comment]
I looked into some aspects of this over a year ago at this point. I'm afraid I don't remember terribly many details. I can tell you that the way dxc is linked for Linux and MacOS is rather fragile in part due to these GUIDs. There may be another way to generate them that makes this possible. I think @ehsannas  (when he gets back from leave) and/or @jaebaek are probably the ones to ask about it at this point. 

Worth noting, during my investigation, I was solely considering how better to link the dxc compiler. Loading the dxcompiler library directly might evade some of these problems. There are some allocators that get need to get initialized that were occasionally missed as well.

**Comment by jkunstwald** [comment]
@rellensb If you don't mind, how are you linking against dxc on linux in the first place? I can't seem to be able to resolve the references to `IDXcLibrary::IDxcLibrary_ID` and `IDXcCompiler::IDxcCompiler_ID`. Im linking against `libdxcompiler.so.3.7` and `libdxclib.a`.

**Comment by rellensb** [comment]
@pow2clk thanks for the reply. I've patched in a string lookup locally which seems to be working ok, but it'd be good to work out an upstream solution if possible.

@jkunstwald in terms of compile time linking? Nothing special, just regular linking against the .so (eg. assuming gcc: `-Lpath/to/library -ldxcompiler` ). It might be because the symbols are actually missing from your built library (you can check with `nm -DC libdxcompiler.so.3.7`). From looking at `WinAdapter.h` I think UUID emulation is disabled when building with clang on Linux.

**Comment by jkunstwald** [comment]
@rellensb Thank you! Forcing `__EMULATE_UUID` on clang did the trick.

**Comment by rellensb** [comment]
@ehsannas @jaebaek any thoughts on this?

**Comment by ehsannas** [comment]
Hey @rellensb ! Sorry for the delay. I was on leave for a while. Were you able to use dlopen without linking the lib? If you were able to get it working with some code changes, please feel free to make a pull-request. Your contributions would be much appreciated.  I currently don't have the bandwidth to do this work.

(side note: There has been some improvement in the generation of UUIDs (https://github.com/microsoft/DirectXShaderCompiler/pull/2796))

**Comment by MarijnS95** [comment]
@ehsannas I'm particularly interested in a method that retains compatibility with external FFI wrappers (from other languages) that dlopen the library and rely on passing a full UUID (which, afaik, is the intended usecase). While #2796 gives a consistent hash those wrappers need changes to pass the hash instead of pointer to UUID when running on a Linux platforms. As it stands the virtual interfaces are incompatible too.

After locally playing with this for some time, here are my thoughts:

- These UUIDs should be truly cross-platform and accept a proper 128-bit GUID wherever they are used;
- They should be easy to define, without requiring macros for definition and declaration in separate places;
- The UUID is preferably only written down exactly once.

Then, the nitty-gritty details on how I came to the final implementation adhering to those rules:

The existing macros are updated to take a rewritten variant of the GUID. These are returned as `REFIID` from `uuidof()` and that pretty much completes the solution, but requires the GUID to be specified twice, in odd formats. Returning a `REFIID` requires a `static` variable which can not be defined in-class:

```
error: ‘constexpr’ needed for in-class initialization of static data member ‘const IID IUnknown::_IID’ of non-integral type
```

Unfortunately `static inline constexpr` is a C++17 feature which I would [have used](https://github.com/MarijnS95/DirectXShaderCompiler/commit/a9fbd7fa3b44e6fce1e897a4c165df1adc98af61) to define IIDs inline without having a definition outside the header with the GUID. As a workaround a static local variable can be [used inside `uuidof()`](https://github.com/MarijnS95/DirectXShaderCompiler/commit/431e0457827236d50cd05052a7eb7e62786b0a5b).

Yet this relies on specifying the UUID twice - in different formats - which is not ideal. Fortunately some macro magic allows a struct header [to be created](https://github.com/MarijnS95/DirectXShaderCompiler/commit/021a980149649ba42e2181b4480d75481965f44b) that generates the `__declspec(uuid(...))` or `static const IID _IID = {...};` based on the platform.
I remember seeing a suggestion to use a trait type with template specializations that contains these IIDs, but cannot find it in this issue chain anymore to link back to. This is used in the [final revision](https://github.com/MarijnS95/DirectXShaderCompiler/commit/89a7b282a9a7891aa99de3039ca921a4738f7688) with the advantage that inherited types do not need to be passed through the macro, because it doesn't emit the opening brace `{` to contain the members anymore.
The disadvantage is that uuids can no longer be retrieved through `.uuidof()`. or `::uuidof()`. Meaning the following, if this usecase even exists/is allowed by `__uuidof()` on Windows, will no longer be supported:

```cpp
struct Custom : public IUnknown {
	// ...
};
//...
auto unknown_uuid = __uuidof(Custom);
// Error: No template specialization for TinterfaceIids<Custom>
```

Note I have yet to (build)test this on Windows and run the tests, as well as autoformat changed code.

Looking forward to your thoughts and suggestions!

**Comment by ehsannas** [comment]
Hi @MarijnS95 
Thanks for putting in the time for the code and for the explanations. 

Do I understand correctly that usages of `__uuidof(...)` would not work? There are many usages of this in the repository ([example](https://github.com/microsoft/DirectXShaderCompiler/blob/355c4fb6a313a402ec108a0742073abb7e8f00ac/lib/Support/MSFileSystemBasic.cpp#L1186)).

**Comment by MarijnS95** [comment]
Hi @ehsannas: All instances of `__uuidof(...)` in dxc work just fine, otherwise I wouldn't be able to compile and use this daily :wink: 

The issue lies specifically in the use of subclasses that themselves don't carry an IID. I don't know how common (if at all) this case is. See the code example given in my comment.

**Comment by ehsannas** [comment]
Oh I see. Let me take a closer look at this later this week. Thanks

**Comment by ehsannas** [comment]
@MarijnS95 Sorry for the delay. What you have done looks reasonable to me. Would you please post a pull-request? We can add any improvement suggestions there. Thanks!

**Comment by MarijnS95** [comment]
@ehsannas took me some time as well to set up the PR, you can find it here now: https://github.com/microsoft/DirectXShaderCompiler/pull/3062

As for the vtable issue, the problem is `virtual ~IUnknown();` generating a complete object destructor and deleting destructor:

<details>
<summary>VTable in GDB</summary>

```
(gdb) info vtbl this->m_Library
vtable for 'DxcLibrary' @ 0x7ffff7cbc5f8 (subobject @ 0x5555556bb9e0):
[0]: 0x7ffff6a56d40 <DxcLibrary::QueryInterface(_GUID const&, void**)>
[1]: 0x7ffff6a56d20 <DxcLibrary::AddRef()>
[2]: 0x7ffff6a56d30 <DxcLibrary::Release()>
[3]: 0x7ffff6b36bc0 <IUnknown::~IUnknown()>
[4]: 0x7ffff6a57130 <DxcLibrary::~DxcLibrary()>
[5]: 0x7ffff6a56d50 <DxcLibrary::SetMalloc(IMalloc*)>
[6]: 0x7ffff6a56d60 <DxcLibrary::CreateBlobFromBlob(IDxcBlob*, unsigned int, unsigned int, IDxcBlob**)>
[7]: 0x7ffff6a56d70 <DxcLibrary::CreateBlobFromFile(wchar_t const*, unsigned int*, IDxcBlobEncoding**)>
[8]: 0x7ffff6a56d80 <DxcLibrary::CreateBlobWithEncodingFromPinned(void const*, unsigned int, unsigned int, IDxcBlobEncoding**)>
[9]: 0x7ffff6a56d90 <DxcLibrary::CreateBlobWithEncodingOnHeapCopy(void const*, unsigned int, unsigned int, IDxcBlobEncoding**)>
[10]: 0x7ffff6a56da0 <DxcLibrary::CreateBlobWithEncodingOnMalloc(void const*, IMalloc*, unsigned int, unsigned int, IDxcBlobEncoding**)>
[11]: 0x7ffff6a56db0 <DxcLibrary::CreateIncludeHandler(IDxcIncludeHandler**)>
[12]: 0x7ffff6a56dc0 <DxcLibrary::CreateStreamFromBlobReadOnly(IDxcBlob*, IStream**)>
[13]: 0x7ffff6a56dd0 <DxcLibrary::GetBlobAsUtf8(IDxcBlob*, IDxcBlobEncoding**)>
[14]: 0x7ffff6a56e90 <DxcLibrary::GetBlobAsUtf16(IDxcBlob*, IDxcBlobEncoding**)>
```

</details>

This breaks vtable layout and requires external wrappers (in a different language, not compiled with dxc headers) to insert extra padding, as we do in our Rust wrapper [here](https://github.com/Traverse-Research/hassle-rs/pull/5/commits/c37cb037be072cac43f2706b89f1388b9deee19a#diff-00940abedebd90a33a1ced7d43a96f0aR38-R39).

The destructors are actively used in `IUnknown::Release()` though I doubt objects should be freed that way seeing most implementation instances are created and freed using `DXC_MICROCOM_TM_{ALLOC,ADDREF_RELEASE_IMPL}` except the few in `WinAdapter`.

Perhaps the destructor can be removed or replaced with a nonvirtual one (with the resulting warning disabled) that is directly called, followed by an explicit free?

**Comment by rellensb** [comment]
Thanks for pushing this forward everyone!
