### ISSUE TITLE
[SPIRV] Expected int scalar or vector type as Result Type: SNegate

### ISSUE THREAD

**Issue by tomspilman** [microsoft/DirectXShaderCompiler#2688]
Got an error from DXC:

```
fatal error: generated SPIR-V is invalid: Expected int scalar or vector type as Result Type: SNegate
  %251 = OpSNegate %mat3v3float %250

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

The problem code is this...
```
float3x3 lightDirections = xxx;
float3 worldNormal = xxx;
float3 dotL = mul(-lightDirections, worldNormal);
```

Also note when optimizations are turned on i would get not error message... just a `-2147467259` return code.  I had to add `-Od` to get it to show the error message.

**Comment by sudonatalie** [comment]
Sorry for the lack of response on this issue!

Given the following minimal shader based on the problem code mentioned above:

```
float3 main(float4 pos: SV_Position) : SV_Target {
    float3x3 mat = {pos.xyz, pos.xyz, pos.xyz,};
    float3 vec = {pos.x, pos.y, pos.z};
    return mul(-mat, vec);
}
```

I was not able to reproduce the error. The above shader compiles successfully with:
* `-T ps_6_0 -E main -spirv`, and
* `-T ps_6_0 -E main -spirv -Od`

I'll assume that the issue has since been fixed, however if you have a full repro shader that still produces this error, please comment and re-open so we can reinvestigate.
