### ISSUE TITLE
Missing validation of integer offsets for Gather

### ISSUE THREAD

**Issue by AdamJMiles** [microsoft/DirectXShaderCompiler#2713]
Hi,

I think FXC and DXC are both missing validation against using non-literal offsets and also offsets that are literal but outside the required range of -8 to +7. The D3D11.3 spec* confirms these restrictions on Sample and Load operations but makes no mention of them existing on Gather.

However, based on the way GCN hardware appears to pack its offsets (into no more than a byte each) there’s no way they can support offsets of more than about -128 - +127 (and in practice it seems to be somewhere around -64 to +63.

[Shader](http://shader-playground.timjones.io/05cef670521469e423bb10db6599f0c4)

main3 (Sample with big offsets) and main4 (Sample with offsets that aren’t compile time literals) give this error and I believe main and main2 probably should too:

G:\gather.txt(7,12-39): error X4566: offset texture instructions must take offset which can resolve to integer literal in the range -8 to 7

The D3D11.3 spec may also want updating if this is an omission.

Thanks,

Adam

*
Address Offset
--------------
The optional [_aoffimmi(u,v,w)] suffix (address offset by
immediate integer) indicates that the texture coordinates for
the sample are to be offset by a set of provided immediate
texel space integer constant values. The literal values are a
set of 4 bit 2's complement numbers, having integer range
 [-8,7]. This modifier is defined for all Resources,
including Texture1D/2D Arrays and Texture3D,
but it is undefined for TextureCube.

**Comment by tex3d** [comment]
There are two types of offsets on Gather*(), the aoffimmi (affine offset immediate) that only supports range [-8..7] and must resolve to a constant, and the programmable offset version with four 2d offsets (one per sample).  Programmable offsets can be variable and are defined where:

> The 6 least significant bits of each offset value is honored as a signed value, yielding [-32..31] range.

DXBC has different operations for these cases: `gather4_aoffimmi` and `gather4_po`.

DXIL on the other hand only has one intrinsic form for both cases.  If the offset is not constant in [-8..7] range, it should be considered the gather4_po case.

This presents a challenge for validating that programmable offsets have been defined properly in HLSL.  In HLSL, you are allowed to have code that eventually resolves immediate offsets to constant values in range, but this may require optimization, and even loop unrolling to determine.  Since this is the case, our validation for these offsets would be very late, even at the very end, in the validator.  At this stage, we don't know if the offsets came from the immediate offset form or the programmable offset form in HLSL.

We could, through additional effort, track values that should be immediate through the pipeline (perhaps by passing through some special intermediate function), and in our DxilLegalizeSampleOffsetPass, we would remove the intermediate function and emit an error here if the values cannot be made constant.

Additional effort to determine this will not add a lot of value, however, since it will only enable an error message when the immediate offset form fails to resolve to immediate offsets, and must use programmable offsets instead.  If this produces a correct result, this doesn't seem like a very high priority issue to fix at the moment.

**Comment by tex3d** [comment]
Another solution is to introduce new dxil OpCodes to differentiate these (to be introduced in some future DXIL version).  They would be under the same OpClass and use same function signature.  I would suggest the new ones be the immediate offset ones, since the old ones can be converted to immediate offset ones if the offsets are compatible, otherwise they would remain the programmable version, requiring no change in the handling of the existing op codes for the driver.  The lowering code could generate the new immediate versions from the appropriate HLSL intrinsics, which would force them to resolve to the expected constants or fail in DxilLegalizeSampleOffsetPass.  Down-conversion for lower shader models would then just map the new op codes to the old ones.

**Comment by pow2clk** [comment]
Just a note that, upon further reflection, we decided that the docs were wrong and the original implementation was right. #3764 has reverted the gather portion of #3283 and the docs have been updated. Gathers can now have variable offsets though the 6 LSB are all that is respected as described here: https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#inst_GATHER4_PO
