### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#2733]
I am getting
```
Cannot open include file: 'D3D12TokenizedProgramFormat.hpp': No such file or directory
```
used in `projects\dxilconv\lib\ShaderBinary\ShaderBinaryIncludes.h`

on my Windows OS. Do I need to install a certain Windows SDK before building? (this is a new issue. Hadn't seen it in the past)

**Comment by hekota** [comment]
You need to install Windows Driver Kit and matching Windows SDK version 10.0.18362.0. 

This is a new requirement since we added DXBC to DXIL converter to the project - the header contains DXBC format definitions. I was considering including the header in the repo but the Windows Driver Kit is good to have anyway because it has the TAEF framework for running tests. The script hctgettaef.py does not always work.

I will update the instructions.

**Comment by ehsannas** [comment]
Ah. Thanks for the explanation. Yeah it'd be great to add this requirement to the building instructions. Thanks!

**Comment by ehsannas** [comment]
Looks like updating my Visual Studio also fixed the issue (it probably updated my SDK/WDK version as a result)

**Comment by siliconvoodoo** [comment]
It didn't work for me to update VS2017. Nor install a WinSDK from MS website. It made the build progress further to install VS2019 though. (probably because it installs that precise 10.0.18362.0 version). But now fails on a bunch of 

> cannot open include file 'version.inc'
