### ISSUE TITLE
Question: How to report issues with FXC?

### ISSUE THREAD

**Issue by TLaviron** [microsoft/DirectXShaderCompiler#2791]
Hi, 

I believe I have encountered a bug in FXC, but I could not find where to submit an issue.

From the FAQ:
> Fxc will continue to be supported (bug fixes, etc) so you can continue to use it.

Can someone point me to the right place for a bug report?
Additionally, may I suggest adding this information in the FAQ?

**Comment by pow2clk** [comment]
Hi @TLaviron! 

Unfortunately, that FAQ was rather out of date. We have since moved away from fxc to a degree that text doesn't accurately represent. The text has been updated to represent our current protocol for fxc:

> fxc is no longer under active development. We are only fixing high priority bugs in fxc that we cannot offer a workaround for. Also note that fxc only ships as a component of the Windows SDK and we are unable to ship a fix outside of the Windows SDK release process. If you have a high priority fxc bug that you would like us to investigate, please mail askhlsl@microsoft.com.
>   fxc will not support shader models beyond the current v5.1, so new features will not be available via that path.
>   Fxc will also continue to generate the original DXBC byte code, not the LLVM-derived DXIL.

We will still fix critical issues, but it's a really high bar and a really low priority for us. 

We encourage everyone to port their shaders to DXC wherever possible. 

https://github.com/microsoft/DirectXShaderCompiler/wiki/Porting-shaders-from-FXC-to-DXC

Thanks for pointing out the out-of-date text!
