### ISSUE TITLE
Why force _ITERATOR_DEBUG_LEVEL=0?

### ISSUE THREAD

**Issue by gongminmin** [microsoft/DirectXShaderCompiler#2864]
In cmake/modules/AddLLVM.cmake, _ITERATOR_DEBUG_LEVEL is defined as 0, and so SPIRV-Tools have to build with _ITERATOR_DEBUG_LEVEL = 0. I tried to remove them and it doesn't seem to break things. What's the necessity of force _ITERATOR_DEBUG_LEVEL to 0?

**Comment by pow2clk** [comment]
I did a bit of digging into this while waiting for a compile to finish. The first indication of this was introduced in #529 where it was commented out, but included this explanation:
```  
# Disable debug iterators for faster debug and to remove some additional allocations with improper noexcept attribution.
# Currently commented out because SPIR-V libs compile their debug modules with debug iterators.
```

The code was enabled and the comments removed by #574. 

@ehsannas should probably make the decision whether that reasoning still applies.

**Comment by ehsannas** [comment]
IIRC:
I think Marcelo's original intent was to have `_ITERATOR_DEBUG_LEVEL=0` because:
> Disable debug iterators for faster debug and to remove some additional allocations with improper noexcept attribution

I **_think_** the same reasoning applies today. If not, I don't feel strongly about keeping the flag.

`_ITERATOR_DEBUG_LEVEL=0` was temporarily commented out (by #529) until we fixed the external dependency (spirv-tools) linking issues and we uncommented it (by #574). So in short, I don't think the reason for `_ITERATOR_DEBUG_LEVEL=0` is because of SPIRV-Tools. Rather, we added this flag to `external/CMakeLists.txt` because the flag was present in DXC and we couldn't link SPIRV-Tools to it otherwise.

**Comment by ehsannas** [comment]
@gongminmin does the build succeed and all the tests pass in both Release and Debug mode?

**Comment by gongminmin** [comment]
It build succeed for Release and Debug, and runs well for my project. I haven't run through CI. Let me try it.

**Comment by gongminmin** [comment]
Tried 4 combinations of x86 or x64, Debug or Release with VS2019, pass all builds and tests. I don't have other compiler installed, but I remember back in 2018, I had some issues if _ITERATOR_DEBUG_LEVEL=0 is removed. Not sure if it's a VS2017 problem or not.

**Comment by ehsannas** [comment]
Please post a PR. Thanks

**Comment by ehsannas** [comment]
This has been addressed.
