### ISSUE TITLE
[SPIRV] strategy to merge/deprecate Vulkan specific feature attribute

### ISSUE THREAD

**Issue by chaocNV** [microsoft/DirectXShaderCompiler#2967]
This was raised during discussion of a Vulkan specific feature attribute and I feel it warrants a separate issue.  
We currently have and will have more Vulkan specific feature attributes for Vulkan features that native language constructs of HLSL does not support. Yet HLSL is also an evolving language and it will start to have native support for those features.  So just as a general strategy discussion, what process(if any) should we have in place to monitor and merge/deprecate the Vulkan attributes and replace them with HLSL native when it becomes available?

**Comment by sudonatalie** [comment]
I think it's fair to say that our new approach with [inline SPIR-V](https://github.com/microsoft/hlsl-specs/pull/59) solves this problem well enough by focusing on supporting a general purpose set attributes for any SPIR-V builtin functions, types, etc. Since we're no longer adding feature-specific attributes to DXC, this attribute churn and maintenance burden should be significantly lessened.
