### ISSUE TITLE
License header has been rewritten on files

### ISSUE THREAD

**Issue by jrmuizel** [Microsoft/DirectXShaderCompiler#30]
For example:
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/utils/PerfectShuffle/PerfectShuffle.cpp

vs.

https://github.com/llvm-mirror/llvm/blob/master/utils/PerfectShuffle/PerfectShuffle.cpp

This seems like a violation of the original LLVM license.

**Comment by marcelolr** [comment]
On phone at the moment, so will be brief.

Notices are retained in the referenced COPYRIGHT file, along with additional information.

Can you provide additional details?

Thanks!


On Jan 23, 2017, at 6:43 PM, Jeff Muizelaar <notifications@github.com<mailto:notifications@github.com>> wrote:


For example:
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/utils/PerfectShuffle/PerfectShuffle.cpp

vs.

https://github.com/llvm-mirror/llvm/blob/master/utils/PerfectShuffle/PerfectShuffle.cpp

This seems like a violation of the original LLVM license.

-

**Comment by jrmuizel** [comment]
PerfectShuffle.cpp file in this repo is claiming "Copyright (C) Microsoft Corporation. All rights reserved." However, Microsoft does not own the copyright on these files and should not be claiming it.

**Comment by Sarkie** [comment]
They probably ran a script to add the copyright before releasing the source and accidentally overwrote the original ones.

**Comment by AgentDickSteele** [comment]
👮

**Comment by dberlin** [comment]
Hey Marcelo,

Speaking in my capacity as both an LLVM contributor and an IP lawyer licensed in a bunch of states:

These things happen, for sure (it'd be nice if they didn't, but ...)
Retaining the notices in a "COPYRIGHT" file is not enough in this situation.
You aren't allowed to change headers like you've done.
First, Microsoft does not own *any* copyright in these files (I checked, y'all have never contributed to pretty much any of them. There's one or two you might have an argument about).
Regardless, you definitely also can't claim it's MIT licensed, when it's definitely not.

Even if you ignore copyright infringement (which has been found in cases of header replacement, and *definitely* license replacement), DMCA has a separate provision about integrity of copyright management information (and companies have been found liable numerous times for stripping and replacing copyright notices)

My suggestion: Put the original headers back, be happy.
It'll also reduce your merge conflicts, etc.

There are likely alternatives (happy to put you in touch with the LLVM foundation, though I suspect they will contact you soon anyway), but i can pretty much guarantee you they don't include having "Copyright Microsoft" on these files, and claiming they are MIT licensed :)

Generally, it's good to resolve these things as fast as possible. There are already 9 forks, and I know nobody really wants incorrectly licensed LLVM source floating around, because it'll float around for a long time.
:(

**Comment by mlrdevgit** [comment]
Thanks for the info everyone. We'll get this sorted out ASAP.

**Comment by DrItanium** [comment]
The rewrite of the copyright has also caused what could be interpreted as Microsoft employees griping about their own operating system in utils/KillTheDoctor/KillTheDoctor.cpp

https://github.com/Microsoft/DirectXShaderCompiler/blob/master/utils/KillTheDoctor/KillTheDoctor.cpp#L28

**Comment by dberlin** [comment]
Thanks Marcelo,
Let me know if I can be of assistance in any way :)

**Comment by marcelolr** [comment]
This should be fixed in the master branch, we're following up with a fix to the v1 branch shortly. It's entirely possible that we've missed something, and we'll fix that as any such issues are found. Thanks again everyone for your input on this - we appreciate the support.
