### ISSUE TITLE
[SPIR-V] Incorrect array stride for StructuredBuffer<float3>

### ISSUE THREAD

**Issue by ch45er** [microsoft/DirectXShaderCompiler#3031]
SPIR-V codegen seems to be incorrectly decorating `StructuredBuffer<float3>` with array stride of 16 with no apparent reason, at least when compiling vertex shaders. Please see the example compiler output:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 29
; Schema: 0
               OpCapability Shader
               OpExtension "SPV_GOOGLE_hlsl_functionality1"
               OpExtension "SPV_GOOGLE_user_type"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %Main "Main" %gl_VertexIndex %gl_Position
          %4 = OpString "./Shaders/Demo_SimpleTriangleVS.hlsl"
               OpSource HLSL 600 %4 "#line 1 \"./Shaders/Demo_SimpleTriangleVS.hlsl\"
#line 16 \"./Shaders/Demo_SimpleTriangleVS.hlsl\"
StructuredBuffer<float3> Buf;

void Main(
 in uint uVertexIndex : SV_VertexID,
 out float4 vOutPos : SV_Position

 )
{


 vOutPos = float4(Buf[uVertexIndex], 1.0);


}
"
               OpName %type_StructuredBuffer_v3float "type.StructuredBuffer.v3float"
               OpName %Buf "Buf"
               OpName %Main "Main"
               OpDecorate %gl_VertexIndex BuiltIn VertexIndex
               OpDecorateString %gl_VertexIndex UserSemantic "SV_VertexID"
               OpDecorate %gl_Position BuiltIn Position
               OpDecorateString %gl_Position UserSemantic "SV_Position"
               OpDecorate %Buf DescriptorSet 0
               OpDecorate %Buf Binding 0
               OpDecorate %_runtimearr_v3float ArrayStride 16
               OpMemberDecorate %type_StructuredBuffer_v3float 0 Offset 0
               OpMemberDecorate %type_StructuredBuffer_v3float 0 NonWritable
               OpDecorate %type_StructuredBuffer_v3float BufferBlock
               OpDecorateString %Buf UserTypeGOOGLE "structuredbuffer"
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
      %float = OpTypeFloat 32
    %float_1 = OpConstant %float 1
    %v3float = OpTypeVector %float 3
%_runtimearr_v3float = OpTypeRuntimeArray %v3float
%type_StructuredBuffer_v3float = OpTypeStruct %_runtimearr_v3float
%_ptr_Uniform_type_StructuredBuffer_v3float = OpTypePointer Uniform %type_StructuredBuffer_v3float
       %uint = OpTypeInt 32 0
%_ptr_Input_uint = OpTypePointer Input %uint
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %void = OpTypeVoid
         %19 = OpTypeFunction %void
%_ptr_Uniform_v3float = OpTypePointer Uniform %v3float
               OpLine %4 16 26
        %Buf = OpVariable %_ptr_Uniform_type_StructuredBuffer_v3float Uniform
               OpLine %4 19 25
%gl_VertexIndex = OpVariable %_ptr_Input_uint Input
               OpLine %4 20 23
%gl_Position = OpVariable %_ptr_Output_v4float Output
               OpLine %4 18 1
       %Main = OpFunction %void None %19
         %21 = OpLabel
               OpLine %4 19 10
         %22 = OpLoad %uint %gl_VertexIndex
               OpLine %4 26 19
         %23 = OpAccessChain %_ptr_Uniform_v3float %Buf %int_0 %22
         %24 = OpLoad %v3float %23
         %25 = OpCompositeExtract %float %24 0
         %26 = OpCompositeExtract %float %24 1
         %27 = OpCompositeExtract %float %24 2
         %28 = OpCompositeConstruct %v4float %25 %26 %27 %float_1
               OpLine %4 20 23
               OpStore %gl_Position %28
               OpReturn
               OpFunctionEnd
```
Compiled with:
```
-E Main -T vs_6_0 \
-spirv -fspv-reflect -fspv-target-env=vulkan1.0 \
-fspv-flatten-resource-arrays \
-fspv-extension=SPV_GOOGLE_hlsl_functionality1 \
-fspv-extension=SPV_GOOGLE_user_type -Zpr -Zi
```
on master.

**Comment by brianwatling** [comment]
#2466 made the stride for StructuredBuffer be calculated as if the buffer is an array of the given type to fix #2408. We'll look into this further

**Comment by brianwatling** [comment]
The array stride becomes 12 if -fvk-use-dx-layout is specified on the command line - does that work for you?

**Comment by ch45er** [comment]
Shaders compiled with `-fvk-use-dx-layout` trigger the following error in vulkan validation layers:
```
SPIR-V module not valid: Structure id 24 decorated as BufferBlock for variable in Uniform storage class must follow standard storage buffer layout rules: member 0 contains an array with stride 12 not satisfying alignment to 16
  %type_StructuredBuffer_v3float = OpTypeStruct %_runtimearr_v3float
```
This looks quite similar to #2408.

**Comment by jaebaek** [comment]
Let's just ignore `-fvk-use-dx-layout` for now. Please give me more time to consider it.

See the Vulkan spec [14.5.4. Offset and Stride Assignment](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#interfaces-resources-layout).

"**Standard Buffer Layout**

Every member of an OpTypeStruct that is required to be explicitly laid out must be aligned according to the first matching rule as follows. If the struct is contained in pointer types of multiple storage classes, it must satisfy the requirements for every storage class used to reference it.

1. If the scalarBlockLayout feature is enabled on the device then every member must be aligned according to its scalar alignment.

2. All vectors must be aligned according to their scalar alignment.

3. If the uniformBufferStandardLayout feature is not enabled on the device, then any member of an OpTypeStruct with a storage class of Uniform and a decoration of Block must be aligned according to its extended alignment.

4. Every other member must be aligned according to its base alignment."


Based on the [memory layout rule options of DXC SPIR-V backend](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#memory-layout-rules),
`-fvk-use-scalar-layout` indicates "**scalarBlockLayout** feature is enabled on the device".

When you do not use `-fvk-use-scalar-layout`, it will follow the _base alignment_ rule of the Vulkan spec.
(Note that the _extended alignment_ rule will basically have the same result with the _base alignment_ rule for your code example because it only uses an array and a vector)

"
The base alignment of the type of an OpTypeStruct member is defined recursively as follows:
- A scalar has a base alignment equal to its scalar alignment.
- A two-component vector has a base alignment equal to twice its scalar alignment.
- **A three- or four-component vector has a base alignment equal to four times its scalar alignment.**
...
"

Since `float3` is a three-component vector, it must have the `4 * sizeof(float)` alignment.

"Any ArrayStride or MatrixStride decoration must be a multiple of the alignment of the array or matrix as defined above."

I believe `4 * sizeof(float) == 16` is the correct ArrayStride decoration for it.

**Comment by jaebaek** [comment]
In terms of `-fvk-use-dx-layout`, I am sorry for this answer but it is also the expected behavior.

Let me briefly explain the situation.

We have 4 layout options: default, `-fvk-use-gl-layout`, `-fvk-use-scalar-layout`, `-fvk-use-dx-layout`. (See the [DXC SPIR-V backend memory layout rule](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#memory-layout-rules)).
For the default, `-fvk-use-gl-layout`, and `-fvk-use-scalar-layout`, we follow [the Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#interfaces-resources-layout).

For `-fvk-use-dx-layout`, we mimic what DXIL backend (or DirectX) does. Since DirectX is different from Vulkan, definitely some layouts in SPIR-V following **DX** layout rule must be invalid in the view of Vulkan spec.

In terms of compiling your code with `-fvk-use-dx-layout`, even though DXC knows that it will be an invalid SPIR-V code, DXC has to generate it because the user gave `-fvk-use-dx-layout`option to DXC.
DXC just uses the DX layout, which is invalid in the view of Vulkan spec.

**Comment by ch45er** [comment]
Thank you very much for this detailed explanation!

So the compiler is correct, and that line "A three- or four-component vector has a base alignment equal to four times its scalar alignment." is what I've overlooked.

Just to summarize: if one needs to access elements of `StructuredBuffer<float3>` (and alike) in a way, that is both DirectX and Vulkan compatible, he has to compile with `-fvk-use-scalar-layout` which assumes `VK_EXT_scalar_block_layout` extension is supported by the hardware and enabled.

Otherwise the most portable ways seem to be either to pad to float4 (and alike) or switch to ByteAddressBuffer and fetch data manually.
