### ISSUE TITLE
half3x3 to float3x3 is causing DXC to crash due to stack overflow

### ISSUE THREAD

**Issue by iOrange** [microsoft/DirectXShaderCompiler#3041]
Hi!

The shader code below is crashing DXC due to stack overflow 

Same behaviour with XBox dxc compiler and latest version from Github.
Compiled using following command line _dxc -E main -T ps_6_0 test.hlsl_

It could be ill-formed code, but compiler should at least point to the error and no just silently crash.

PS. Same behaviour if using dxcompiler.dll  and IDxcCompiler3.

```c++
static const float sFoo = 1.5;

static const float3x3 sBar = half3x3
(
    sFoo,  0.0f,   -sFoo * 0.5f,
    0.0f,   sFoo,  -sFoo * 0.5f,
    0.0f,   0.0f,   1.0f
);

half4 main() : SV_Target
{
    half3 result = half3(0.0, 0.0, 0.0);
    return(float4(result, 0));
}
```

**Comment by vcsharma** [comment]
@iOrange Thanks for reporting this issue. This appears to be a valid scenario which should compile successfully. Below is the slightly shorter repro of this bug.

```
void main() {
const float1x1 sBar = half1x1(0);
}
```

```
ImplicitCastExpr 0x1f3407abf38 'matrix<float, 1, 1>' <HLSLCC_FloatingCast>
`-CXXFunctionalCastExpr 0x1f3407abf10 'half1x1':'matrix<half, 1, 1>' functional cast to half1x1 <NoOp>
  `-InitListExpr 0x1f3407abdb0 'half1x1':'matrix<half, 1, 1>'
    `-ImplicitCastExpr 0x1f3407abd98 'half' <IntegralToFloating>
      `-IntegerLiteral 0x1f3407abd70 'literal int' 0
```

The issue is that while trying to evaluate the above expression tree recursively, in  function `EmitConstantExpr`, the call to `EvaluateAsRValue` always returns `false` for `InitListExpr` as it doesn't seem to handle matrix type even though the underlying evaluation of constexpr happens successfully. This is why it keeps on recursing the same expression again and again in the below line which eventually causes stackoverflow.

`C = ConstExprEmitter(*this, CGF).Visit(const_cast<Expr*>(E));`
