### ISSUE TITLE
IDxcCursor API doesn't expose ConstantBuffer<> variables

### ISSUE THREAD

**Issue by vaspoul** [microsoft/DirectXShaderCompiler#3085]
(feature request) Can we get constant buffers in the new 'template' form exposed via IDxcCursor?

i.e. the following:

struct MaterialParams
{
	float4	albedo;
};

ConstantBuffer<MaterialParams>	materialParams;

materialParams is currently coming through as DxcCursor_UnexposedExpr.

The -ast-dump output does include it:

|-VarDecl 0x2cd45555a30 parent ConstantBuffer 0x2cd45555ae0 <line:9:16, col:32> col:32 materialParams 'const MaterialParams'

**Comment by llvm-beanz** [comment]
Hi @vaspoul, I'm sorry this issue has sat so long without comment. We're not actively developing the `IDxcCursor` interface. We're keeping it functioning until our LSP-based replacement is ready, but we're not investing resources in extending or improving the existing interface. We would consider pull requests to extend the exiting interfaces, but I don't want to leave this issue unresolved since we're not going to prioritize this.

Our LSP-based replacement will be `clangd`, and the issue for adding HLSL support to `clangd` is tracked here:
https://github.com/llvm/llvm-project/issues/58026.
