### ISSUE TITLE
[SPIR-V] sizeof() gets wrong value when used in a non-entry function

### ISSUE THREAD

**Issue by LLJJDD** [microsoft/DirectXShaderCompiler#3198]
The shader:
```
struct StructA
{
    float3 one;
    float3 two;
};

uint foo()
{
    return sizeof(StructA);
}

[numthreads(64, 1, 1)]
void main()
{
    uint a = foo();
    uint b = sizeof(StructA);
}
```

Using command: `dxc -spirv -E main -T cs_6_0 shader.hlsl -fcgl`

The result is:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 18
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 64 1 1
               OpSource HLSL 600
               OpName %main "main"
               OpName %src_main "src.main"
               OpName %bb_entry "bb.entry"
               OpName %a "a"
               OpName %b "b"
               OpName %foo "foo"
               OpName %bb_entry_0 "bb.entry"
       %uint = OpTypeInt 32 0
    %uint_24 = OpConstant %uint 24
    %uint_32 = OpConstant %uint 32
       %void = OpTypeVoid
          %6 = OpTypeFunction %void
%_ptr_Function_uint = OpTypePointer Function %uint
         %16 = OpTypeFunction %uint
       %main = OpFunction %void None %6
          %7 = OpLabel
          %8 = OpFunctionCall %void %src_main
               OpReturn
               OpFunctionEnd
   %src_main = OpFunction %void None %6
   %bb_entry = OpLabel
          %a = OpVariable %_ptr_Function_uint Function
          %b = OpVariable %_ptr_Function_uint Function
         %14 = OpFunctionCall %uint %foo
               OpStore %a %14
               OpStore %b %uint_24
               OpReturn
               OpFunctionEnd
        %foo = OpFunction %uint None %16
 %bb_entry_0 = OpLabel
               OpReturnValue %uint_32
               OpFunctionEnd
```

You can see that in `main()`, `sizeof(StructA)` calculates to 24, but in `foo()`, it is 32.

**Comment by LLJJDD** [comment]
Additional questions:
1. Which size is the correct one? Should there be padding in the structure?
2. When interacting with RWByteAddressBuffer, using a `RWByteAddressBuffer.store<StructA>` or `RWByteAddressBuffer.load<StructA>`, should there be padding between structure members?

**Comment by jaebaek** [comment]
Hi @LLJJDD, thank you for reporting this issue.
In terms of your questions,

1. In my opinion, it should be `24` because DXIL backend generates `24`: http://shader-playground.timjones.io/5a07735e693ec2d141d8b492539166c0

For this decision, we have to consider whether it aligns with the rule of Vulkan or not.
Since `sizeof(StructA)` is not coupled with any storage class (it is not an actual storage), I do not think Vulkan spec specifies anything for it. It seems that we have to follow what the HLSL means.

2. In terms of `RWByteAddressBuffer`, it does not have special memory layout. It is just an array with the array stride of 4 bytes.

Try
```
// Run: %dxc -T cs_6_2 -E main -fvk-use-dx-layout

RWByteAddressBuffer buf;

struct StructA
{
  float3 one;
  float3 two;
};

[numthreads(64, 1, 1)]
void main(uint3 tid : SV_DispatchThreadId) {
  StructA foo = buf.Load<StructA>(tid.x);
}
```

Since `RWByteAddressBuffer buf` is an array of `int`, it uses `OpCompositeConstruct` to construct `StructA foo`.

In terms of the memory layout of a variable with the type `StructA`, it depends what layout you use (see [Memory layout rules](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#memory-layout-rules)), but the default memory layout rule is [Vector-relaxed OpenGL std430](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#constanttexturestructuredbyte-buffers).

Note that a local variable does not have any memory layout. It should be determined by a driver.
(as far as I know, a local variable in shader does not have any memory layout, but the one in OpenCL C has an explicit memory layout. I am not 100% sure for it)

**Comment by jaebaek** [comment]
Let me know if I am wrong or if you have a different opinion.

**Comment by LLJJDD** [comment]
Thanks for the explanation, it basically matches my thoughts.

I will open a PR later to fix this issue.

**Comment by jaebaek** [comment]
Oh I already sent one. PTAL #3208
