### ISSUE TITLE
IDxcLinker : Allow to provide a different function name

### ISSUE THREAD

**Issue by mrvux** [microsoft/DirectXShaderCompiler#3238]
Hello, while using linker features, I stumbled on the following :  

Let's take this simple pixel shader : 

    float4 Blend(float4 c1, float4 c2, float a);

    float4 PS(float4 p : SV_Position) : SV_Target
    {
        float4 c1 = //do something
        float4 c2 = //do something
        return Blend(c1,c2, a);
    }

In order to link a function to this shader, name must be matching eg : 

   float4 Blend(float4 c1, float4 c2, float a)
  {
      return lerp(c1,c2,a);
  }

If I provide a function like : 

    float4 Blend_Add(float4 c1, float4 c2, float a)
    {
        return lerp(c1,c1+c2,a);
    }
 
Linking will fail.

This is (almost) not an issue in the above case (Have my Blend_Add function called blend Blend instead.

But this prevents to have all blend modes in a single file eg : 

    float4 Blend_Normal(float4 c1, float4 c2, float a)
    {
       return lerp(c1,c2,a);
    }
    float4 Blend_Add(float4 c1, float4 c2, float a)
    {
        return lerp(c1,c1+c2,a);
    }
    float4 Blend_Multiply(float4 c1, float4 c2, float a)
    {
        return lerp(c1,c1*c2,a);
    }

Moreover, in case I want to perform the task multiple times in the same pixel shader, eg, like in the following code : 

    float4 PS(float4 p : SV_Position) : SV_Target
    {
        float4 c1 = //do something
        float4 c2 = //do something
        float4 c3 = //do something
        c1 = Blend(c1,c2, a1);
        return Blend2(c1,c3, a2);
    }

I wish to be able to route Blend to Blend_Add, and Blend2 to Blend_Multiply (for example).

This would allow a lot more flexibility for composing  shaders at bytecode level.

As a side note, I did implemented that using a modified version of the source, so if there is interest I would be happy to share it. (This was a quick hacky proof of concept at the time so it would require some cleaning, plus if would involve a little bit of api changes)

Thanks

**Comment by tex3d** [comment]
I believe the linker has support for something very similar to what you want that should solve the problem.

The API (not the dxl.exe command line tool yet, sadly) has support for the option displayed when you type `dxc.exe -?`:
```
-exports <value>        Specify exports when compiling a library: export1[[,export1_clone,...]=internal_name][;...]
```

This is a renaming (and cloning) of functions rather than call sites.  You can link your function library to a new library (one input lib, one output lib) using this option to rename and clone functions to satisfy callsites in another library that you will be linking in another step.  For instance, let's take your example, and imagine you have a third call, `Blend3` that you also want to link to `Blend_Multiply`.  In this case, you would link to an intermediate library using:
`-exports Blend=Blend_Add;Blend2,Blend3=Blend_Multiply`

You would get an output library with three exported functions matching the call sites in your pixel shader.  After that, you would link this library to the one containing your entry with the call sites.

Given your scenario, it might make sense to make a new option with the same syntax as exports that operates on call sites and eliminates the intermediate step.  It could be called `-imports`, and would allow you to assign functions at call sites to functions in the set of libraries you are linking.  However, more thought should go into this, since the best way to support this kind of scenario is likely some sort of interface objects that can be resolved at link time to concrete implementations, like the runtime interfaces that were deprecated in D3D12.

Note: there's nothing wrong with playing with the code in support of some custom scenario, as long as you can produce some valid DXIL at the end that passes through the DXIL.dll validator and runs across hardware and drivers.  If you feel you have something useful and general-purpose that you might like to contribute, feel free to reach out for guidance on how the API and code should be structured to fit with the rest of the project and planned directions.
