### ISSUE TITLE
Missing implicit type cast for function-style vector cast

### ISSUE THREAD

**Issue by antiagainst** [Microsoft/DirectXShaderCompiler#331]
The following source code:
```hlsl
float4 main(int4 input: A) : SV_TARGET {
  int a;
  float b;
  b = float(a);
  return float4(input);
}
```
has the following parsed AST:
```rust
TranslationUnitDecl 0x19664e07880 <<invalid sloc>> <invalid sloc>
`-FunctionDecl 0x19665374ce8 <hlsl.hlsl:5:1, line:10:1> line:5:8 main 'float4 (int4)'
  |-ParmVarDecl 0x19665374b78 <col:13, col:18> col:18 used input 'int4':'vector<int, 4>'
  | `-SemanticDecl 0x19665374be8 <col:25> "A"
  |-CompoundStmt 0x196653752c0 <col:40, line:10:1>
  | |-DeclStmt 0x19665374eb0 <line:6:3, col:8>
  | | `-VarDecl 0x19665374e40 <col:3, col:7> col:7 used a 'int'
  | |-DeclStmt 0x19665374f50 <line:7:3, col:10>
  | | `-VarDecl 0x19665374ee0 <col:3, col:9> col:9 used b 'float'
  | |-BinaryOperator 0x19665375070 <line:8:3, col:14> 'float' '='
  | | |-DeclRefExpr 0x19665374f68 <col:3> 'float' lvalue Var 0x19665374ee0 'b' 'float'
  | | `-CXXFunctionalCastExpr 0x19665375048 <col:7, col:14> 'float' functional cast to float <NoOp>
  | |   `-InitListExpr 0x19665375000 <col:13> 'float'
  | |     `-ImplicitCastExpr 0x19665374fe8 <col:13> 'float' <IntegralToFloating>
  | |       `-ImplicitCastExpr 0x19665374fd0 <col:13> 'int' <LValueToRValue>
  | |         `-DeclRefExpr 0x19665374fa8 <col:13> 'int' lvalue Var 0x19665374e40 'a' 'int'
  | `-ReturnStmt 0x196653752a8 <line:9:3, col:22>
  |   `-CXXFunctionalCastExpr 0x19665375280 <col:10, col:22> 'float4':'vector<float, 4>' functional cast to float4 <NoOp>
  |     `-InitListExpr 0x196653750e8 <col:17> 'float4':'vector<float, 4>'
  |       `-ImplicitCastExpr 0x196653750d0 <col:17> 'int4':'vector<int, 4>' <LValueToRValue>
  |         `-DeclRefExpr 0x196653750a8 <col:17> 'int4':'vector<int, 4>' lvalue ParmVar 0x19665374b78 'input' 'int4':'vector<int, 4>'
  `-SemanticDecl 0x19665374e08 <line:5:30> "SV_TARGET"
```

For `ReturnStmt`, it seems to me that there should exist an `ImplicitCastExpr` (converting `int4` into `float4`) between `InitListExpr` and `ImplicitCastExpr` (`LValueToRValue`). (`b = float(a)` has such an `ImplicitCastExpr` as a contrast.)

But this may be just my misunderstanding of the HLSL semantics. I'd really appreciate comments. Thanks!

@dneto0 @ehsannas

**Comment by ehsannas** [comment]
I think you're right. I expected a `ImplicitCastExpr` converting int4 to float4.

**Comment by dneto0** [comment]
It's reasonable to expect a similar behaviour between scalars and vectors.
However, the AST is an internal representation and the compiler writers get to make up their own rules.
It may be that the CXXFunctionCastExpr is supposed to take care of the extra generality.

I tried checking a similar case in OpenCL, where the similar construct would have been`(float4)(input)`.  But OpenCL disallows an implicit conversion in that case, and it doesn't compile.

But worth keeping open and asking Microsoft if this AST is intentional.

**Comment by marcelolr** [comment]
Need to look a bit more closely at this specific case (sorry, out for a long weekend), but InitListExpr is an odd case. HLSL performs flattening of the right-hand side of initialization in some contexts, and we validate it all but don't construct a full AST for the conversions because they can be linear on the number of primitives.

Check [HLSLExternalSource::InitializeInitSequenceForHLSL](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/lib/Sema/SemaHLSL.cpp#L6033) for how the analysis is done. CodeGen will likewise "unroll" the assignment (which we don't yet clean up properly in all cases).

Consider:

```
struct S { int i[2]; };
int g_big[100];
float4 main() : SV_Target {
  S s = { 1, 2 };
  float f_big[102] = { g_big, s }; 
  float4 f4 = { 4, s, f_big[3] };
  return f4;
}
```

You can also have structures straddling mis-aligned structures on one hand or the other. These samples are rather extreme, but there are handy cases when filling up vectors and matrices with other bits.

**Comment by antiagainst** [comment]
For the ease of following this thread, the core part of the parsed AST for the code snippet by @marcelolr looks like:

```rust
  | |-DeclStmt 0x19665535c58 <line:8:3, col:17>
  | | `-VarDecl 0x19665535b18 <col:3, col:16> col:5 used s 'S' cinit
  | |   `-InitListExpr 0x19665535bd8 <col:9, col:16> 'S'
  | |     |-ImplicitCastExpr 0x19665535c28 <col:11> 'int' <IntegralCast>
  | |     | `-IntegerLiteral 0x19665535b88 <col:11> 'literal int' 1
  | |     `-ImplicitCastExpr 0x19665535c40 <col:14> 'int' <IntegralCast>
  | |       `-IntegerLiteral 0x19665535bb0 <col:14> 'literal int' 2
  | |-DeclStmt 0x19665535e10 <line:9:3, col:34>
  | | `-VarDecl 0x19665535d00 <col:3, col:33> col:9 used f_big 'float [102]' cinit
  | |   `-InitListExpr 0x19665535dc0 <col:22, col:33> 'float [102]'
  | |     |-DeclRefExpr 0x19665535d70 <col:24> 'const int [100]' lvalue Var 0x1966552cdc0 'g_big' 'const int [100]'
  | |     `-DeclRefExpr 0x19665535d98 <col:31> 'S' lvalue Var 0x19665535b18 's' 'S'
  | |-DeclStmt 0x19665536010 <line:10:3, col:33>
  | | `-VarDecl 0x19665535e38 <col:3, col:32> col:10 used f4 'float4':'vector<float, 4>' nrvo cinit
  | |   `-InitListExpr 0x19665535f88 <col:15, col:32> 'float4':'vector<float, 4>'
  | |     |-ImplicitCastExpr 0x19665535fe0 <col:17> 'float' <IntegralToFloating>
  | |     | `-IntegerLiteral 0x19665535ea8 <col:17> 'literal int' 4
  | |     |-DeclRefExpr 0x19665535ed0 <col:20> 'S' lvalue Var 0x19665535b18 's' 'S'
  | |     `-ImplicitCastExpr 0x19665535ff8 <col:23, col:30> 'float' <LValueToRValue>
  | |       `-ArraySubscriptExpr 0x19665535f60 <col:23, col:30> 'float' lvalue
  | |         |-ImplicitCastExpr 0x19665535f48 <col:23> 'float [102]' <LValueToRValue>
  | |         | `-DeclRefExpr 0x19665535ef8 <col:23> 'float [102]' lvalue Var 0x19665535d00 'f_big' 'float [102]'
  | |         `-IntegerLiteral 0x19665535f20 <col:29> 'literal int' 3
```

**Comment by antiagainst** [comment]
@marcelolr: I see the complexity involved with `InitListExpr`. Based on the previous examples, it seems that the current AST will inject `ImplictCastExpr` for builtin types but not composite or HLSL types. We can follow the way DXIL codegen (in [`ScanInitList`](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/lib/CodeGen/CGHLSLMS.cpp#L4399) and [`FlattenValToInitList`](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/lib/CodeGen/CGHLSLMS.cpp#L4126) if I'm correct) to handle the composite extraction and construction together with type casting if the current AST representation is intended. But it seems a little bit duplicated for me since we are essentially doing type analysis again when codegen'ing, which is already done in AST construction.

**Comment by marcelolr** [comment]
@antiagainst I'd recommend following the DXIL codegen pattern for this. There's an argument to be made for encoding some of the cast analysis discovered during AST build-up so it doesn't need to be redone at codegen time, and if so we could read that information from the initialization expression rather than recalculating, but that would also be a custom thing (because today's representation requires a per-element conversion in say the array example above), so keeping this isolated behind helpers seems reasonable for now. We also benefit from the current separation in scenarios where we just support code editor queries.

This is one of the language features we were hoping to modify to bring more in line with C/C++, but there are use cases today where code is more readable & expressive by using these. We might trim the feature some at some point, but we don't currently have a proposal that's valuable enough to warrant a break in behavior.

**Comment by antiagainst** [comment]
Understood. We'll handle it using a similar way to DXIL then. Thanks for the explanation!
