### ISSUE TITLE
"-flegacy-resource-reservation" doesn't keep resource stripped by optmization

### ISSUE THREAD

**Issue by hamwj1991** [microsoft/DirectXShaderCompiler#3326]
"-flegacy-resource-reservation" only perserve resource not referenced by any code. 

If a resource was referenced by code which was stripped in optimization, the resource would not occur in shader reflection, wheather "-flegacy-resource-reservation" was specified or not. 

this simple sample should reproduce this problem, where root_texture was used by optimized, so there is no root_texture in reflection info, which situation was not wanted.

```hlsl
SamplerState texture_sampler : register(s0);

Texture2D<half4> root_texture;
Texture2D<half4> diffuse_texture;
Texture2D<half4> noise_texture;
Texture2D<half4> unique_hair_value_texture;
Texture2D<half4> alpha_texture;
Texture2D<half4> depth_texture;
Texture2D<half4> ao_texture;

float4 PSMain(float2 uv) : SV_Target0
{
	float root_mask = root_texture.Sample(texture_sampler, uv).r;
	float3 diffuse = diffuse_texture.Sample(texture_sampler, uv2nd).rgb;
	float unique_hair_value = unique_hair_value_texture.Sample(texture_sampler, uv).r;
	float alpha = alpha_texture.Sample(texture_sampler, uv).r;
	float depth = depth_texture.Sample(texture_sampler, uv).r;
	float noise = noise_texture.Sample(texture_sampler, frac(uv * 24)).r;
	float ao = ao_texture.Sample(texture_sampler, uv2nd).r;
	float brightness = 1.0;
	float random_value_variation = 0.5;
	float random_hue_variation = 0.2;
	float vertex_color_strength = 1;
	float3 root_color = {1, 1, 1};
	float3 tip_color = {1, 0.999999, 1};
	float3 tangentA = {0, 0, 1};
	float3 tangentB = {0, 0, 1};
	float3 tangent = {0, 0, 0};
	float ao_min = 0;
	float ao_max = 1;
	float ao_facing_exp = 1;
	float ao_depth_masking = 0.7;
	float ao_depth_max = 1;

	float3 hair_base_color = lerp(root_color, tip_color, root_mask) * diffuse * (1 +noise) * brightness;

        return float4(hair_base_color, 1);
}
```

dxc version refs/tags/v1.5.2010

hope this problem will be addressed, thanks a lot.

**Comment by tex3d** [comment]
I'm confused by your description of the problem and the example.  Let me try to clarify the purpose of the flag, which appears to be working correctly.

The purpose of `-flegacy-resource-reservation` is to reserve the register binding for resources that have **explicit register bindings**, but are unused, either because they are unreferenced, or because their use was optimized away.  This is what fxc would do on shader models 5.0 and below, but changed in shader model 5.1.

Dxc defaults to the behavior of fxc with shader model 5.1, which is to use the slot, even when explicit bindings on the unused resource are present.  `-flegacy-resource-reservation` will allow you to keep those explicitly bound registers reserved, so automatic binding will not try to use them.

Both Dxc and Fxc omit unused resources from the binding table, even when the slot is reserved.  This is by-design.  The resource binding table identifies the resources that are required to be bound in order to run the shader, not all resources declared when you compiled it.

Example:

```HLSL
Texture2D<float4> Tex2;
Texture2D<float4> Tex1 : register(t0);

float4 main(float4 coord : TEXCOORD) : SV_Target
{
  // Whether or not the following line is present,
  // Tex1 will be unused in the final shader.
  float4 a = Tex1.Load(coord.xyz);

  return Tex2.Load(coord.xyz);
}
```

This will bind `Tex2` to `t0` by default, because `Tex1` is ultimately unused.

If you specify `-flegacy-resource-reservation`, `t0` will be reserved for `Tex1` because of the explicit register binding, causing `Tex2` to bind to `t1` instead.  The line that uses `Tex1` may be present (and optimized away) or removed entirely, it makes no difference to the register bindings produced in either case.
