### ISSUE TITLE
[SPIR-V] does not take -Gis (IEEE strict) argument into account

### ISSUE THREAD

**Issue by aras-p** [microsoft/DirectXShaderCompiler#3331]
The `-Gis` command line argument should effectively mark all variables behave as if they had `precise` HLSL modifier in them (that's what #2861 seems to be doing in DXIL output).

But SPIR-V output seems to generate completely identical result no matter if `-Gis` is present or not. Only actually spelling out `precise` on variables makes it generate the `NoContraction` SPIR-V decorations.

**Comment by ehsannas** [comment]
Thanks for reporting @aras-p. I think we have missed to implement this command line option for the SPIR-V backend.

**Comment by Jasper-Bekkers** [comment]
Now with #4529 merged in, I was wondering if this issue went up in priority? To have have sane floating point behavior we rely on this for our DXIL codepath, but would also love to rely on this for our SPIRV codepath. Having this makes a world of difference to us in terms of having to debug odd floating point issues. On the CPU side we got rid of relying of fastmath style behavior since we started using Rust and it's been a breath of fresh air.

**Comment by sudonatalie** [comment]
#4529 was just part of some general error messaging improvements and cleanup following issue triage, so implementing `-Gis` is still not currently on our roadmap of priorities for the near future. It should be supported by the SPIR-V backend though so we would be happy to review any PRs that address this, and provide any help with implementation questions if someone in the community is interested in contributing it sooner.
