### ISSUE TITLE
Provide a disassembler

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3369]
spirv has spirv-dis. please include a standalone dxc-dis tool.

**Comment by Jasper-Bekkers** [comment]
@seanbaxter if it's of any help, mesa has dxil_dump.h / dxil_dump.c that one can use to disassemble some parts.

**Comment by jenatali** [comment]
There is an `IDxcCompiler::Disassemble` (https://github.com/microsoft/DirectXShaderCompiler/blob/master/include/dxc/dxcapi.h#L301), it's just a matter of building a standalone executable for it.

**Comment by tex3d** [comment]
We have `dxc.exe -dumpbin <file>` for this.  Is this sufficient for the need?  If not, why not?

Granted, the option name could be better/more discoverable (it's inherited from fxc.exe).

Our general direction is to make more functionality available through dxc.exe rather than adding more special-purpose driver executables.
