### ISSUE TITLE
DXIL.rst has wrong resource type documentation

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3411]
The DXIL doc disagrees with dxc in the type of resource GlobalVariable metadata. Eg, 

https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#metadata-resource-records
![Screenshot at 2021-01-30 19-48-45](https://user-images.githubusercontent.com/521513/106371589-385cff00-6334-11eb-9477-c53f2b11cd25.png)

But dxc produces different types:
http://shader-playground.timjones.io/aab301e5c7b8488b1e26854922b80052
![Screenshot at 2021-01-30 19-49-50](https://user-images.githubusercontent.com/521513/106371596-5591cd80-6334-11eb-8bce-4ce13faf90c6.png)

Although neither of these types agree with the result type of @dx.op.sample.

**Comment by damyanp** [comment]
@bogner - could you have a look at this and decide what we need to do please?

**Comment by bogner** [comment]
Yeah, it looks like there are a couple of inaccuracies in the [Metadata Resource Records](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#metadata-resource-records) and [Reflection Information](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#reflection-information) example as far as the "Pointer to a global constant symbol" argument is concerned.

1. Both refer to a `ResElem` type instead of the `ResRet` [resource operation return types](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#resource-operation-return-types). This is the type that operations like [sample](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#sample) actually return.
2. These examples seem to conflate the return type of resource operations with the type of the global for the metadata, which "original shape of the resource and element type" refers to. This is the `%"class.Texture2D<vector<float, 4> >"` type you see.
3. AFAICT in practice the global itself is usually stripped and the metadata just refers to an `undef` with the right type, which adds to the confusion.

So the SRV example should probably be either a somewhat complete example like so:
```llvm
; Scalar resource: Texture2D<float4> MyTexture2D.
%"class.Texture2D<vector<float, 4> >" = type { <4 x float>, %"class.Texture2D<vector<float, 4> >::mips_type" }
%"class.Texture2D<vector<float, 4> >::mips_type" = type { i32 }
@MyTexture2D = external addrspace(1) constant %"class.Texture2D<vector<float, 4> >", align 16
!2 = !{ i32 0, %"class.Texture2D<vector<float, 4> >"* @MyTexture2D, !"MyTexture2D",
        i32 0, i32 0, i32 1, i32 2, i32 0, null }
```

or we should just simplify this to make it clear it's only really about the metadata values and type like so:
```llvm
%"class.Texture2D<vector<float, 4> >" = ...
!2 = !{ i32 0, %"class.Texture2D<vector<float, 4> >"* undef, !"MyTexture2D",
        i32 0, i32 0, i32 1, i32 2, i32 0, null }
```
