### ISSUE TITLE
Semantics should be used for coordinating interface variables, not register packing

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3438]
The choice of packed registers makes it too hard for DXIL producers with GLSL-like semantics to coordinate interface variables between shader stages. When interface variables are globals, there is no real order among them. Generally interface variables are pulled into the module only when ODR-used, so a latter stage doesn't list as inputs all the variables named as outputs by the preceding stage. This makes mapping interfaces to registers unreliable.

A workaround is to patch shaders at runtime, just prior to CreateGraphicsPipelineState.
> Driver compilers can rearrange signature elements as they see fit, while preserving compatibility of connected pipeline stages. DXIL is designed in such a way that it is easy to 'relocate' signature elements - loadInput/storeOutput row and column indices do not need to change since they are relative to the start row/column for each element.

However, for an already-compiled shader, this requires opening up the LLVM metadata, patching that, then re-validating and signing with dxil.dll, since a patch will invalidate the hash.

There are only downsides to using register packing compared to semantics, especially since all shader stages are available when building the pipeline object. I wrote more details about this and referenced another project where people are facing this same frustration:
https://github.com/KhronosGroup/SPIRV-Cross/issues/1611

**Comment by llvm-beanz** [comment]
The design of DXIL today is pretty intrinsically tied to implementation details of HLSL in DXC. I don't see that changing anytime soon. As we work to implement DXIL generation in LLVM we expect to have cleaner abstractions and interfaces, but the structure of DXIL isn't changing and I don't expect we're going to support patching pre-compiled shaders.

Since I don't see a path to addressing this concern I'm going to close this issue.
