### ISSUE TITLE
The argument ‘/Zi ’ does not take effect when use IDxcCompiler::Compiler

### ISSUE THREAD

**Issue by WhiteSmoogy** [microsoft/DirectXShaderCompiler#3461]
Code：
cbuffer _RootShaderParameters
{
float4 BufferSizeAndInvSize;
Texture2D Depth;
float4 InvDeviceZToWorldZTransform;
float NormalBias;
RWTexture2D<float4> Output;
float4x4 SVPositionToWorld;
RaytracingAccelerationStructure TLAS;
float3 WorldCameraOrigin;
Texture2D WorldNormalBuffer;
}
args：
▶ | [0] | 0x00007ff645958c40 L"/auto-binding-space" | const wchar_t *
▶ | [1] | 0x00007ff6459545d8 L"1" | const wchar_t *
▶ | [2] | 0x00007ff645958ca0 L"/exports" | const wchar_t *
▶ | [3] | 0x0000001d300fdec0 L"RayGen" | const wchar_t *
▶ | [3] | 0x0000001d300fdec0 L"RayGen" | const wchar_t *
▶ | [4] | 0x00007ff645958cc8 L"/Zi" | const wchar_t *
▶ | [5] | 0x00007ff645902290 L"-Qembed_debug" | const wchar_t *
▶ | [6] | 0x00007ff645958d48 L"/O1" | const wchar_t *

call Compiler by this Code：
Compiler->Compile(
			TextBlob.Get(),
			L"hlsl.hlsl",
			L“RayGen”,
			L“lib_6_3”,
			args.data(),
			static_cast<UINT32>(args.size()),
			NULL,
			0,
			NULL,
			&CompileResult.GetRef()
		)

but the error buffer output：
error: validation errors
error: Invalid resource return type. 'TLAS' **Use /Zi for source location**.
Validation failed.

**Comment by pow2clk** [comment]
We used to include that caveat whenever we didn't have location information. Usually it was because there was no `Zi` flag, but not always. I wouldn't conclude that the `Zi` flag wasn't being respected only that the error message was bad.

In fact, the `Zi` flag is no longer needed to have this location information. Please try again and if it fails, reopen the bug.
