### ISSUE TITLE
Wave intrinsics lead to artifacts on polygon edges

### ISSUE THREAD

**Issue by ohlenbg** [microsoft/DirectXShaderCompiler#3500]
When using Wave intrinsics, very bad artifacts are produced on the polygon edges.  

In the attached screenshot, this shader is executed on 36 triangles that make up a full-screen plane.  Artifacts appear on these polygon edges.

We have a large UAV that we use as a ring buffer - Allocated with 64 * 32 * 16384 elements where we allocate 64 uint4's per thread, assume each warp can have 32 threads and have 16k of these 32x64 blocks to absolutely guarantee we never stomp an active allocation.
A counter is atomically incremented to determine which part of the ring buffer is allocated for the current thread

With #define USE_WORKING_UAV_CASE in line 1, it demonstrates our current safe and simple approach to allocating ring buffer blocks to individual shader threads. 
Each thread performs one atomic increment to allocate 64 uint4's in the ring buffer

When commenting out line 1 and instead uncomment #define USE_WAVE_INTRINSICS in line 3, it demonstrates our attempt at using the Wave intrinsics in order to only perform one atomic increment per wave rather than an atomic increment per lane.
The first lane performs one atomic increment to allocate 32 x 64 uint4's in the ring buffer, which is a block of 64 uint4's per lane.

Using #define USE_WAVE_INTRINSICS produces the artifacts

[DebugRenderingPixelShader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6034934/DebugRenderingPixelShader.txt)

![UAV_Demo_Results](https://user-images.githubusercontent.com/79572684/108981599-2baa9d00-768d-11eb-80a6-c48e04937705.png)

**Comment by tex3d** [comment]
Actually it appears to assume 32 lanes (which also is not correct for a variety of GPUs).

But even where it is, these two paths will not produce the same result, particularly because of polygon edges.  That's because some lanes will be assigned uncovered samples in quads.  These invisible helper lanes will not contribute to wave intrinsics or UAV operations.

This means that the InterlockedAdd path will only increment on active lanes handling covered samples (active non-helper lanes), which may be fewer than a full wave, but will be identical to the number you are actually operating on through the UAV accesses.

The USE_WAVE_INTRINSICS path appears to assume a wave will always have 32 active (non-helper) lanes, which is not going to be true.  There will be indexes allocated but uninitialized/unused.

So these paths are not equivalent.

You could correct this by counting the active lanes (`WaveActiveCountBits(true)` or `WaveActiveSum(1)`) and using a prefix sum (`WavePrefixCountBits(true)` or `WavePrefixSum(1)`) for the individual indices.  But why bother doing all this when the atomic operation should be optimized by the driver across the wave in any case, producing the result you want, right?
