### ISSUE TITLE
Potential issues on denorms in DirectX Intermediate Language spec(master/docs/DXIL.rst)

### ISSUE THREAD

**Issue by tangogu** [microsoft/DirectXShaderCompiler#3585]
1. To FMin/FMax, still flush to zero first then comparison, without considering new denorm preserve mode, is this really expected?
2. To sin/tan/asin/atan of denorms input, it can better be represented the same as the input denorm value while spec require denorms flush to zero. Considering no performance/complexity in HW, and flush to zero does impact precision, is there any plan to change or allow different behaviors on different vendors?
3. To rsq/sqrt/log/exp, it also require denorms input get zero or Inf while the better value can be achieved by IHV. Does the spec plan to allow different behaviors on different vendors?

Another issue is general issue on FDiv. It only mentioned that "When fast math is enabled, implementation may use reciprocal form: src0*(1/src1).". If fast math is disabled, does it mean IHV have to offer real division operation instead of always implementing by rcp+mul solution?

Thanks

**Comment by damyanp** [comment]
Please let us know if this is still something you need us to look further into.  As this issue is many years old now, we're not sure it is worth spending time doing a full investigation.  I suggest you have a look at the [D3D11 spec](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm) where the behavior of some of these operations are documented in more detail.
