### ISSUE TITLE
[SPIR-V] DXC expects shader compilation to fail, but SPIR-V generation succeeds

### ISSUE THREAD

**Issue by jenatali** [microsoft/DirectXShaderCompiler#3651]
Running the https://github.com/microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/HLSLFileCheck/hlsl/control_flow/if_else/if9.hlsl against SPIR-V generation, I'd expect this shader to fail since there's a declared output that's not written to, but it succeeds and produces SPIR-V.

Probably a secondary/orthogonal issue is whether SPIRV-Val should complain about this: it doesn't (at least with my potentially-outdated version).

**Comment by jaebaek** [comment]
@jenatali Thank you for report this issue. We will take a look.

**Comment by sudonatalie** [comment]
Thanks for reporting, and sorry for the delayed response! This is an odd case since this is valid SPIR-V according to the spec, so spirv-val shouldn't complain about it. Down the line an error like this should be caught by Vulkan validation layers due to mismatched stage variables, but catching it during compilation would require somewhat hacky checks both before and after optimization passes. Though we generally want to mirror the success and failure cases between SPIR-V and DXIL generation, this one doesn't seem worth the maintenance for the benefit, so we're opting to close this bug as won't fix.
