### ISSUE TITLE
Rebase hlsl-2021 branch on top of master

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#3696]
It would be really nice to refresh the hlsl-2021 branch so they contain all the recent fixes that have gone into master, looks like it's a relatively straight forward rebase/merge operation.

**Comment by pow2clk** [comment]
Since it seems there's interest, perhaps a comment along the lines of what what was discussed elsewhere would be useful here. 

We don't have a strict schedule for merging hlsl-2021 to the main branch. "When it's ready" is a meme and a war cry, but it's accurate here. Templates are a popular feature. Much credit to @tcorringham for the work! We want them as widely available as possible as soon as possible. They have proved disruptive as various bugs have demonstrated and we want to be sure that the great new stuff in this branch doesn't disrupt the great stuff in the main branch or make the bad stuff worse.

What I can say is that we'd prefer that the "2021" part of the branch and feature name doesn't become bitterly ironic 😝

**Comment by Jasper-Bekkers** [comment]
@pow2clk Thanks for the heads up, I'm aware this is going to be in some "future hlsl" version and I think that's fine, we're mostly interested at this point in trying to run ahead as much as possible and will report any bugs as we find them (with proper reproducers like we've done in the past) to hopefully assist a bit in stabilizing this feature. 

The reason for this issue in particular was because we wanted to start prototyping with the template support but needed some of the fixes for other issues that we'd reported before, fixes that ended up in the master branch before. I hope that this is the right way to use and view this branch - we won't be shipping with this any time soon for example, and I hope it can be useful to you all at the same time.

@hekota Thanks for doing the merge!

**Comment by hekota** [comment]
You're welcome! Feel free to nudge us if you see hlsl-2021 getting too much out of sync with master ;).
