### ISSUE TITLE
Validate HLSL as a whole

### ISSUE THREAD

**Issue by kvark** [microsoft/DirectXShaderCompiler#3714]
It would be useful for us to be able to tell if a particular HLSL module is valid by itself (similar to how "spirv-val" checks SPIR-V modules), without any particular entry point or execution model specified.
Maybe it's possible today? I wasn't able to figure out from the documentation.

**Comment by pow2clk** [comment]
I'm not entirely sure what you're looking for, but perhaps `dxv` is what you want? It isn't included in the release package yet, but it is built by default when you build the project. It will load a Dxil blob and perform the validation on it. You can do the same with the dxcompiler.dll api. 

That said, these DXIL blobs are built with specified entry points and targets. Libraries are something of an exception. Maybe that's what you have in mind?

**Comment by kvark** [comment]
Thanks for the pointers! We'll need this for DXIL as well, but currently asking about HLSL.

**Comment by llvm-beanz** [comment]
It isn't really possible to validate that HLSL is possible at the source level today. The language is defined to allow invalid patterns in source if they are eliminated during optimization.

I'm in favor of changing the language to make the language verifiable at the source level, but that isn't going to happen anytime soon.

Since this issue isn't directly actionable I'm going to close it.
