### ISSUE TITLE
[SPIR-V] use isomorphic type for a local variable and a global variable with the same resource type

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#3727]
As explained in #3721, SPIR-V backend uses a pointer to the type for a local variable while it uses the type itself for a global variable when the type is one of `RWByteAddressBuffer`, `RWStructuredBuffer`, and `AppendStructuredBuffer`.
It results in one more dereference for the local variable compared to the global variable in all the places. In addition, we have to handle this exception for all the places e.g., type lowering, function argument passing, ...

1. We want to check if we can use the isomorphic type for a local variable and a global variable when the type is one of `RWByteAddressBuffer`, `RWStructuredBuffer`, and `AppendStructuredBuffer` (without critical issues)
2. Handle all the place to avoid the additional dereferencing for the local variable case.

**Comment by s-perron** [comment]
The reason we do the pointer-to-pointer is to better match the semantics:

```
RWStructuredBuffer<float4> global_resource_variable;

void getResource(out RWStructuredBuffer<float4> result) {
  result = global_resource_variable;
}

[numthreads(1,1,1)]
void main() {
  RWStructuredBuffer<float4> x;
  getResource(x);
  x[0] = 0; // Does global_resource_variable[0] change?
}
```

The answer is "yes it does." The idea is that `x` is really a reference to `global_resource_variable`. That is how it was implemented. Because `global_resource_variable` is implemented as a pointer to data, we could simple pass that pointer around. The difficulty would be the storage class. We wanted to keep the spir-v a legal as possible. We cannot have the OpVariable for a function scope variable point to uniform storage. The pointer to a pointer is also illegal when variable pointers are not used, but it is less likely to confuse the optimizer.

that is why we did it the way we did. At this point, I don't think it is worth trying to revisit.
