### ISSUE TITLE
SV_Barycentrics can't be declared in a struct, needs to be declared on the frag method

### ISSUE THREAD

**Issue by hybridherbst** [microsoft/DirectXShaderCompiler#3729]
While doing
```
fixed4 frag (v2f i, float3 PerspectiveBaryWeights : SV_Barycentrics) : SV_Target
```
works, moving the SV_Barycentrics declaration to the v2f declaration fails:
```
struct v2f
{
  float4 vertex : SV_POSITION;
  float2 uv : TEXCOORD0;
  float3 PerspectiveBaryWeights : SV_Barycentrics;
};
```
leads to
> Error: Semantic SV_Barycentrics is invalid for shader model: vs Use /Zi for source location. (on d3d11)

Is this expected? My (limited) understanding was that all semantics can be moved into a parameter struct, but that doesn't seem to be the case here.

Reproduction:
http://shader-playground.timjones.io/1e89247ebc1bb12902aed1baa18b3256

**Comment by hybridherbst** [comment]
Turns out at least in Unity this can be defined out depending on stage:

```
            struct v2f
            {
                float4 vertex : SV_POSITION;
                float2 uv : TEXCOORD0;
                #if defined(SHADER_STAGE_FRAGMENT)
                float3 barycentricWeights : SV_Barycentrics;
                #endif
            };
```
and
```
#if defined(SHADER_STAGE_FRAGMENT)
            fixed4 frag (v2f i) : SV_Target
            {
                return float4(i.barycentricWeights, 1);
            }
            #endif
```

Guess the question still holds why the compiler complains about this (and not just silently ignores it), as this will in my understanding cause layout differences between the v2f format in vertex and fragment shader.

**Comment by pow2clk** [comment]
Hi @hybridherbst!

You can read more about `SV_Barycentrics` here: https://github.com/microsoft/DirectXShaderCompiler/wiki/SV_Barycentrics

As you can see, there is no mention of it being writable in the vertex shader, which is why it can't be used there. It is not unique in that respect as `SV_IsFrontFace` also has that characteristic: https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics#semantics-supported-only-for-direct3d-10-and-newer

To accomplish something similar to how you used the macros you did, there is a `__SHADER_TARGET_STAGE` implicit define that you can use to exclude the code: https://github.com/microsoft/DirectXShaderCompiler/wiki/Predefined-Version-Macros#shader-stage-defines.

However, if what you want to do is define a vertex and fragment shader in the same file, provided you don't use the struct that contains the unwritable semantic in the vertex shader, you shouldn't need to put defines around the `frag()` entry point.
