### ISSUE TITLE
[SPIR-V] DXC June 2021 not outputting embedded debug information

### ISSUE THREAD

**Issue by Pursche** [microsoft/DirectXShaderCompiler#3899]
Hello, I recently updated from a mid-2020 version of DXC to the DXC June 2021 release, and I'm having a bit of an issue. After updating I'm no longer getting any embedded debug information in my shader binaries.

I am using the DLL interface of the compiler to compile HLSL into SPIR-V for my Vulkan renderer, I read about the new IDxcCompiler3 interface and I modified my code to better match what I saw on this page:
https://github.com/microsoft/DirectXShaderCompiler/wiki/Using-dxc.exe-and-dxcompiler.dll

I am providing the -Zi and -Qembed_debug arguments, and then I am getting the output like this:

        Microsoft::WRL::ComPtr<IDxcBlob> pShader = nullptr;
        Microsoft::WRL::ComPtr<IDxcBlobUtf16> pShaderName = nullptr;

        pCompileResult->GetOutput(DXC_OUT_OBJECT, IID_PPV_ARGS(&pShader), &pShaderName);

        blobSize = pShader->GetBufferSize();
        blob = new char[blobSize];
        
        memcpy(blob, pShader->GetBufferPointer(), blobSize);
        
Am I incorrect to assume that the debug information should be in DXC_OUT_OBJECT if I provide the -Zi and -Qembed_debug arguments? How else should I retrieve my embedded debug information? I would use PDBs but Vulkan doesn't seem to support that.

Here is a pastebin of (hopefully) all relevant code: https://pastebin.com/Sh7p8dDJ

**Comment by Pursche** [comment]
Jesse Natalie from Microsoft confirmed to me in the DirectX Discord that the DXC_OUT_OBJECT should include debug information if I'm passing -Zi and -Qembed_debug. So on the off chance that this isn't a user error (which it might be, I'd love to have someone confirm if I'm using it correctly), it sounds like a SPIR-V output related bug to me.

I tried running the dxc.exe executable from the June 2021 release with the same command line arguments as I should be using with the dll, other than stripping some unnecessary defines. I have attached the source file and both compiled versions, and here is the commandline that I ran for the .exe:
`dxc.exe solidColor.ps.hlsl -E main -T ps_6_5 -spirv -fspv-target-env=vulkan1.1 -fvk-use-gl-layout -Zpr -enable-16bit-types -WX -Zi -Qembed_debug -Od -Fo solidColor.ps.hlsl.spv`
[shaders.zip](https://github.com/microsoft/DirectXShaderCompiler/files/6947965/shaders.zip)

**Comment by Pursche** [comment]
I still can't get this to work, is there any chance you could tell me if I'm using it wrong or if this is a valid issue?

**Comment by Derzo** [comment]
Aaaagh I just spent hours on the same thing! Except that if I run dxc.exe, I get debug info, but if I run the exact same command with the API, I don't get debug info.

This was the first time I tried to get debug info running so I don't have experience with previous versions, but I quickly tried an older version because you mentioned it worked for you, but still couldn't get it to work

I've attached a clean C++ program that *should* do the same thing as
`dxc -spirv -Zi -E "cs_main" -T "cs_6_0" -Fo my_thing2.spv shader.hlsl`
[testing.zip](https://github.com/microsoft/DirectXShaderCompiler/files/7147771/testing.zip)

**Comment by Pursche** [comment]
So it's currently November, I am still having this issue and I still don't know if it's because I'm using it in the wrong way or not...

Any kind of verification if this is a valid issue or user error would be helpful.

**Comment by Pursche** [comment]
All I want for christmas is debug information.

**Comment by RuslanKutdusov** [comment]
We have the same issue, after a little bit of debugging I've found out that it was broken in [7f985ff4726eb24e275d3d5345cc33a232158317](https://github.com/microsoft/DirectXShaderCompiler/blob/0917aa9c0c20528b5cfb051f277eb01a222e51f2/tools/clang/lib/SPIRV/EmitVisitor.cpp#L644) by @jaebaek
where instead of getting source code from SpirvSource::getSource as it was before, the source code gets read from the file. The problem is that when using DXC API it is not mandatory to specify file name, actually, sometimes source code is gotten not from the file, but from the archive for example so there is no way to specify a file path to read by ReadSourceCode. Thus using ReadSourceCode is wrong particularly in EmitVisitor::visit(SpirvSource *inst), I don't know about other usages of ReadSourceCode. @jaebaek could it be fixed?

**Comment by RuslanKutdusov** [comment]
> Aaaagh I just spent hours on the same thing! Except that if I run dxc.exe, I get debug info, but if I run the exact same command with the API, I don't get debug info.
> 
> This was the first time I tried to get debug info running so I don't have experience with previous versions, but I quickly tried an older version because you mentioned it worked for you, but still couldn't get it to work
> 
> I've attached a clean C++ program that _should_ do the same thing as `dxc -spirv -Zi -E "cs_main" -T "cs_6_0" -Fo my_thing2.spv shader.hlsl` [testing.zip](https://github.com/microsoft/DirectXShaderCompiler/files/7147771/testing.zip) If you open the two files in text editor, in one you can see the shader source and not in the other. Actually I'm not currently doing `-Qembed_debug` in those tests, but that didn't change the outcomes

The sample there is a good example of a problem, where source code is not in a file, it is in memory, there is no way ReadSourceCode can get it

**Comment by phradsky** [comment]
I have the exact same problem as well :\

**Comment by Pursche** [comment]
@jaebaek You might want to close this one as well.
