### ISSUE TITLE
[Question] Does DXC support wrap-level primitives?

### ISSUE THREAD

**Issue by ghostplant** [microsoft/DirectXShaderCompiler#3924]
Wrap-level primitives are used for shaders to do SIMT computation without barriers, which is supported by many high-end devices like NVIDIA. Several computations cannot be executed very efficiently without using them.

**Comment by pow2clk** [comment]
Hi @ghostplant!

I think you mean warp-level primitives? (https://github.com/microsoft/DirectXShaderCompiler/wiki/Wave-Intrinsics) In which case the HLSL counterpart is wave primitives because, as an industry, we are sadly reluctant to converge on common terms. 

You might also look at https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-0-features-for-direct3d-12

Does that give you what you want?

**Comment by pow2clk** [comment]
I'm going to conclude that my response was satisfactory. Feel free to contact me directly if you need more information.
