### ISSUE TITLE
Implementations of abstract classes cannot be passed to functions

### ISSUE THREAD

**Issue by aluedke** [microsoft/DirectXShaderCompiler#395]
Some of our shaders use a scheme where an abstract class is declared and functions are written that use that abstract class.  A shader can then define the functions of that abstract class and pass the implementation into the functions.  This fails with an error.  Here's an example:

```
interface iPropertyState
{
  float GetStateValue(uint stateIndex);
}

float EvaluateState(const Property property, const iPropertyState propertyState)
{
  return propertyState.GetStateValue(GetInputIndex(property));
}

class ShaderState : iPropertyState
{
  float GetStateValue(uint stateIndex) { return states[stateIndex]; }
  float states[10];
}

/// body of shader
ShaderState state;
...
result = EvaluateState(property, state)
````

**Comment by marcelolr** [comment]
@aluedke again, hopefully I'll go into a deeper discussion on this in the near future.

The problem with interfaces is shared by some other language constructs that we're trying to stay away from, and it boils to requiring the compiler to do some amount of tracking values + unrolling + inlining + const prop to generate proper code.

In this case, it boils down to being able to devirtualize all calls properly (otherwise you end up with dynamic class linkage, which was a very-rarely-used feature and is not accessible in D3D12 AFAIK).

How pervasive is your use of this language construct? Did you ever end up with application-set classes?

**Comment by aluedke** [comment]
We use it for a subset of our shaders, mostly in effects shaders that we want a technical artist to be able to author with few errors.  Most of our other compile issues on the DXC compiler can be mitigated by massaging the code, but this is one that I haven't been able to find a simple change to fix.

**Comment by simondeschenes** [comment]
I am currently in the process of trying to move the engine of the game studio at work for from DX11 to DX12 and Vulkan. We are actually using the interface/class feature stated above everywhere. Is there any way to get this feature in DXC ?

**Comment by llvm-beanz** [comment]
This bug has been languishing for a long time, and I don't expect we're likely to prioritize it.

With HLSL 2021's templates feature, you should be able to translate many uses of interfaces to template polymorphism. For the pattern described in the initial description, making the interface-typed parameter instead a template type should allow the code to build with minimal changes.

If this is still a pressing use case and templates aren't a viable solution for you please re-open this bug with more information.

**Comment by bshalke** [comment]
I actually need this to move off of fxc because I use dynamically-linked shaders.  I'm working on an SDF-based renderer, and I need to be able to combine different functions at runtime so complex scenes can be composed of multiple primitive functions.  I have almost 100 functions across 3 different interfaces.  Each of those interfaces has a loop that processes (currently) up to 32 instances, using a directed acyclic graph to chain results.  It works surprisingly well, and has opened up a lot of unique possibilities.

This would be clearly impossible to do with statically-linked shaders, since the number of combinations is enormous.  In my research, it appears that DX12 does actually still support dynamic linking, but I still use DX11 because I can't go past SM 5.1.  Access to new shader features via dxc would be huge for this project.
