### ISSUE TITLE
[SPIR-V]How to rename spirv entry point?

### ISSUE THREAD

**Issue by LuciferSweety** [microsoft/DirectXShaderCompiler#3953]
I used the function spirv_cross::Compiler::rename_entry_point to rename other shading language's entry point.(gl,hlsl,metal)
But it can't rename for vulkan(spirv).
Can IDxcRewriter or SPIRV-Tools do this kind of behaviour?

**Comment by jaebaek** [comment]
Hi @LuciferSweety,

If the input is SPIR-V code (not HLSL), I think this should be posted in https://github.com/KhronosGroup/SPIRV-Tools/issues

**Comment by LuciferSweety** [comment]
Hi, @jaebaek,
The spirv code generated by dxc. 
If dxc have not this kind of behaviour, I'll be posting it in SPIRV-Tools.

**Comment by jaebaek** [comment]
Basically, DXC generates SPIR-V for the given HLSL code.
In order to deal with SPIR-V code e.g., optimization, validation check, instrumentation, ... , we have to use SPIRV-Tools.
I am not sure SPIRV-Tools (e.g., spirv-opt) has a pass to rename the entry point, but definitely this is must be reported or asked in SPIRV-Tools repo.

**Comment by LuciferSweety** [comment]
ok. Thanks!
