### ISSUE TITLE
Slim PDBs can't be embedded via /Qembed_debug

### ISSUE THREAD

**Issue by Aeva** [microsoft/DirectXShaderCompiler#3971]
If you try to run dxc.exe with both /Zs and /Qembed_debug, it fails with this error:
`dxc failed : Must enable debug info with /Zi for /Qembed_debug`

As /Zs and /Zi are mutually exclusive, this prevents embedding slim PDBs.

I'm able to repro this in release builds and also artifacts build 618b207a62f7b5d0f789d86baca5a47a2896f203.

**Comment by pow2clk** [comment]
I'm afraid this is not supported by design. If you have a specific use case that makes that absence particularly painful, let us know the details and maybe we can make some accomodation

**Comment by Aeva** [comment]
The use case is that I would like to receive PIX captures with PDBs embedded in them, but the aggregate size resulting from compiling all of the shaders with Zi iirc runs our build machines out of disk space, so instead what I get are PIX captures that have no PDBs at all.

Could this limitation at least be made clear in the documentation?

**Comment by jeffnn** [comment]
Hi Aeva,
Unfortunately the only way to get debug info embedded into the PIX capture is to capture an application that compiled shaders with /Zi and /Qembed_debug. Sounds like it's not feasible for you to modify your content pipe so that this happens with just the shaders you're interested in. 
Presumably you're aware that PIX has options to specify directories in which to search for PDBs. Just in case you aren't: in PIX, choose "Home->Settings" and scroll most of the way down. This should work just fine with /Zs, and in fact is the scenario that /Zs was designed for. PIX should automatically find the right PDB based on hash information in the shaders captured in the .wpix file.
Interestingly, the PIX team is in the middle of updating this system to enable better handling of large-scale PDB sets via caching etc. That'll probably be in the next release of WinPIX. I'll make a note to mention it here if/when that happens.

**Comment by jeffnn** [comment]
Note to self: PIX work item 36556597 for UI-side PDB caching.

**Comment by Aeva** [comment]
The project is Unreal based, so the problem is that embedding everything with /Zi is not really viable for us due to the sheer number of shaders, and we were hoping that /Zs's significant file size reduction might make embedding everything viable for us.  So the workflow we use currently is similar to the one you described above, where we rebuild and export pdbs for just a few shaders as needed for existing captures.  /Zi for external PDBs is fine in this case, since only a few need to be generated anyway.

Can you say more about this PDB set caching feature?
