### ISSUE TITLE
Question: Detecting driver support for dxc compiled shaders

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/DirectXShaderCompiler#4038]
We're using dxc to compile shaders with SM5.1. Unfortunately, on some older AMD FirePro drivers, we're seeing errors from `CreateGraphicsPipelineState` such as:

> D3D12 ERROR: ID3D12Device::CreateVertexShader: Shader is corrupt or in an unrecognized format

It's easily resolved by updating the drivers to the most recent version (from AMD's site, not from Windows AutoUpdate). But, we would like to diagnose this issue ahead of time, and present the user with relevant help. Is there any way to check driver support for dxc shaders, other than just attempting to create a pipeline state with a shader and checking for this specific error result?

FWIW, our command line flags expand to something similar to (in debug):
```
dxc.exe input.ps -T ps_5_1 -Fh output.h -Vn output -E main -Zi -Qembed_debug
```

**Comment by pow2clk** [comment]
Hi @MarkIngramUK

When you compile with a 5.1 target, the compiler actually upgrades it to 6.0, which is the lowest version it supports. Most of the time, that shouldn't matter. If it does, you'll see errors in the compilation.

Additionally, it will generate DXIL instead of DXBC. It's possible that the origin of the error you report is that the drivers you had installed may not have supported DXIL. You can determine this using this query struct: https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_shader_model

Another possibility is that initially, you weren't compiling with dxil.dll available. This will produce a warning at the start of compilation `warning: DXIL.dll not found.  Resulting DXIL will not be signed for use in release environments.` and would result in that error if you tried to load the output in a release environment.

I hope some of that has been helpful, but it's hard to give advice confidently without more information about why exactly it failed.

**Comment by pow2clk** [comment]
Querying the shader model version is a bit unintuitive, you can see an example implementation here: https://github.com/microsoft/DirectXShaderCompiler/blob/0c53d74705548033610e7f5eb7b60c3179e982a4/tools/dxexp/dxexp.cpp#L193

**Comment by MarkIngramUK** [comment]
Hi @pow2clk , thanks for the info!

I have a feeling it'll be the lack of DXIL support in the driver. We have a copy of the older drivers, so I can try adding the `D3D12_FEATURE_DATA_SHADER_MODEL` query, and see what they return. Given that dxc upgrades SM 5.1 => 6.0, should we be looking for a minimum of `D3D_SHADER_MODEL_6_0` (similar to the `GetHighestShaderModel` example), even though we specified `-T ps_5_1` on the command line?

**Comment by pow2clk** [comment]
Yes, in order to use the output of DXC, you'll need a driver that supports 6.0 or later. 

We've recognized that silently converting earlier shader models to 6.0 might lead to this sort of confusion. We'll be adding a warning for that case to try to make it clearer.

**Comment by MarkIngramUK** [comment]
Great - thanks :-)
