### ISSUE TITLE
reinterpret cast uint to float16_t

### ISSUE THREAD

**Issue by 44DA133A8B** [microsoft/DirectXShaderCompiler#4139]
Is there a way to reinterpret cast uint to float16_t and vice versa?

I've read the wiki page about 16-bit types in DXC, but there's no information on type casting on this page.
And I did not manage to find asfloat16() or anything like that.

**Comment by tex3d** [comment]
You can't reinterpret a uint as a single float16_t (different bit sizes), so I suspect you want to reinterpret the low and/or high 16-bits as float16_t value(s).  To do that, you would cast the uint to a uint16_t, then use asfloat16().  Here's an example of extracting both the low and high portions:
```
float16_t2 unpack_float16(uint value) {
  return float16_t2(
    asfloat16((uint16_t)value),
    asfloat16((uint16_t)(value >> 16)),
  );
}
```

If instead you want to cast a uint to float16_t, rather than reinterpret bits, then you can simply use a c-style cast: `(float16_t)myUint`.
