### ISSUE TITLE
[GBV] When using the gpu based validation, there can be a big spike of memory usage (9gb) when a patching shaders.

### ISSUE THREAD

**Issue by simontardif** [microsoft/DirectXShaderCompiler#4198]
I reach out to someone from nvidia to know where the issue can come from.

This is his response:
_The out of memory is mainly due to the bloat in the DXIL shader, which is the input to our driver. The DXIL shader size increases by 6x with your small source code modification. We suggest reaching out to Microsoft since this appears to be an issue in dxc._

So for the moment, we kept the fxc compiler as the it doesn't go beyond 2gb.

This is the callstack when we got that peak of memory:

D3D12Core.dll!TableFunctionTraits<0>::Detail::InvokerImpl<struct TableFunctionTraitsImpl<0>::FunctionTraits<46,17,void>,void,void,struct D3D10DDI_HDEVICE,struct D3D12DDIARG_CREATE_SHADER_0026 const *,struct D3D10DDI_HSHADER>::Call(class CDevice *,struct D3D10DDI_HDEVICE,struct D3D12DDIARG_CREATE_SHADER_0026 const *,struct D3D10DDI_HSHADER) Unknown
D3D12Core.dll!CShader::FinalConstruct(struct CShader::TConstructorArgs const &) Unknown
D3D12Core.dll!CLayeredObject<class CShader>::CreateInstance(struct CShader::TConstructorArgs const &,void *,void *,struct _GUID const &,void * *) Unknown
D3D12Core.dll!CDevice::CreateLayeredChild(unsigned int,void const *,unsigned int64,struct ID3D12LayeredUseCounted *,struct _GUID const &,void * *) Unknown
D3D12Core.dll!NDXGI::CDevice::CreateLayeredChild(unsigned int,void const *,unsigned int64,struct ID3D12LayeredUseCounted *,struct _GUID const &,void * *) Unknown
d3d12SDKLayers.dll!NDebug::CDeviceChild<struct ID3D12DeviceChild>::FinalConstruct(enum ED3D12DeviceChildType,struct SLayeredArgs const *,unsigned int64,unsigned int64,struct ID3D12LayeredUseCounted *,struct _GUID const &) Unknown
d3d12SDKLayers.dll!CLayeredObject<class NDebug::CShader>::CreateInstance(struct NDebug::CShader::TConstructorArgs const &,void *,void *,struct _GUID const &,void * *) Unknown
d3d12SDKLayers.dll!NDebug::CDevice::CreateLayeredChild(unsigned int,void const *,unsigned __int64,struct ID3D12LayeredUseCounted *,struct _GUID const &,void * *) Unknown
D3D12.dll!NOutermost::CDevice::CreateLayeredChild(unsigned int,void const *,unsigned __int64,struct ID3D12LayeredUseCounted *,struct _GUID const &,void * *) Unknown
d3d12SDKLayers.dll!NDebug::CDevice::CreatePatchedShader(struct ID3D12DeviceChild *,enum D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODE,bool) Unknown
d3d12SDKLayers.dll!<lambda>(void)() Unknown
d3d12SDKLayers.dll!NDebug::CDevice::CreatePatchedPipelineState(struct ID3D12PipelineState *,enum D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODE,bool) Unknown
d3d12SDKLayers.dll!NDebug::CGraphicsCommandList::GBVPatchPipelineState(struct ID3D12PipelineState * *,bool,bool) Unknown
d3d12SDKLayers.dll!NDebug::CGraphicsCommandList::SetPipelineState(struct ID3D12PipelineState *) Unknown
d3d12SDKLayers.dll!NDebug::CGraphicsCommandList::SetPipelineState(struct ID3D12PipelineState *) Unknown

**Comment by tex3d** [comment]
This issue is being closed for the following reasons:

This appears to be an issue with the size of GBV-modified DXIL that isn't (yet) known to be a regression from prior DXIL GBV, though it is clearly larger than the DXBC equivalent.  Unless it is a regression in GBV, or there is a more specific output pattern identified as a target for optimization in GBV, and without repro information, this issue is not actionable as-is for GBV.

If this is a regression in GBV from one version of SDKLayers to another (with the same DXIL input) please re-activate and provide details.

This isn't normally the forum for GBV issues, though we can forward those issues internally when closely related like this.

If you have a shader that demonstrates a problem with DXC output bloat (without GBV) where it is not expected, please open an issue on that and provide a repro so we may take a look.  If the repro cannot be shared publicly, you can email AskHLSL at microsoft dot com with the necessary details, which will go to the HLSL compiler team where we can keep your repro confidential.
