### ISSUE TITLE
Packing and unpacking for DirectX? 

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectXShaderCompiler#420]
Hello. Have HLSL packing functions for int16, int32, half, etc? For example, split 32 integer to two 16bit (include as 32-bit integer, but if hardware type, prefer native splitting) ? But very interesting unpacking and packing of 8bit and 16bit norm and unorms in HLSL. 

OpenGL spec:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shading_language_packing.txt

**Comment by capitalknew** [comment]
I also read here 

```
Future DXIL may add support for <2 x half> and <2 x i16> vectors or hints for packing related half and i16 quantities.
```

Hardly doing in DirectX with packing

**Comment by marcelolr** [comment]
Our first introduction of half ended up not using vectors in the IR. That keeps a class of types out from the representation, and it turns out that in practice backends were already doing some amount of work to recognize packing opportunities (if they had special instructions that could do better).

I expect we'll do the conversions as we add more of the smaller types - HLSL doesn't support 16-bit ints yet.

**Comment by devshgraphicsprogramming** [comment]
@ghost does this solve your issue?
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Pack_Unpack_Intrinsics.html

**Comment by damyanp** [comment]
Without feedback from original reporter we're not going to look any more into this.
