### ISSUE TITLE
[SPIR-V] RayQuery compilation error

### ISSUE THREAD

**Issue by a3YsM5jc** [microsoft/DirectXShaderCompiler#4221]
#### Description:
DXC fails to compile a compute shader with trace inline when SPIR-V codegen is enabled.
DXC successfully compiles the shaders into DXIL.

#### Compilation error:
> error: store value of type 'RayQuery<RAY_FLAG_SKIP_PROCEDURAL_PRIMITIVES | RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH>' is unsupported

#### Command line:
```
dxc.exe -DCOMPILER_DXC=1 -DVULKAN=1 -T cs_6_5 IndirectRays.cs.hlsl -Fo IndirectRays.cs.spirv -WX -O3 -spirv -fspv-target-env=vulkan1.2 -fspv-extension=SPV_EXT_descriptor_indexing -fspv-extension=SPV_KHR_ray_tracing -fspv-extension=SPV_KHR_ray_query
```
Attaching shaders: [shaders.zip](https://github.com/microsoft/DirectXShaderCompiler/files/7980039/shaders.zip)

I tried to use the latest version from github (v1.6.2112) and also the build from VulkanSDK, both builds print the same error.

**Comment by jaebaek** [comment]
@a3YsM5jc Thank you for reporting this issue. We will take a look.

**Comment by sudonatalie** [comment]
I'm not sure by which PR since there have been a few ray tracing improvements, but it looks like this issue has since been fixed. I'm able to repro the error with the DXC distributed with Vulkan SDK 1.2.182.0, but it now compiles successfully with the latest version from GitHub (`1.7(dev;3598-0ef9b702)`) and Vulkan SDK 1.3.216.0.
