### ISSUE TITLE
Provide attributes to control spilling of local variables

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#4291]
Relevant twitter thread: https://twitter.com/JasperBekkers/status/1494223540194844672

It's a fairly common performance bug that comes up, where someone creates a local array of values, and expects to be able to index into it. Usually this works fine, the compiler will unroll all necessary loops and jump through as much hoops as it can to facilitate this syntax. However, in some cases it needs to spill to global memory. Those cases typically are catastrophic for runtime performance.

In order to be more explicit about this intent, it would be really nice if HLSL could strictly annotate some of this so that the compiler can emit errors when variables get spilled accidentally. In the thread I suggest adding a `[spill]` and `[flatten]` attribute, that signify to the compiler exactly what the expectation here is.

Note that unlike the existing attributes such as `[unroll]`, I'm not suggesting this to be a hint to the driver. I know there is a bit of a back and forth here, and that typically drivers "decide" to spill. However, it would be preferable imho to be quite a bit more structured and strict where we can.

**Comment by llvm-beanz** [comment]
I'm not entirely sure how to handle this request, but I'm not sure what is actionable here.

The Twitter thread is actually referencing FXC and the issue is caused by a limitation in DXBC where only certain types of buffers can be dynamically indexed, and those buffers may result in spilling in the driver. That specific bug is unfixable here since it isn't in this codebase (although a similar issue is entirely plausible).

In terms of adding `[spill]`/`[flatten]` attributes, I'm not sure how we could implement this in any way other than as a hint to the driver. The frontend has no control over register allocation and thus spilling.

I'm happy to discuss this in more detail to understand the underlying issues to see if we can come up with an actionable solution.
