### ISSUE TITLE
I have got a compile error when include header file with utf-8 encoding

### ISSUE THREAD

**Issue by KawaharaKiyohara** [microsoft/DirectXShaderCompiler#4314]
I have got a compile error in hlsl which  has been happend by include header file with utf-8 without bom encoding.
Its error message is "Coulod not open XXXX.h".
But if encode of header file is native wide character( shift-jis ) or utf-8 with bom, preprocessor can have opend header file.
Please see its source code on cpp.

```cpp
// Create Blob From File
uint32_t codePage = CP_UTF8;
CComPtr< IDxcBlobEncoding> sourceBlob;
dxclib->CreateBlobFromFile(filePath, &codePage, &sourceBlob);

// Create DXC Compiler
CComPtr<IDxcCompiler> dxcCompiler;
DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(&dxcCompiler));

// Create include handler 
CComPtr< IDxcIncludeHandler> includerHandler;
dxclib->CreateIncludeHandler(&includerHandler);

// Create compile options.
std::vector<LPCWSTR> args;
args.push_back(L"-I");
args.push_back(L"\\Assets\\shader");
		
std::wstring filePathTmp = L".\\";
filePathTmp += filePath;

// Done Compile
CComPtr<IDxcOperationResult> result;
hr = dxcCompiler->Compile(
	sourceBlob,			// pSource
	filePathTmp.c_str(),	        // pSourceName
	L"",					// pEntryPoint
	L"lib_6_3",			// pTargetProfile
	args.data(),			// pArguments 
	args.size(),			// argCount
	nullptr, 0,				// pDefines, defineCount
	includerHandler,		// pIncludeHandler
	&result				// ppResult
);
```
Am I making a mistake in the compilation settings?
Please tell me why header file with utf-8 without bom encoding have got a compile error.

**Comment by tex3d** [comment]
Thanks for the report.  Can you share the version of the compiler you are using that reproduces this issue?

I think even the latest released version of the compiler has the issue where it may interpret include files using the application code page, rather than utf-8, by default.

In PR #4109, we made a change to allow the -encoding option to also set the default input encoding for files that lack a BOM.  We also made utf-8 the default, so we should no longer default to some non-unicode code page for reading source without BOM.  But these changes haven't yet made it it into our most recent release.

If you want to check to see whether these fixes work for your scenario, you can try the latest build of dxcompiler.dll from the artifacts zip file on AppVeyor here:
  - https://ci.appveyor.com/project/dnovillo/directxshadercompiler/build/job/jnov5ux2k1yuklo4/artifacts

Or via latest builds:
  - https://ci.appveyor.com/project/dnovillo/directxshadercompiler

Or through the checkmark beside a commit in master branch history: 
  - https://github.com/microsoft/DirectXShaderCompiler/commits/master
  - checkmark -> details for AppVeyor -> Image: Visual Studio 2019 -> Artifacts

Or build latest master branch yourself if you'd prefer.

Please re-open with more details if this issue doesn't appear to be fixed in recent builds from master.

**Comment by KawaharaKiyohara** [comment]
Thanks response.
I have used the compiler is included WindowsSDK(C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64).
I have try changed the version of compiler to latest,  the error of encoding was fixed.

But it happned new error in algorithm of shadowing in DXR.
Its algorithm is raytracing to light source.
Its algorithm is If the ray hits geometry, the lighting don't calculate.
Please see code of raytracing to light source.

```cpp
// raytracing to light source.
void TraceLightRay(inout RayPayload raypayload, float3 normal)
{
    float hitT = RayTCurrent();
    float3 rayDirW = WorldRayDirection();
    float3 rayOriginW = WorldRayOrigin();

    // Find the world-space hit position
    float3 posW = rayOriginW + hitT * rayDirW;

    RayDesc ray;
    ray.Origin = posW;
    ray.Direction = normalize(float3(0.5, 0.5, 0.2));
    ray.TMin = 0.01f;
    ray.TMax = 100;

    TraceRay(
        g_raytracingWorld,
        0,
        0xFF,
        1,	// No of hit group
        0,
        1,	// No of miss shader
        ray,
        raypayload
    );
}

[shader("closesthit")]
void shadowChs(inout RayPayload payload, in BuiltInTriangleIntersectionAttributes attribs)
{
    // set hit flag
    payload.hit = 1;
}

[shader("miss")]
void shadowMiss(inout RayPayload payload)
{
   // unset hit flag
   payload.hit = 0;
}
```
Look at the picture that was executed by shader that was builded by old compiler.The shadowing has been successful.
![shadow_old_version](https://user-images.githubusercontent.com/17634197/157169678-8d762a94-1735-4b1f-b591-abcf16b96b90.png)
But the shadowing which was executed by shader that was builded by latest compiler has been failed.
![shadow_latest_version](https://user-images.githubusercontent.com/17634197/157169695-23fa4522-af04-4032-8b9f-8691d09658f0.png)
I think shadowMiss and shadowChs function has not called by TraceRay function. Maybe this error was about invoked by no setting payload.hit to value.

(Numper of hitgroup is zero and numper of miss shader is zero has called.)
