### ISSUE TITLE
Potential Optimization with bundled compilation

### ISSUE THREAD

**Issue by JiayinCao** [microsoft/DirectXShaderCompiler#4353]
Hi,

Modern game engines commonly involve thusands of shader permutations if not more. As game developer, we've been working very hard trying to reduce shader compilation time so that we can have faster iteration, which means a lot to us. By us, I don't mean only programmers, it could have big impact on the workflow of other professions too.

However, most of the effort we've made are on the engine level, things like
- Avoid compiling invalid shader permutation during asset building pipeline
- Switch to dynamic branch whenever it doesn't hurt performance
- Distributed shader compilation on a build farm
- etc

I'm wondering if there could be any chances that things could be done on a lower level, the compiler.
To be more specific, for example, imagine we have two shader permutations, each of them may have ten thousand lines of code, but they are only one-line different from each other because of a different Macro setup.
The dxc compilation process would need to go through all the same workload once for each shader compilation process, which could have been shared to save some duplicated work if a set of target shader permutations, rather than just one single target shader permutation.

So rather than taking one input and generating one output file, it would be nice if there could be a way to take one input and different set of macros combinations for different permutations and do a bundled compilation so that the compiler has more chances to de-duplicate work.

This could be a valuable thing for the industry as everyone will benifit from faster shader compilation iterations.

Thanks

**Comment by llvm-beanz** [comment]
As described here there isn't really a solution inside the HLSL language. I have a draft PR that specifies HLSL's translation phases [here](https://github.com/microsoft/hlsl-specs/pull/19).

The important bits are that the pre-processor tokens are expanded to a preprocessed token sequence, then the preprocessed sequence is parsed to an AST. Having DXC permeate shaders based on macro definitions doesn't save time in practice because macros are resolved first in the compilation process, so you don't really save any effort.

We understand the problem with shader permutations. Some users with this problem can find improvements using library shaders. We also have a [request for specialization constants](https://github.com/microsoft/hlsl-specs/issues/71), and some ideas of our own to help address the issue.
