### ISSUE TITLE
The api ConvertInDriver's parameter  pInputSignature doesn't match the PFND3D10DDI_CREATEVERTEXSHADER call function's output

### ISSUE THREAD

**Issue by zhaoyue001** [microsoft/DirectXShaderCompiler#4386]
when use api ConvertInDriver to convert D3D10's DXBC code binary to DXIL online, ConvertInDriver will cast pInputSignature pointer into struct D3D12DDIARG_SIGNATURE_ENTRY_0012 which has 6  elements.But PFND3D10DDI_CREATEVERTEXSHADER call function outputs struct D3D10DDIARG_STAGE_IO_SIGNATURES,it's D3D10DDIARG_SIGNATURE_ENTRY only has 3 elements.How can I pass the IO signature to ConvertInDriver when missing the elements 'Stream RegisterComponmentType MinPrecision'?

**Comment by tex3d** [comment]
I think you need to supply sane values that take into account the limitations when that DDI are used.

Here's my recommendation:
- Use `0` for `Stream`
- Use `D3D11_SB_OPERAND_MIN_PRECISION_DEFAULT` for `MinPrecision`
- For `RegisterComponmentType`:
  - use `D3D_REGISTER_COMPONENT_UNKNOWN` if `SystemValue` is `D3D10_SB_NAME_UNDEFINED` (The converter will fill in the appropriate type)
  - otherwise, use `D3D10_SB_REGISTER_COMPONENT_FLOAT32`

**Comment by zhaoyue001** [comment]
thanks for your answers
