### ISSUE TITLE
Question: How do I use globallycoherant with unbounded texture arrays?

### ISSUE THREAD

**Issue by tomjohnstone** [microsoft/DirectXShaderCompiler#4430]
Hi,

Say I have an unbounded texture array like so that I'm using in a bindless renderer:

RWTexture2D<uint2> bindlessTextureUInt2 : register(u0, space10);

How do I use the globallycoherant markup when accessing a single texture from this array? Ie. I don't want it applied to all textures in the array.

Cheers,
Tom

**Comment by pow2clk** [comment]
Hi @tomjohnstone!

Unfortunately, there isn't a way to do this with the standard resource binding methods. However, it can be done with dynamic resource binding added in Shader Model 6.6. It would require some code refactoring on your part. 

You can get more detail from the blog post here: https://devblogs.microsoft.com/directx/in-the-works-hlsl-shader-model-6-6/#dynamic-resource-binding
The spec itself here: https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_DynamicResources.html
Or maybe even my presentation at GSL last year: https://youtu.be/lMU5P97K9Kk

**Comment by tomjohnstone** [comment]
So just to confirm would you have a separate array of descriptors marked as globallycoherant? Or in SM6.6 can you apply that modifier to local variable that you assign to the descriptor heap array? 

I can't seem to find any mention of globallcoherant in the links you posted.

Thanks,
Tom

**Comment by tex3d** [comment]
Dynamic Resources is a feature of SM 6.6 where you are able to directly index resource and sampler descriptor heaps and assign these to a local (or static global) resource variables.  You would no longer declare a resource array in HLSL.  The local resource variable would have the appropriate `globallycoherent` qualifier.

Here's an example:
```hlsl
// globallycoherent goes on local resource variable declaration.
// NonUniformResourceIndex (if needed) goes directly on index to built-in ResourceDescriptorHeap array.
globallycoherent RWByteAddressBuffer buf = ResourceDescriptorHeap[NonUniformResourceIndex(index)];
```

However, using this feature means changing the way you index these resources, since they will be indexed from the single descriptor heap base set on the command list, rather than a descriptor table base argument for the root signature.  So, depending on your use case, you may have additional index offset(s) you need to pass to the shader, potentially through a root constant, for example.  Plus, it's important that you set the root signature *after* the descriptor heaps are set on the command list.
