### ISSUE TITLE
compile error in type conversion

### ISSUE THREAD

**Issue by SJTU-Lucy** [microsoft/DirectXShaderCompiler#4563]
Hi! Here is roughly what I'm trying to compile from HLSL to SPIR-V using dxc. And I have marked the error below.
```
 struct VS_INPUT 
{
 float4 position : POSITION;
 float4 texcoord0 : TEXCOORD0;
 }
;
 struct PS_INPUT 
{
 float4 pos_screen : SV_Position;
 float2 uv;   // error here!
 }
;
 PS_INPUT vs_main(VS_INPUT input) 
{
 PS_INPUT output = (PS_INPUT) 0;
 float scale = float2 (1.0);   // error here!
 float offset = float2 (0.0);  // error here!
 float2 pos_xy = input.position.xy * scale + offset;
 output.pos_screen = float4 (pos_xy , input.position.z , 1.0);
 output.uv = input.texcoord0.xy;
 return output;
 }
 float4 ps_main(PS_INPUT input) : SV_Target0 
{
 float2 uv = input.uv;
 float4 color = t_tex0.Sample (s_tex0 , uv);
 float2 uv2 = uv * float2 (4.0 , 2.0);
 float3 uv3 = float3 (fmod (uv2 , 1.0) , floor (uv2.x));
 float4 value;
 if(u_state == 0) value = t_shadow1.Sample (s_shadow1 , uv3);
 else if(u_state == 1) value = t_height_map.Sample (s_height_map , uv3);
 else if(u_state == 2) value = t_tex2.Sample (s_tex2 , uv3).xxxx;
 else if(u_state == 3) value = t_tex3.Sample (s_tex3 , uv3).yyyy;
 return final;
 }
```
The Errors are:
1. error: too few elements in vector initialization (expected 2 elements, have 1)
2. error: semantic string missing for shader input variable 'uv'
The problem is that I can compile this with glslang without an error, so I wonder what's going wrong.
Are there any option parameters I could refer to?

Thanks!

**Comment by tex3d** [comment]
Both of these errors are legitimate errors in HLSL (whether or not glslang allows it).

1. `float2(1.0)` is an error because it is an attempt to initialize a float2 vector from a single scalar value.  While it is possible to do a splat to the vector, that is not supported by the float2(...) constructor syntax.  Furthermore, this `float2` vector will ultimately be assigned to a scalar `float`, so it's strange that it's `float2` in the first place.
2. All shader inputs and outputs must have semantics assigned in HLSL.  It doesn't matter what it is, since this is not a system value, you just need to put something unique there to identify the parameter in the pipeline, like: `float2 uv : uv;` would work.

**Comment by SJTU-Lucy** [comment]
Thank you very much!
