### ISSUE TITLE
Can I start compile using AST?

### ISSUE THREAD

**Issue by Jason-YJ** [microsoft/DirectXShaderCompiler#4657]
I want to call the compile function when starting with ast information.
I read code and found some function maybe useful for my need like "ASTUnit::LoadFromASTFile". But I don't know how to use it to change the current dxc pipeline. 
I found https://github.com/microsoft/DirectXShaderCompiler/issues/216 talked about transform ast to SPIR-V, unfortunately I only want to get dxil for d3d12.

**Comment by pow2clk** [comment]
Hello again @Jason-YJ!

Correct me if I'm wrong, but I think this bug is an individual form of were the discussion in #4632 ended up. As such, I refer you to my last comment there https://github.com/microsoft/DirectXShaderCompiler/issues/4632#issuecomment-1251513980 . I'm afraid this isn't something that the compiler supports. The use of AST to generate SPIRV is an internal implementation detail, not an exposed interface.

**Comment by Jason-YJ** [comment]
> Hello again @Jason-YJ!
> 
> Correct me if I'm wrong, but I think this bug is an individual form of were the discussion in #4632 ended up. As such, I refer you to my last comment there [#4632 (comment)](https://github.com/microsoft/DirectXShaderCompiler/issues/4632#issuecomment-1251513980) . I'm afraid this isn't something that the compiler supports. The use of AST to generate SPIRV is an internal implementation detail, not an exposed interface.

Thanks, but I'm not going to transform the ast to SPIR-V. What I need is to transform the ast to bytecode in d3d12, like DXIL.
