### ISSUE TITLE
Why support of compiling from ast discarded?

### ISSUE THREAD

**Issue by Jason-YJ** [microsoft/DirectXShaderCompiler#4681]
I found some interface for compiling from ast to dxil which were noted like following. I wonder if it still works cause I'm interested in compilation from my ast file to dxil bytecode.
![image](https://user-images.githubusercontent.com/71368398/191692683-8bd98563-82a7-4211-912b-41a2971a4168.png)

**Comment by llvm-beanz** [comment]
Clang's support for consuming serialized ASTs is used for precompiled headers and C++ modules, neither of which are features supported by HLSL.

AST serializations are also not stable across compiler versions, as such we don't want to support it as an interface since the support burden would be significant.
