### ISSUE TITLE
Is it possible to compile the same shader with different define configuration in one go?

### ISSUE THREAD

**Issue by alelievr** [microsoft/DirectXShaderCompiler#4697]
Hello,

In many game engines, there is a feature to compile a single shader multiple times with different define values or configuration (for example the [multi_compile](https://docs.unity3d.com/Manual/SL-MultipleProgramVariants.html) in Unity), this lead to the same shader being compiled 10 or 100 times with slight variation of code.

Currently, the step of generating all the variants of the shader file is done in the game engine and sent to the shader compiler separately. Would it be possible to move the step of generating all the needed combinations of defines inside the shader compiler to share a maximum of process between the output shaders?
I'm asking this because most of the time, the shader variants result in 95% of the same code and I think we'd gain quite a lot of time if we could share these steps between variants.

Here's an example with a simple HLSL shader:

```hlsl
#pragma multi_compile _ _USE_NORMAL_MAP

[shader("pixel")]
float4 main(float3 p : SV_POSITION, float2 uv : TEXCOORD0, float3 normal : TEXCOORD1) : SV_TARGET
{
#ifdef _USE_NORMAL_MAP
    normal  = ApplyNormalMap(normal, uv);
#endif

    return GetSurfaceColor(uv, normal);
}
```

This shader would result in two compiled fragment shaders: one with the call to `ApplyNormalMap` and one without

**Comment by pow2clk** [comment]
Hi @alelievr!

I'm afraid that the answer is technically yes, but it won't do what you hope it will. Defines are handled by the preprocessor which is the first thing the compiler does and doesn't take a lot of time. There isn't any common action that could be taken on the code that could remove any duplication of effort before the defines have to be finalized. It would take just as long to compile as it does when you invoke the compiler repeatedly now and you would have to use an interface that we designed instead of your own. In any case, all that interface would do would be the same thing that you are doing now, just down exactly one layer of abstraction. It doesn't seem like a good trade off.

**Comment by alelievr** [comment]
Thanks for the answer!

I understand that preprocessor resolving happens first in the compilation and it's unfortunate that we can't share more execution between shaders of similar structure.
Do you have any pointers on how to optimize shader compilation time? Or how to profile it correctly? Some of our shaders can take up to 15 seconds to compile and with the number of variants it can grow to dozen minutes very quickly.

**Comment by llvm-beanz** [comment]
DXC supports the `-ftime-profile` and `-ftime-trace` flags which can be useful for identifying where the compiler is spending time. There's a [great blog post](https://aras-p.info/blog/2019/01/16/time-trace-timeline-flame-chart-profiler-for-Clang/) about the `-ftime-trace` flag being used for Clang to optimize C++ compiles.

If you can't make progress on your own we can help if you can share the shaders with us. If you need to share them privately we can work out a way to do that.

Since there isn't direct action we can take on this issue, I'm going to close it. Please file a new issue if you have a concrete example for us to investigate or if you have further support needs.
