### ISSUE TITLE
[SPIR-V] attribute vk::image_format can't be used on arrays

### ISSUE THREAD

**Issue by TLaviron** [microsoft/DirectXShaderCompiler#4772]
The following shader:
```hlsl
[[vk::image_format("r11g11b10f")]] RWTexture2D<float3> uavs[2];

[numthreads(1,1,1)]
void maincomp(uint3 threadID : SV_DispatchThreadID)
{
	uavs[threadID.z][threadID.xy] = float3(0.5, 0.2, 1.0);
}
```
compiled with `dxc test_uav_format.hlsl -E maincomp -T cs_6_0 -spirv -Fo test_uav_format.comp.spv` fails with an error:
```
test_uav_format.hlsl:1:3: error: 'image_format' attribute only applies to RWTextures, Buffers and RWBuffers
```

If the `image_format` attribute is not used, the resulting SPIR-V is invalid; it breaks VUID-RuntimeSpirv-OpImageWrite-07112 (error reported by the Vulkan Validation Layers version 1.3.231.1).

**Comment by Keenuts** [comment]
Hi! Thanks for the report!

The validation error is because when not specified, the guessed type is RGBA32F. So we have 1 missing component on the source texel (3 floats, not 4). I guess we should fail to generate SPIR-V in such case, opening another issue to track this separately.

Looking at it, it seems the issue is not on the SPIR-V side, but before: DXC fails during the attribute validation phase. 
Reason is we check if the root type is a RWTexture2D, but the root type is a constant array:
(this was a known limitation looking at https://github.com/microsoft/DirectXShaderCompiler/commit/03cc4f866367d06a95bfe894a614827803e10d8b description)

Variable declaration node
```
VarDecl 0x555555a3a068 <repro.hlsl:1:36, col:62> col:56 uavs 'RWTexture2D<float3> [2]'
```

type declaration subtree
```
ConstantArrayType 0x555555a39ff0 'RWTexture2D<float3> [2]' 2
`-TemplateSpecializationType 0x555555a39f10 'RWTexture2D<float3>' sugar RWTexture2D
  |-TemplateArgument type 'float3':'vector<float, 3>'
  `-RecordType 0x555555a39ef0 'RWTexture2D<vector<float, 3> >'
    `-ClassTemplateSpecialization 0x555555a39de0 'RWTexture2D'
```

This works if you replace the array of RWTexture2D with a RWTexture2DArray.
Question that remains to be solved now: is there a reason not to support arrays for vk::image_format attributes?

**Comment by TLaviron** [comment]
Thanks for the reply
> This works if you replace the array of RWTexture2D with a RWTexture2DArray.

Unfortunately in the actual use case I have, the multiple `RWTexture2D`s have different dimensions, so I can't just merge them into a single `RWTexture2DArray`.
I'll have to wait for either the ability to use this attribute on arrays of resources, or by having the format default to `unknown` instead, with the appropriate `StorageImageReadWithoutFormat`/`StorageImageWriteWithoutFormat` capabilities enabled.

**Comment by s-perron** [comment]
This looks like it is working with the latest DXC: https://godbolt.org/z/qMx7xjYG9. Is there anything else that is expected?
