### ISSUE TITLE
Function Pointers in HLSL

### ISSUE THREAD

**Issue by sileom-dev** [microsoft/DirectXShaderCompiler#4777]
Hello -- Is there a way of using something like function pointers in HLSL compute kernels?  I couldn't find anything in the documentation.  I'm porting an application currently written in Metal which uses visible function tables to achieve what I'm attempting to do here.  Thanks much!

**Comment by devshgraphicsprogramming** [comment]
I think https://github.com/microsoft/hlsl-specs would be correct repo for this feature request.

But yeah the proper way to support this with a polyfill would be for the compiler to build a visible function table for every signature, then emit a "dispatcher" which would be used in-place of every function call from a pointer.

No in-situ switches though, because that would ruin perf on GPUs with separable program counters or ones that have a choice whether to inline a function call or not.

Ideally DXIL should support it itself and then correct RDNA ISA or Nvidia PTX would be emitted by their respective drivers (because  for example Nvidia can do actual function calls since what seems like forever).
