### ISSUE TITLE
[SPIRV-V] Dynamic Resource Binding for SPIR-V

### ISSUE THREAD

**Issue by deceased-a** [microsoft/DirectXShaderCompiler#4824]
I have no exact idea for `ResourceDescriptorHeap` and `SamplerDescriptorHeap`, but I thinking about add such decorators. And make it editable as buffers. Add also `UniformDescriptorHeap` and variable named descriptor heaps. In Vulkan API and SPIR-V we have descriptor buffer and mutable descriptor types. Also, I would to propose add variable stride in layout specifier (include such as `custom.srv_stride`, imported from Vulkan properties).

```hlsl
// Because these names already is busy
<layout(set=0, stride=8) ResourceDescriptorHeap>
<layout(set=1) SamplerDescriptorHeap>
```

```hlsl
ResourceDescriptorHeap[x] = AnotherDescriptorHeap[x];
```

Also, I propose to add definitions: `#ifdef SPIR_V` and `#ifdef DXIL` for specific coding for targets.

**Comment by pow2clk** [comment]
Hi @unit-a-user! 

Wow. This is a lot in very few words. It's really several distinct issues. I'm going to declare that this bug is for adding SPIRV support for the descriptor buffer extension(s). I'll address the others here briefly, but please file separate bugs for them so we can track each issue indpendently.

1. Add `UniformDescriptorHeap`. I think in HLSL-speak this would be `ConstantBufferHeap`? Please file a separate bug and give us more detail.
2. Variable stride in layout specifier. It's an interesting proposal. Can you explain, in a separate bug how this would be useful to you?
3. `ResourceDescriptorHeap[x] = AnotherDescriptorHeap[x]` I'm unsure if this is supported by Vulkan. Is it? I'd also be interested to see a separate bug explaining how this is useful. You can create an array of resource types, but of course they wouldn't have the generic descriptor type that the built in arrays have.
4. Add definitions `#ifdef SPIR_V` and `#ifdef DXIL`. There is already a define `__spirv__` that you can use to conditionalize code meant only for spirv. We should probably add a __dxil__ equivalent. Please file a bug for that.

**Comment by s-perron** [comment]
This does not give me enough to go on. However, this type of change should go through [HLSL specs](https://github.com/microsoft/hlsl-specs). This seems like a significant language change.
