### ISSUE TITLE
Bad error string format when a debugger is attached

### ISSUE THREAD

**Issue by poulpi** [microsoft/DirectXShaderCompiler#5096]
Hello,

We have an issue with the error format returned when a debugger is attached.

If there is no debuger attached, the error is returned with the following format:
`shader.hlsl(16,15): error GE5E59682: invalid format for vector swizzle 'u'`
And when a debugger is attached, the result is:
`shader.hlsl:16:15: error: invalid format for vector swizzle 'u'`

The second one make debugging difficult as double click on it will takes you to the start of the file instead of the correct line.
We are using using DXCompiler from December 2022 release, and Visual Studio 2019 (16.11.24).

**Comment by neversleeping** [comment]
Looks like this problem has the same roots as
https://github.com/microsoft/DirectXShaderCompiler/issues/2705#issue-567819892
That issue was closed, but not actually resolved.
I'm compiling shaders directly from a command line this:
`dxc.exe -flegacy-macro-expansion -HV 2021  -T cs_6_0 -E visibility -I includes_dir source.hlsl -Fc compiler_output.asm -Zi -Qembed_debug`
and I'm always getting errors in format "file:line:column:".
I was trying to use multiple DXC releases and even build main branch - I never got a format with braces. HLSL compilation in Visual Studio 2022 returns errors in a format "file(line,column):", but I found no way to reproduce the same output from a command line.

**Comment by llvm-beanz** [comment]
I think the bug is Visual Studio not handling Clang's diagnostic formatting correctly.

We're not going to change how DXC outputs these because we'd immediately regress when we move to Clang as our default HLSL compiler.

**Comment by Kosmokleaner** [comment]
I have the same issue and would love to get the fix.

> We're not going to change how DXC outputs these because we'd immediately regress when we move to Clang as our default HLSL compiler.

If you make the change it would be easy as command line options. The same command line option can be added to clang as one of  you first contributions that would be useful for others too. So I don't see this as an argument. Once you switch to clang you are expected to help improving this code as well. The change can also be be in parallel, no need to wait for the clang change to propagate. 

Thanks
