### ISSUE TITLE
llvm assert in CodeGen with templated resource argument defaulted to ResourceDescriptorHeap element

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#5145]
llvm assert in CodeGen with templated resource argument defaulted to ResourceDescriptorHeap element.

Requires that the resource type has not yet been instantiated.  For instance, if you use `Texture2D<float4>` before the instantiation, it succeeds.

Found when testing fix for issue #5139, but this is a separate issue.

```hlsl
// RUN: %dxc -T vs_6_6 -HV 2021
template<typename T>
void foo(Texture2D<vector<T, 4> > tex = ResourceDescriptorHeap[0]) {}
// Texture2D<float4> Tex; // If you uncomment this line, it will no longer assert.  But it must precede the instantiation in main()
void main() {
  foo<float>();
}
```

The assert:
```cpp
  assert(D && "Cannot get layout of forward declarations!");
```

When retrieving layout of this RecordDecl:
```cpp
ClassTemplateSpecializationDecl 0x2c4866bc3f8 <<invalid sloc>> <invalid sloc> class Texture2D
`-TemplateArgument type 'vector<float, 4>'
```

In `ASTContext::getASTRecordLayout`, `D = D->getDefinition();` results in nullptr because the type has not yet been defined.  Preceding this is:
```cpp
  if (D->hasExternalLexicalStorage() && !D->getDefinition())
    getExternalSource()->CompleteType(const_cast<RecordDecl*>(D));
```
But this type does not return true for `hasExternalLexicalStorage()`.  Should we be using this mechanism to instantiate built-in template specializations?

**Comment by pow2clk** [comment]
assert is gone, but the shader still fails to compile

**Comment by pow2clk** [comment]
@llvm-beanz to triage and advise

**Comment by llvm-beanz** [comment]
I think I may have a somewhat hacky fix for this. The core problem is that the HLSL implicit conversion sequence code doesn't force the target type to be complete. We get lucky in most cases because expressions are pretty robust at forcing their types to be complete.

This code hits a particularly odd edge case where an incomplete type is assigned to another incomplete type and the `hlsl::CanConvert` function allows the conversion without forcing either type to be complete.

**Comment by llvm-beanz** [comment]
Okay... I think I get what is going on here. This is a different manifestation of this upstream bug:
https://github.com/llvm/llvm-project/issues/49178

Basically the default argument doesn't ever get template instantiated and as a result the template-dependent type parameter doesn't get instantiated.

I don't know if the upstream fix will back port, but I'll give that a stab since I think it is the right approach.
