### ISSUE TITLE
[Question] Why is `getMainBufferWithPrecompiledPreamble` disabled?

### ISSUE THREAD

**Issue by jeremyong** [microsoft/DirectXShaderCompiler#5230]
Refer to the code here: https://github.com/microsoft/DirectXShaderCompiler/blame/cea4142fc1a5fda7a6a3e85c06e7eb6897da15b3/tools/clang/lib/Frontend/ASTUnit.cpp#L1375

This function appears to have been disabled since the initial commit 7 years ago, but it reduces the usefulness of the `IDxcIsense` `Reparse` functionality. My understanding is that the preamble is not a PCH per se, but the collection of headers included at the top of a translation unit. This is cached where possible (e.g. no errors encountered, only warnings), and reused on re-parse to facilitate faster code complete and such. The comment here suggests that the code is disabled because "no support for PCH" but I'm curious if there is a different reason.

**Comment by llvm-beanz** [comment]
The big issue here is that DXC didn't maintain any of the infrastructure for serializing ASTs to bitcode. I _think_ that decision was made because DXC doesn't support precompiled headers, but it has compounded. I'm unsure if any of the HLSL-specific AST nodes have ever been written to support serialization, and I'm sure they've never been tested.

Preamble headers are precompiled headers, they're just subtly different in how they are used from the API perspective because they are geared toward IDE/Tooling usage rather than compile-time usage. The Clang docs on [PCH internals](https://clang.llvm.org/docs/PCHInternals.html) are pretty accurate and useful to understand how these things all come together.

**Comment by llvm-beanz** [comment]
@jeremyong, since I don't think there's anything else for our team to do here, I'm going to close this out. If you need anything else please reach out.
