### ISSUE TITLE
`static` global variables with attached system semantics compile but silently ignore semantics

### ISSUE THREAD

**Issue by jeremyong** [microsoft/DirectXShaderCompiler#5280]
Absent a spec, I wasn't sure what the intended behavior should be, but declarations such as:

```hlsl
static float4 position : SV_Position;
static uint iid : SV_InstanceID;
```
and so forth in the global scope are all 0 initialized (as with other static declarations). The semantic is ignored as far as I can tell, but the code appears to compile, despite the semantics being dropped. Would it make sense to either:

1. Emit a warning/error indicating that the semantic is unused
2. OR (possibly with a flag), emit an initializer that loads from the expected input registers and attempt to actually respect the semantic

Thanks!

**Comment by llvm-beanz** [comment]
Not that I think we need it, but here's a [godbolt example](https://godbolt.org/z/qqcG3z97f).

I think this is somewhat related to #2448 in that they both are insufficient verification/annotation of semantics.

I'd like @tex3d to weigh in on the specifics of what we can do here. I know that semantics being quietly ignored in some cases when they are not valid is the expected and correct behavior. This seems likely to be a case where we could issue a diagnostic since these will always be ignored.

Leaving as untriaged until @tex3d can chime in.

**Comment by jeremyong** [comment]
Yup thanks, I mentioned this issue because I think it's a common beginner trap for users that transition from GLSL to HLSL (noticed this question pop up in forums/discord a couple times).

**Comment by pow2clk** [comment]
These are left over from Effects. They are ignored and should have a warning saying as much like some similar left over language features are. We'll likely turn that to an error in a later language version.

**Comment by pow2clk** [comment]
Closing as we'll be fixing this as part of the clang issue https://github.com/llvm/llvm-project/issues/95150

@Tex3d, to weigh in if there's anything else we should be considering
