### ISSUE TITLE
Feature request, combinedImageSamplers for single sampler & multiple textures

### ISSUE THREAD

**Issue by kirill146** [microsoft/DirectXShaderCompiler#5341]
To create multiple combined image samplers we have to make N textures and N samplers even if these samplers are the same. For SPIR-V path it means just more verbose code since SamplerStates are compiled out; for DXIL though resource slots are wasted. It would be nice to support 1:N relationships. Something like
```hlsl
[[vk::combinedImageSampler, vk::binding(0)]] Texture2D diffuseTex;
[[vk::combinedImageSampler, vk::binding(1)]] Texture2D normalTex;
[[vk::combinedImageSampler, vk::binding(0), vk::binding(1)]] SamplerState commonSampler;
```

**Comment by s-perron** [comment]
We will not be implementing this feature. It will help because it provides a little syntactic sugar, but it will create a very large complication in the compiler. This essentially creates a single name to reference two different variable. It will be difficult for the compiler to which variable is being referred to. In some cases, it might even be impossible.  For example:


```
[[vk::combinedImageSampler, vk::binding(0)]] Texture2D diffuseTex;
[[vk::combinedImageSampler, vk::binding(1)]] Texture2D normalTex;
[[vk::combinedImageSampler, vk::binding(0), vk::binding(1)]] SamplerState commonSampler;

struct PixelInput
{
    float4 position : SV_POSITION;
    float2 uv : TEXCOORD0;
};

float4 func(Texture2D tex, PixelInput input) {
  return tex.Sample(commonSampler, input.uv); // We cannot know this commonSampler to use. Binding 0 or binding 1?
}

float4 main(PixelInput input) : SV_Target
{
    return func(diffuseTex, input) + func(normalTex, input);
}
```
