### ISSUE TITLE
[SPIRV] Type of PerVertexKHR inputs.

### ISSUE THREAD

**Issue by ShchchowAMD** [microsoft/DirectXShaderCompiler#5383]
Hi, @s-perron 

I have some corner case questions when refining PervertesKHR decorated inputs dealers.

**1. Local Variable**
```
enum VertexID {
    FIRST = 0,
    SECOND = 1,
    THIRD = 2
};
struct PSInput
{
    int color2 : COLOR2;
    nointerpolation float3 Color : COLOR11;
};

PSInput main(PSInput input) : SV_Target
{
    PSInput test;
    test.color2 = 1;
    test.Color = input.Color;
    test.Color += GetAttributeAtVertex( input.Color, VertexID::THIRD );
    return test;
}
```
From previous example, should test.Color be treated as test.Color[0] too?

Local variable 'test' have same type with 'input'. DXC would reports a warning ' warning: internal semantic 'COLOR11' overridden by enclosing semantic 'SV_Target'' for this usage, but seems this is allowed.

**2. Is it allowed to remove some instructions from their basic block?**

When stage input has a bool type, spvEmitter added some binary op like OpINotEqual to let stage inputs be converted from unit to bool type before passed to a functionCall.

If 'nointerpolation' inputs' types are changed to an array, Spiv won't allow the result type or operands' types of OpINotEqual to be an bool array.

I remove this bool case binary op and replace with a directly load, but not make sure this is a correct way (please see around instruction %38):

```
enum VertexID {
    FIRST = 0,
    SECOND = 1,
    THIRD = 2
};

struct PSInput
{
    int color2 : COLOR2;
    nointerpolation bool3 Color : COLOR11;
};

bool3 main(PSInput input) : SV_Target
{
    bool3 vColor0 = input.Color;
    bool3 vColor1 = GetAttributeAtVertex( input.Color, VertexID::THIRD );
    bool3 vColor2 = input.Color;
    bool3 vColor3 = GetAttributeAtVertex( input.Color, VertexID::SECOND );
    return bool3(vColor0.x && vColor1.y, vColor2.y, vColor3.z);
}

; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 84
; Schema: 0
              ..............
               OpDecorate %in_var_COLOR2 Flat
               OpDecorate %in_var_COLOR11 PerVertexKHR
               OpDecorate %in_var_COLOR11 Flat
               OpDecorate %in_var_COLOR2 Location 0
               OpDecorate %in_var_COLOR11 Location 1
               OpDecorate %out_var_SV_Target Location 0
              ..............
    %PSInput = OpTypeStruct %int %_arr_v3uint_uint_3
             ..............
%in_var_COLOR2 = OpVariable %_ptr_Input_int Input
%in_var_COLOR11 = OpVariable %_ptr_Input__arr_v3uint_uint_3 Input
%out_var_SV_Target = OpVariable %_ptr_Output_v3uint Output
       %main = OpFunction %void None %32
         %33 = OpLabel
%param_var_input = OpVariable %_ptr_Function_PSInput Function
         %37 = OpLoad %int %in_var_COLOR2
        ;;;;;; There was a EOpINotEqual %bool3 %in_var_COLOR11 %v3uint_1 here ;;;;;;
         %38 = OpLoad %_arr_v3uint_uint_3 %in_var_COLOR11
         %39 = OpCompositeConstruct %PSInput %37 %38
               OpStore %param_var_input %39
         %42 = OpFunctionCall %v3bool %src_main %param_var_input
         %44 = OpSelect %v3uint %42 %14 %12
               OpStore %out_var_SV_Target %44
               OpReturn
               OpFunctionEnd
   %src_main = OpFunction %v3bool None %45
      %input = OpFunctionParameter %_ptr_Function_PSInput
   %bb_entry = OpLabel
    %vColor0 = OpVariable %_ptr_Function_v3bool Function
    %vColor1 = OpVariable %_ptr_Function_v3bool Function
      %_Vtx0 = OpVariable %_ptr_Function_v3bool Function
    %vColor2 = OpVariable %_ptr_Function_v3bool Function
    %vColor3 = OpVariable %_ptr_Function_v3bool Function
         %55 = OpAccessChain %_ptr_Function__arr_v3uint_uint_3 %input %int_1
         %57 = OpAccessChain %_ptr_Function_v3uint %55 %uint_0
         %58 = OpLoad %v3uint %57
         %59 = OpINotEqual %v3bool %58 %12
               OpStore %_Vtx0 %59
         ....
               OpReturnValue %83
               OpFunctionEnd
```

**Comment by s-perron** [comment]
The best way to figure these out is to look at the DXIL that is generated. For 1, you can look at https://godbolt.org/z/cbnG3Pdo7.

The important instructions are:

```
  # Load the input at the porvoking vertex.
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 1, i32 0, i8 0, i32 undef), !dbg !46 ; line:12 col:22  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  # Load the input at the third vertex.
  %4 = call float @dx.op.attributeAtVertex.f32(i32 137, i32 1, i32 0, i8 0, i8 2), !dbg !53 ; line:17 col:19  ; AttributeAtVertex(inputSigId,inputRowIndex,inputColIndex,VertexID)
  # Add them together.
  %5 = fadd fast float %1, %4, !dbg !54 ; line:17 col:16
```

I think this shows that, yes, `test.Color` should be treated as test.Color[0] too.

We should also have a test where GetAttributeVertex is called on `test.Color` instead of `input.Color`.

```
enum VertexID {
    FIRST = 0,
    SECOND = 1,
    THIRD = 2
};
struct PSInput
{
    int color2 : COLOR2;
    nointerpolation float Color : COLOR11;
};

PSInput main(PSInput input) : SV_Target
{
    PSInput test;
    test.color2 = 1;
    test.Color = input.Color;
    test.Color += GetAttributeAtVertex( test.Color, VertexID::THIRD );
    return test;
}
```

**Comment by s-perron** [comment]
For 2, I would prefer if the compare instruction was placed in `%main` and not in `%src_main`. That is because we should try to minimize special cases. The current handling of `bool` is to make the interface of `%src_main` match the HLSL function. That is the input is a bool. If you break that convention, the code become less predictable, and another DXC developer will just have to know what is going on, and how to correctly use the variable.

> Spiv won't allow the result type or operands' types of OpINotEqual to be an bool array

You can load each element, do individual compares, and then construct the bool array. The optimizer should remove any loads that are not used.

**Comment by ShchchowAMD** [comment]
Thanks for your reply! I think above questions now have a solution.

Another case I met during local debugging is:

```
enum VertexID {
    FIRST = 0,
    SECOND = 1,
    THIRD = 2
};


struct PSInput
{
    int i : COLOR0;
    nointerpolation float3 Color : COLOR1;
};

struct testStructure
{
    nointerpolation float3 Color : COLOR4;
};


float3 t2(nointerpolation float3 Color){
  testStructure chainEndVal;
  chainEndVal.Color = Color;
  float3 k = GetAttributeAtVertex(Color, 1) + chainEndVal.Color;
  return k;
}

float3 t3(nointerpolation float3 Color){
  return t2(Color);
}


float3 main(nointerpolation float3 Color : COLOR) : SV_Target
{
    float3 v = t3(Color);
    return v;
}
```

I found following questions:

1. It is not legal to decorate 'nointerpolation' to a local variable in DXC, like : `nointerpolation float3 chainEndVal;`:
`error: 'nointerpolation' is not a valid modifier for a local variable`

In stead, it is still legal to declare it within a structure type like above.

But I also find `nointerpolation float3 chainEndVal;` is legal in FXC, is this expected?

2. I found there's a statement in SV_BaryCentrics like:

`Implementations are required to preserve all bits in the binary representation of such attributes through the VS/DS/GS-to-PS interface – so that applications can treat them essentially as sets of 32-bit bitfields with application-specific interpretation.`

So this means the first parameter of GetAttributeAtVertex() should directly from the PS inputs (like, only used in src_main)?

Or, it is ok after checking the call chain and make sure it is only from a PS input, like above example, even its a function local variable?

I think following usage should be wrong (vtx1 and vtx2 is undefined)?

```
float3 t2(nointerpolation float3 Color){
  testStructure chainEndVal;
  chainEndVal.Color = float3(0.1, 0.1, 0.1);
  float3 ret = GetAttributeAtVertex(chainEndVal.Color, 1) + Color;
  return ret;
}
```

**Comment by ShchchowAMD** [comment]
I found its definition as following, so the first parameter can only be an stg input?

```
<attributeType> GetAttributeAtVertex( nointerpolation <attributeType> attribute,
                                                                  uint VertexID );
```

**Comment by s-perron** [comment]
This seems to be a case where the DXIL backend does some legalization. That is, a program is considered valid or legal based on what the code looks like or would look like after being optimized.

To simplify our code, I would like to have the FE issue more errors, but we will have to run that past the DXIL backend developers. I want our behaviour to match DXIL, and we do not want to remove functionality that HLSL developers use.

@llvm-beanz Do you have an thoughts on this? Should DXC issue a parsing error if someone tries to assign a value that does not have the `nointerpolation` modifier to a variable that does?  So the follow would be an error regardless of what `t3` does with the `Color`.

```
float3 t3(nointerpolation float3 Color);

float3 main(nointerpolation float3 Color : COLOR) : SV_Target
{
    return t3(float3(0.2, 0.1, 0.0));
}
```

The same for

```
struct testStructure
{
    nointerpolation float3 Color : COLOR4;
};

float3 main(nointerpolation float3 Color : COLOR) : SV_Target
{
    testStructure t;
    t.Color = float3(0.2, 0.1, 0.0);
    ...
}
```

DXC currently issues an error if `Color` is used in `GetAttributeAtVertex`, but not otherwise.


@ShchchowAMD This will be ugly. For now,  here are my thoughts on how we can match the current DXIL behaviour:

> In stead, it is still legal to declare it within a structure type like above.

Yes it is still "legal", even if it seems inconsistent. Simply because there is no error with the DXIL backend.

> So this means the first parameter of GetAttributeAtVertex() should directly from the PS inputs (like, only used in src_main)?

Correct, but that need only be true after optimization, which we cannot check properly in SPIR-V because the call to get `GetAttributeAtVertex` is turned into an array reference. So we will have to be more premissive than DXIL in this case.

I would convert all non-external, `nointerpolation` variables into arrays. Assignments between two symbols that are not `nointerpolation` should be treated as accessing just the provoking vertex of the `nointerpolation` variable.

```
float3 c;
chainEndVal.Color = c;
```

becomes the equivalent of 

```
chainEndVal.Color[0] = c;
```

**Comment by ShchchowAMD** [comment]
Thanks for advice!

A new case is:

```
struct testStructure
{
    nointerpolation float3 Color : COLOR4;
};

float3 t2(nointerpolation float3 Color){
  testStructure chainEndVal;
  chainEndVal.Color = Color;
  float3 ret = GetAttributeAtVertex(chainEndVal.Color, 1);
  return ret;
}

float3 main(nointerpolation float3 Color1 : COLOR,
nointerpolation float3 Color2 : COLOR2) : SV_Target
{
    float3 v = t2(Color1);
    testStructure mainLocal;
    mainLocal.Color = Color2;
    return v;
}
```

If I understand right, only `Color1` would be converted into an array and decorated with `PerVertexKHR`, not `Color2`, right?

**Comment by ShchchowAMD** [comment]
I think the question is:

spirv decorator `PerVertexKHR` is not fully mapping to `nointerpolation` in HLSL.

We could only make sure that we should add this decorator to an input variable when it is finally used in `GetAttributeAtVertex`?

**Comment by ShchchowAMD** [comment]
Thanks. I'll convert nointerpolated variables into an array.

**Comment by ShchchowAMD** [comment]
> If we see it makes a difference and we want to optimize, we can add a pass to spirv-opt that remove the PerVertexKHR decoration, and makes other appropriate changes, if the pass sees that only element 0 is referenced.

This would make the code simple. For variables only use element 0, opt could change them back to a non-array and remove its PerVertexKHR decorator.
