### ISSUE TITLE
[DXIL] Add a dxil op for IndexNodeRecordHandle

### ISSUE THREAD

**Issue by bob80905** [microsoft/DirectXShaderCompiler#5435]
**Is your feature request related to a problem? Please describe.**
Validation can't be added to the IndexNodeRecordHandle intrinsic because no dxil opcode exists for that intrinsic

**Describe the solution you'd like**
IndexNodeRecordHandle should be assigned a dxil opcode so that the intrinsic (semantics, arguments, etc) can be validated. I think the entry should be added to DxilConstants.h.

**Comment by tex3d** [comment]
There's no opcode for `IndexNodeRecordHandle` because this intrinsic doesn't exist anymore.  So no validation is necessary for this operation, since the operation doesn't exist.

DXIL ops are described in hctdb.py, which generates the `DXIL::OpCode` and `DXIL::OpCodeClass` enums, as well as a bunch of other stuff.  Those enums in `DxilConstants.h` are generated, not meant to be hand-edited.
