### ISSUE TITLE
[SPIR-V] Compile failure Interlocked*() functions with output a struct member

### ISSUE THREAD

**Issue by jbright282** [microsoft/DirectXShaderCompiler#5772]
**Description**

Interlocked*() functions with the out parameter as part of struct fail to compile for SPIR-V

**Steps to Reproduce**

Example Shader
```
groupshared uint lds;

struct Struct
{
    uint member;
};

[numthreads(64, 1, 1)]
void main()
{
    Struct s;
    InterlockedAdd(lds, 1, s.member);
}
```

Error:

**Actual Behavior**
```
error: InterlockedCompareExchange requires a reference as output parameter
    InterlockedAdd(lds, 1, s.member);
```
Compiles correctly for DXIL.  Failure is only SPIRV.

**Environment**
- DXC version  1.7 - 1.7.0.4123 (8c201e0bd) (head)
- Host Operating System Win10

**Comment by s-perron** [comment]
I tried this on Linux with the command `dxc -T cs_6_6 t.hlsl -spirv -E main`. 

The generated code looks correct as well. Before optimization we have

```
          %s = OpVariable %_ptr_Function_Struct Function
         %18 = OpAtomicIAdd %uint %lds %uint_1 %uint_0 %uint_1
         %20 = OpAccessChain %_ptr_Function_uint %s %int_0
               OpStore %20 %18
```

The store to `%s` is removed by optimization because the value is never used, which is also correct.

Reopen if you are still able to reproduce, and provide the command line that is used. In the meantime, I'll try to reproduce on Windows in case that make a difference.

**Comment by s-perron** [comment]
I was able to reproduce using the latest prebuilt binaries on windows.

**Comment by s-perron** [comment]
This is regression caused by #5661.

**Comment by Keenuts** [comment]
Hi! Thanks, taking a look now.

**Comment by Keenuts** [comment]
Looks like I overlooked that underlying VarDecl could be wrapped into other expressions (array, member, etc).

But the fix seems a bit more complex:
the compiler handles output parameters a bit weirdly.

```hlsl
int variable;
InterlockedAdd(lds, 1, variable)
```

the variable is passed "by copy" from the AST perspective, but we do lower it correctly to some kind of reference (not a real ref, because HLSL).

But now, if I do the following:

```hlsl
RWStructuredBuffer<uint> buffer;
InterlockedAdd(lds, 1, buffer[0]);
```

Then, I get a FunctionCall expression as input. And the return type is indeed an l-value reference.
I'll see if adding this particular edge-case feels OK, because right now, I feel like I'm piling up weird heuristics
