### ISSUE TITLE
[SPIR-V] using 64bit image causes fatal error of dxc

### ISSUE THREAD

**Issue by YangGraphics** [microsoft/DirectXShaderCompiler#5955]
**Description**

using 64bit image causes fatal error of dxc

**Steps to Reproduce**

the HLSL code:
```
[[vk::binding(0, 0)]] [[vk::image_format("r64ui")]] RWTexture2D<uint> myImage;



[numthreads(64, 1, 1)]
void main(uint3 ThreadID: SV_DispatchThreadID)
{
    myImage[uint2(1,1)] = 1;
}
```
my command: 

```dxc.exe -HV 2021 -spirv -T cs_6_6 -E main mycode.comp.hlsl -Fo mycode.comp.hlsl.spv -fspv-extension=SPV_EXT_shader_image_int64```

or

```dxc.exe -HV 2021 -spirv -T cs_6_6 -E main mycode.comp.hlsl -Fo mycode.comp.hlsl.spv```

**Actual Behavior**

the error output:
fatal error: generated SPIR-V is invalid: Operand 8 of TypeImage requires one of these capabilities: Int64ImageEXT 
  %type_2d_image = OpTypeImage %uint 2D 2 0 0 2 R64ui

**Environment**
- DXC version v1.7.2308
- Host Operating System <windows 10 22H2>

**Comment by sudonatalie** [comment]
Looks like we just missed a case in the CapabilityVisitor. @s-perron Can you take a look at this?

**Comment by devshgraphicsprogramming** [comment]
@YangGraphics if you add `[[vk::ext_capability(5016)]]` either above the declaration of `myImage` or `main` does it get rid of the error?

P.S. I'd expect the image to be declared with `RWTexture2D<uint64_t>` and `operator[](uint64_t)` though!?

**Comment by YangGraphics** [comment]
@devshgraphicsprogramming  

Many Thanks!

changes to ```RWTexture2D<uint64_t>``` does work. So I guess the error information isn't accurate

**Comment by devshgraphicsprogramming** [comment]
> So I guess the error information isn't accurate

I guess so, usually for a vulkan extension, DXC isn't really under an obligation to support those. But in this case someone obviously wrote the codegen so it seems like DXC is supposed to support this extension.

I'd still take a look if I were you and see what SPIR-V is emitted because you need OpExtension and OpCapability being emitted correctly at the top of your shader.
```

               OpCapability Int64ImageEXT
               OpExtension "SPV_EXT_shader_image_int64"
```

**Comment by s-perron** [comment]
Yes, the code you generated was not valid because the type in the sampled type has to be a 64-bit value. You can see the requirements [here](https://docs.vulkan.org/spec/latest/appendices/spirvenv.html#spirvenv-format-type-matching).

However, the error you are seeing is not very informative. DXC does not do any error checking between the `vk::image_format` and the sampled type. I'll look into whether or not that is something that is reasonable to do.

**Comment by s-perron** [comment]
> > So I guess the error information isn't accurate
> 
> I guess so, usually for a vulkan extension, DXC isn't really under an obligation to support those. But in this case someone obviously wrote the codegen so it seems like DXC is supposed to support this extension.
> 
> I'd still take a look if I were you and see what SPIR-V is emitted because you need OpExtension and OpCapability being emitted correctly at the top of your shader.
> 
> ```
> 
>                OpCapability Int64ImageEXT
>                OpExtension "SPV_EXT_shader_image_int64"
> ```

You can see the generated spir-v at https://godbolt.org/z/78TvabGjv. You are correct that getting the exact minimal set of capabilities is sometimes hard.
