### ISSUE TITLE
cbuffer name redefine as warning or error

### ISSUE THREAD

**Issue by dodoleon** [microsoft/DirectXShaderCompiler#6007]
This is my test code. The name of cbuffer "A" is redefined. But there is no warning or error for Compiling this code.
Is there any option to open it? 
BTW why it is ok for cbuffer A redefined?
```
struct PSInput
{
	float4 color : COLOR;
};

cbuffer A
{
    float a;
}

cbuffer A
{
    float b;
}

float4 PSMain(PSInput input) : SV_TARGET
{
	return input.color * a +b;
}
```

**Comment by llvm-beanz** [comment]
`cbuffer` objects behave more like C++ namespaces than structures. The code above doesn't re-define `cbuffer A` it extends it by adding an additional member.

The one complication is that `cbuffer` member declarations are added to the global scope, so the names of `cbuffer` members can't conflict with each other or declarations in the global scope (so you can't add variables named `a` to multiple `cbuffer` declarations).

Since this is the correct behavior I'm going to close this issue.
