### ISSUE TITLE
[SPIR-V]SampleLevel with offset in a loop

### ISSUE THREAD

**Issue by mayhcat** [microsoft/DirectXShaderCompiler#6116]
if you define const array and use it in a loop, SampleLevel with this array element will compile failed, because this array element can not be a const variable. the result info: Image Operand Offset can only be used with OpImage*Gather operations
  %85 = OpImageSampleExplicitLod %v4float %84 %75 Lod|Offset %float_0 %83

this bug is occured with option DXC_ARG_SKIP_OPTIMIZATIONS, if not with option this flag will not occur.

code:
--------------------------------------------------------------
struct PARAMS_IN
{
    float4 wPos : SV_Position;
    [[vk::location(0)]] float2 vTex : MY_TEX;
};

struct PARAMS_OUT
{
    float4 k_color : SV_Target;
};

cbuffer BackInfo : register(b0, space0)
{
    float4 g_param0 : packoffset(c0);
    float4 g_param1 : packoffset(c1);
}

#define tex2DLevelOffset(s, t, l, f)        s.SampleLevel(s##Sampler, t, l, f)

SamplerState g_samBack : register(s0, space1);
Texture2D g_texBack : register(t0, space2);
Texture3D g_tex3d : register(t1, space2);

void main( PARAMS_IN pIn, out PARAMS_OUT pOut )
{
    uint2 colrow = uint2(pIn.wPos.xy);

    // 2d texture background
    float4 clr = g_texBack.SampleLevel(g_samBack, pIn.vTex, 0.0, int2(-7, 0));

#if 1 // bug here...
    clr = 0;

    const int2 Offsets[9] =
	{
		int2(-1, -1),
		int2( 0, -1),
		int2( 1, -1),
		int2(-1,  0),
		int2( 0,  0),
		int2( 1,  0),
		int2(-1,  1),
		int2( 0,  1),
		int2( 1,  1),
	};

    [unroll] for( uint i = 0; i < 9; i++ )
    {
        clr += g_texBack.SampleLevel(g_samBack, pIn.vTex, 0.0, Offsets[i]);
    }

    clr /= 9;
#endif

    clr *= g_param0;

    // 3d texture test
    float3 tuv;
    tuv.xy = pIn.vTex * 20;
    tuv.z = g_param1.x;

    colrow /= 4;
    float4 clr2 = g_tex3d.Load( uint4(colrow % uint2(32,32), uint(g_param1.x * 31), 0) );
                 //g_tex3d.SampleLevel(g_samBack, tuv, 0);
    clr = lerp(clr, clr2, 0.3);

    // out
    pOut.k_color = clr;
}

**Comment by s-perron** [comment]
To generate legal spir-v, this example requires:

1. Unrolling to unroll the loop,
2. Local access change convert to modify the accesses to `Offsets`,
3. Scalar replacement to replace the use of `Offset` by individual variables,
4. SSA elimination to removes the loads and stores to the scalar variable of `Offset`.

This is my guess at the order that would be a needed. Step 2-4 are not done in the legalization passes after unrolling, which is why this fails when optimization is disabled. They are performed as part of the optimization, when it is enabled, which is why it passes in that case.

The solution would be to add more passes to the legalization passes, but the extra compile time for everyone may not be worth it.

@mayhcat, Is it possible for you to selectively enable optimizations? Our "legalization" is on a best effort basis, and I would need a good reason to add more passes for everyone.

You can see the list of pass that are run [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/7d2429594d84f09d0aef2c0a36d1a7234941a040/source/opt/optimizer.cpp#L113)

**Comment by mayhcat** [comment]
> To generate legal spir-v, this example requires:
> 
> 1. Unrolling to unroll the loop,
> 2. Local access change convert to modify the accesses to `Offsets`,
> 3. Scalar replacement to replace the use of `Offset` by individual variables,
> 4. SSA elimination to removes the loads and stores to the scalar variable of `Offset`.
> 
> This is my guess at the order that would be a needed. Step 2-4 are not done in the legalization passes after unrolling, which is why this fails when optimization is disabled. They are performed as part of the optimization, when it is enabled, which is why it passes in that case.
> 
> The solution would be to add more passes to the legalization passes, but the extra compile time for everyone may not be worth it.
> 
> @mayhcat, Is it possible for you to selectively enable optimizations? Our "legalization" is on a best effort basis, and I would need a good reason to add more passes for everyone.
> 
> You can see the list of pass that are run [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/7d2429594d84f09d0aef2c0a36d1a7234941a040/source/opt/optimizer.cpp#L113)

Thank you for your answer. Actually, this problem only occurs in my debug mode, so I modified my code, and if it fails, it will automatically try to remove the skip optimization option.
