### ISSUE TITLE
asfloat16 is incorrectly applied

### ISSUE THREAD

**Issue by AdamJMiles** [microsoft/DirectXShaderCompiler#6315]
float main() : SV_TARGET
{
	return asfloat16(0x7c00);   // 0x7c00 = Infinity in float16.
}

This shader returns 31744.0f rather than FP32 Infinity (0x7f800000).

Instead of doing a reinterpret_cast -style cast like asfloat16 should, it's doing a C-style cast from uint16_t (0x7c00) to float16_t (31744.0f).

Thanks,

Adam

**Comment by llvm-beanz** [comment]
This is behaving as expected for HLSL based on the current state of the language.

Basically `0x7c00` is a signed 32-bit integer. The standard conversion sequence prefers converting a signed 32-bit integer to `half` which can represent the full range of a signed 32-bit integer, rather than to `uint16_t` which cannot.

You can get your expected results by explicitly casting to a `uint16_t`:

```hlsl
float main() : SV_TARGET
{
  return asfloat16((uint16_t)0x7c00); // 0x7c00 = Infinity in float16.
}
```
[godbolt link](https://godbolt.org/z/7KfWcs7bd)

Without changing the language in some way there's nothing we can really do to change this.
