### ISSUE TITLE
[SPIR-V] Verify behavior of `HitAttributeNV` vars

### ISSUE THREAD

**Issue by sudonatalie** [microsoft/DirectXShaderCompiler#6364]
In fixing #5709 I noticed that hit attributes are reused as long as they have the same type, even if they have different values:

https://github.com/microsoft/DirectXShaderCompiler/blob/5a3178590581b4a7deea17dd45b6c4f1b51edb53/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L11772-L11778

This may be correct since it was clearly implemented intentionally, but I'd like to double check this and verify the behavior. 

It seems odd for both attributes in this shader to be `OpStore`d to `%myHitAttribute`: 

`dxc -T lib_6_3 -fspv-extension=SPV_NV_ray_tracing -spirv`

```
struct Attribute
{
  float2 bary;
};

[shader("intersection")]
void main() {
  Attribute myHitAttribute = Attribute(float2(0.0f,0.0f));
  ReportHit(0.0f, 0U, myHitAttribute);
  Attribute myHitAttribute2 = Attribute(float2(1.0f,1.0f));
  ReportHit(0.0f, 0U, myHitAttribute2);
}
```

https://godbolt.org/z/rfsrjxKvG

**Comment by s-perron** [comment]
From https://learn.microsoft.com/en-us/windows/win32/direct3d12/intersection-attributes, it seems like it is the structure itself, and not the instance of the structure that defines the hit attribute. It makes sense that both calls to HitAttribute will write to the same attribute since myHitAttribute and myHitAttribute2 are the same type.

> A structure declared in HLSL to represent hit attributes for fixed-function triangle intersection or axis-aligned bounding box for procedural primitive intersection.
