### ISSUE TITLE
[Feature Request] Add clarifying comment to ternary assignment to undefVertexIdx in mesh shader preview

### ISSUE THREAD

**Issue by bob80905** [microsoft/DirectXShaderCompiler#6486]
**Is your feature request related to a problem? Please describe.**
There is an odd ternary statement in HLSignatureLower.cpp, and the reasoning behind the condition that is written is unclear.

**Describe the solution you'd like**
This issue can be considered resolved when a comment is added to HLSignatureLower.cpp:GenerateDxilInputsOutputs, where undefVertexIdx is defined to be 
```
props.IsMS() || props.IsMeshNode() || !bInput
                              ? nullptr
                              : UndefValue::get(Type::getInt32Ty(HLM.GetCtx())); 
```
explaining the purpose of the assignment.

**Describe alternatives you've considered**

**Additional context**

**Comment by damyanp** [comment]
@pow2clk - can you have a look at this please? Maybe consider adding a comment, but it's possible that we'll have shipped by the time you get to it in which case it may be moot.

**Comment by pow2clk** [comment]
The upshot is that this value is potentially used as the default value for four different intrinsics, `LoadInput`, `StoreOutput`, `StoreVertexOutput`, or `StorePrimitiveOutput`. Of these, `StoreOutput` doesn't take an index and the others do.  Of interest to mesh shaders and mesh nodes are `StoreVertexOutput` and `StorePrimitiveOutput` which take indices. Unlike `LoadInput`, these indices shouldn't default to undefined, since they are required to have a valid value, which should be assigned later in the process.

If I'd written the code, I'd have communicated this differently, but as it stands, this is what the code expects to correctly generate the calls to the `Store*Output` calls needed for mesh shaders and mesh nodes. It is correct. I can easily add a comment in the release code, though it's no clearer in main.

**Comment by pow2clk** [comment]
Fixed by https://github.com/microsoft/DirectXShaderCompiler/pull/6539
