### ISSUE TITLE
Library compilation to support library reflection

### ISSUE THREAD

**Issue by mrvux** [microsoft/DirectXShaderCompiler#657]
Since compiled shaders already support reflection (using ID3D11LibraryReflection/ID3D12ShaderReflection)

Bytecode compiled with lib_6_1 could definitely also provide [ID3D11LibraryReflection](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280554(v=vs.85).aspx) support. 

Reflection data should match what's already in the D3D11 counterpart (eg: function name / parameters), since it's already quite exhaustive (and ideally use the same interface).

This is really useful in order to scan library for existing functions (when building authoring tools).

**Comment by pow2clk** [comment]
Supported!

**Comment by mrvux** [comment]
Thanks, I finally had time to try it, seems there is some partial support, also I could see a few issues 

Taking this extremely simple code : 
    
    float3 Apply(float3 input)
    {
	    return input * 2.0f;
    }

accessing reflection gives a mangled name in function desc : 

     D3D12_FUNCTION_DESC func_desc;
     auto fr = lib_ref->GetFunctionByIndex(0);
     fr->GetDesc(&func_desc);

func_desc.Name gives me : 

?Apply@@YA?AV?$vector@M$02@@V1@@Z

Also seems parameter reflection is not working versus d3d12 counterpart : 

D3D12_PARAMETER_DESC pdesc;
auto p = fr->GetFunctionParameter(0);
HRESULT hr = p->GetDesc(&pdesc);

hr returns an E_FAIL here

Should I actually post those as separate issues?

Thanks

**Comment by pow2clk** [comment]
Hi @mrvux! 

The name mangling is intentional I'm afraid. See this line where the mangled name return is tested: https://github.com/microsoft/DirectXShaderCompiler/blob/075d3ce9ef70820efea79d3c256183e19d36bb14/tools/clang/unittests/HLSL/DxilContainerTest.cpp#L1280

To demangle it, you might consider the fairly simple approach taken by the internal code: https://github.com/microsoft/DirectXShaderCompiler/blob/075d3ce9ef70820efea79d3c256183e19d36bb14/lib/DXIL/DxilUtil.cpp#L139
unfortunately, this function isn't directly available outside the codebase

The `GetFunctionParameter` issue looks unexpected. I notice we have no testing for it. :disappointed:  Maybe @tex3d has some insight, but I think it's worth creating a new issue regardless.

**Comment by tex3d** [comment]
While we implemented some library reflection through the `ID3D11LibraryReflection` interface, there are fundamental differences between what a library is and what it's used for in D3D11 with FXC and DXBC vs. D3D12 with DXC and DXIL.  One (DXBC) consists of shader snippets used exclusively for constructing function linking graphs at runtime in D3D11, and the other (DXIL) is more similar to a C++ library for use in offline linking of modules, as well as for DXR shaders and functions linked by drivers.  As you point out, one difference is that DXIL libraries mangle functions in order to support function overloading.

It may not be worth it to attempt to make reflection match in more than some useful subset of ways.  The implementation of DXIL library reflection in this interface was limited to known use cases that were needed for developers using them at the time (for DXR).

I agree we should create a new issue for `GetFunctionParameter`.  Then we would like to know how high a priority this is for developers who would like to use it.
