### ISSUE TITLE
[SPIR-V][Feature Request][SM6.5] Add support for FeedbackTexture2D

### ISSUE THREAD

**Issue by Keenuts** [microsoft/DirectXShaderCompiler#6614]
The SPIR-V backend currently doesn't support [FeedbackTextures](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_ShaderModel6_5.html#sampler-feedback).

Not sure if that's high priority as this support seems optional even on the DirectX side, but creating an issue to track this, and define its priotity.

```hlsl
Texture2D<uint> tex;
SamplerState samplerState;
FeedbackTexture2D<SAMPLER_FEEDBACK_MIP_REGION_USED> feedback;

float4 main() : SV_Target {
  feedback.WriteSamplerFeedback(tex, samplerState, uint2(0, 0));
  uint tmp = tex.Sample(samplerState, uint2(0, 0));
  return float(tmp).xxxx;
}
```

```
$ dxc -T ps_6_7 shader.hlsl -spirv
shader.hlsl:6:12: error: intrinsic 'WriteSamplerFeedback' method unimplemented
  feedback.WriteSamplerFeedback(tex, samplerState, uint2(0, 0));
```

**Comment by devshgraphicsprogramming** [comment]
Vulkan & SPIR-V is a bit less managed than DX12 & HLSL, I'm not sure same functionality exists in Vulkan

For sample we have no Append/Consume etc.

there's VK_NV_shader_image_footprint but that doesn't give you a thing to write the feedback to, only query the region accessed

emulating this DX12 feature in SPIR-V would require cooperation from the application to supply a BDA ponter, SSBO or Storage Image to use as the `feedback` and a contract on how to interpret this data

**Comment by sudonatalie** [comment]
After further investigation, we've decided not to implement this feature in the SPIR-V backend at this time because there is not a solid mapping from DX to Vulkan that would support the full feature's requirements, or most Vulkan end users.

We are open to feedback so additional comments/issues are welcome if this is a high-priority feature for your use case.

Improving the error messaging with #6640
