### ISSUE TITLE
integral_constant is exposed to the global namespace in DXC (trunk)

### ISSUE THREAD

**Issue by KStocky** [microsoft/DirectXShaderCompiler#6646]
**Description**
`integral_constant` is defined in the global namespace in DXC(1.8.2405.17). The primary template appears to be declared as follows:

```c++
template<typename T>
struct integral_constant;
```
I don't think this type should be defined in the global namespace.

**Steps to Reproduce**

This should not compile: https://godbolt.org/z/hKxdKhW7e.
DXC 1.8.2403 does not compile this code: https://godbolt.org/z/vha9GennT

**Environment**
- DXC version: 1.8.2405.17
- Host Operating System N/A

**Comment by damyanp** [comment]
@cassiebeckley - we think that this is the result of something you added recently that should be in the `vk` namespace.

**Comment by KStocky** [comment]
Just updating this to say that this bug is now in 1.8.2405.17. It is no longer just an issue with DXC trunk on godbolt

**Comment by s-perron** [comment]
In the code that adds the builtin types, the pattern used for adding types in the vk namespace is 

https://github.com/microsoft/DirectXShaderCompiler/blob/8c3f40c0ae12cbc128832ff546eccc62c9945418/tools/clang/lib/Sema/SemaHLSL.cpp#L3828

Note that the second condition is to check if the vk namespace has been defined. If not, it continues to the next condition, and eventually falls into the default case, which add the function in the default namespace:

https://github.com/microsoft/DirectXShaderCompiler/blob/8c3f40c0ae12cbc128832ff546eccc62c9945418/tools/clang/lib/Sema/SemaHLSL.cpp#L3851-L3862

We need to change this first condition, so that it continues if the vk namespace is not defined.
