### ISSUE TITLE
[SPIR-V][SM6.6] Payload access qualifiers

### ISSUE THREAD

**Issue by sudonatalie** [microsoft/DirectXShaderCompiler#6647]
> Shader models 6.6 and 6.7 add payload access qualifiers (PAQs) to the ray payload structure. PAQs are annotations which describe the read and write semantics of a payload field, that is, which shader stages read or write a given field. The added semantic information can help implementations reduce register pressure and can avoid spilling of payload state to memory. This incentivizes the use of the narrowest-possible qualifiers for each payload field.

https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#payload-access-qualifiers

The SPIR-V backend currently ignores the `[raypayload]` annotation and may work for some cases, but it should have the same behavior and validation as the DXIL backend for the annotation and detailed read/write qualifiers and semantics. There are also currently no tests for these annotations in the SPIR-V backend.

**Comment by s-perron** [comment]
Unfortunately, we are unable to provide the types of warnings that the DXIL back end offers. If you look at the type of warnings generated in [access.hlsl](https://github.com/microsoft/DirectXShaderCompiler/blob/978d36221daecfb745fde05a78bd134a389cb934/tools/clang/test/HLSLFileCheck/hlsl/payload_qualifier/access.hlsl), there is an expectation that an interprocedural data flow analysis is done to determine if the code contradicts the qualifiers. That cannot be done in the spir-v backend because our data-flow analysis is done on the spir-v, and we do not have a way to annotate the SPIR-V with this information.

Moreover, since there is no way to annotate the SPIR-V so that Vulkan drivers are able to take advantage of the qualifiers, we should simply add a single warning that the raypayload annotation is ignored. That is what will actually happen.

**Comment by s-perron** [comment]
I decided not to add a warning for this feature. This is simply a missed opportunity for optimization, and will not effect correctness. We are following the spec, in that we are doing what we can.
