### ISSUE TITLE
[Feature Request] Transplant XIC (Xbox Iterative Compiler) to General DXC

### ISSUE THREAD

**Issue by FlyAndNotDown** [microsoft/DirectXShaderCompiler#6656]
As I known, there is a utility on xbox can help game optimize register usage named XIC (Xbox Iterative Compiler). As mentioned in xbox document it just perform shader compile multi times with different compile options. I'm curious about is it possible be transplanted to general DXC as a compile option ?

**Comment by llvm-beanz** [comment]
We discussed this in our triage meeting. The problem really is that XIC's heuristics for determining "better" or "worse" are extremely reliant on generating final Xbox ISA so they don't work on DXIL. While we could implement such a thing for DXIL the heuristics would be quite challenging and it would more or less require us completely re-designing XIC.

Due to complexity we're not going to pursue this, so I'm going to close this issue rather than letting it languish.
