### ISSUE TITLE
[SPIR-V] Texture2D used with sampleCmp not tagged as depth texture

### ISSUE THREAD

**Issue by webez** [microsoft/DirectXShaderCompiler#6658]
**Description**
Hi, I know this has previously being discussed but I wanted to share again the current problem and how slang deals with it. Dxc right now does not mark in any way Textures as depth textures which makes the work of spirv-cross much harder later. I have tried using slang and it sets the depth of the OpTypedImage used by samplecmp to 1. Could something like this be done in Dxc?

**Steps to Reproduce**
Shader playground of Dxc behavior (Dxc -fcgl->spirv-cross->MSL)
https://shader-playground.timjones.io/8540896d1a665612f1beaaae3c6e0f75

Shader playground of Slang behavior (Slang->spirv-cross->MSL)
https://shader-playground.timjones.io/f6fbb80daa2fb07ae38beff70124e3ee

**Actual Behavior**
The spirv generated by Dxc can´t be converted by spirv-cross

**Environment**
Trunk version

**Comment by s-perron** [comment]
I don't think we will be able to match the code generated by slang. Our primary concern is to generate SPIR-V for Vulkan, and supporting other APIs through spirv-cross or other tools is a secondary. In this case, slang generates invalid spir-v.

```
%13 = OpTypeImage %float 2D 0 0 0 1 Unknown  ; Not a depth image
%19 = OpTypeImage %float 2D 1 0 0 1 Unknown ;  a depth image
%20 = OpTypeSampledImage %19

%29 = OpLoad %13 %tex_0 ; tex_0 is not a depth image.
%31 = OpSampledImage %20 %29 %30  ; The type of %29 implicitly changes to a depth image. The type of %29 is %13, but the image type in %20 is %19.
```

The [spir-v spec for OpSampledImage](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSampledImage) says:

> Result Type must be the OpTypeSampledImage type whose Image Type operand is the type of Image.

I'm double checking with people who know the Vulkan spec better than I do that this is not overridden by the Vulkan specification.

In general, DXC cannot tell if an image is a depth image or not, so it is best to use `2` for the depth in the type. If we started changing the type based on how the variable is used, we could easily run into problem keeping track of the type. For example, Slang is generating what I believe to be invalid code because of this problem.

I view this more as a spirv-cross problem. They are the ones that have to worry about metal, and doing the correct analysis to get the right types for metal. That is not DXC's job.

**Comment by dneto0** [comment]
Tint has a SPIR-V to WGSL conversion path, and faces similar translation challenges as spirv-cross.
Tint tracks usages by operations rather than types, to  infer the resulting type for the target language (WGSL).
