### ISSUE TITLE
What happened to -fvk-disable-depth-hint ?

### ISSUE THREAD

**Issue by maj-tom** [microsoft/DirectXShaderCompiler#6733]
Trying to use newer DXC release with O3DE which passes this parameter when building shaders for Android. But now I get the error that this is an unknown argument. I can build after I remove the option, but not clear on the significance of it

**Comment by damyanp** [comment]
@s-perron - this flag doesn't seem to have ever been supported in DXC.  Maybe this was in some other fork that was distributed to users?

**Comment by s-perron** [comment]
I am unfamiliar with that option. I've looked for it in our internal documentation, and could not find any reference to it. 

The only feature I believe I could map it to is the depth operand in `OpTypeImage`. If the value of that operand is 0 or 1, then it given an indication of whether or not that operand is used a a depth image; however that seem to be just be a hint because it is ignored in Vulkan. If a value of `2` is used, then there is no indication.

The DXC compiler always generates 2 anyway. I don't know if that was always the case. It is possible that this flag was added to "disable" the hint and cause the compiler to always output 2. That is the only behaviour now.

I would recomment removing the option from your build scripts, and look into any problem that may come up. If you find a problem with the compiler please report a new issue.

**Comment by maj-tom** [comment]
Apologies, looks like O3DE uses a fork of DXC where they added that option to work around a mobile driver bug, instead of pushing it upstream...
