### ISSUE TITLE
missing scenario with *it is of type FunctionDecl

### ISSUE THREAD

**Issue by galop1n** [Microsoft/DirectXShaderCompiler#679]
I have a shader with dxc crashing here because it cast the iterator to an improper HLSLBufferDecl type while the iterator contains a FunctionDecl, adding an additional if to skip the element solve the crash for me, but i don't know if it is a proper solution. This is also only the first step, i get other crashes further away.

https://github.com/Microsoft/DirectXShaderCompiler/blob/cd5299e9464fcde9018771eb0afae70c4cbdd260/tools/clang/lib/CodeGen/CGHLSLMS.cpp#L2568

**Comment by python3kgae** [comment]
Sorry for later reply.
Could you send a shader so we can debug?
In theory, a FunctionDecl should not happen inside a cbuffer, so we didn't check it there.

**Comment by galop1n** [comment]
I can't upload this shader on GitHub, do you have a microsoft email ?

**Comment by marcelolr** [comment]
@galop1n I'm starting a pull request to fix an issue with functions within cbuffers (that was likely the second crashing issue you saw). Couldn't repro the first issue though, although there have been a number of fixes in the iterator since. If you still see a problem with the fix, please file a new issue and if you can't upload a file, you can reach me at mruiz at microsoft dot com. Thanks!
