### ISSUE TITLE
[SPIR-V] DXC crash with buffer assignment + template function

### ISSUE THREAD

**Issue by jukim-nv** [microsoft/DirectXShaderCompiler#6877]
**Description**
We are seeing a crash in our shader debug code which uses template functions to output strings to a `RWByteAddressBuffer`.

Only SPIR-V compilation crashes.  DXIL compilation works fine.

**Steps to Reproduce**
This is the most minimal shader that I have found to reproduce the problem:
```
RWByteAddressBuffer u_OutputBuffer : register(u0);

template<typename T, uint N> uint StrLen(T str[N])
{
    // Includes the null terminator
    return N;
}

[numthreads(1, 1, 1)]
void main()
{
    // commenting out either of these lines makes compilation succeed
    // calling StrLen() on a non-string array instead also appears to compile successfully
    const uint unusedStrLen = StrLen("test_string");
    RWByteAddressBuffer unusedBuffer = u_OutputBuffer;
}
```
DXC command line used to reproduce:
```
dxc.exe repro.hlsl -T cs_6_5 -E main -spirv
```

**Actual Behavior**
Compilation crashes with error
```
Internal compiler error: access violation. Attempted to read from address 0x0000000000000000
```

**Environment**
- Reproduced with DXC July 2024 release `dxcompiler.dll: 1.8 - 1.8.2407.7 (416fab6b5); dxil.dll: 1.8(101.8.2407.12)`
- Reproduced with DXC from Vulkan SDK 1.3.290.0 `dxcompiler.dll: 1.8 - 1.8.0.4650 (49d1ae9a0); dxil.dll: 1.5(10.0.19041.1001)`
- Host Operating System: Windows 10 19045.4046

**Comment by damyanp** [comment]
https://godbolt.org/z/oPzofvvqj

**Comment by s-perron** [comment]
The generated code is invalid. See https://godbolt.org/z/nYP4xGrj7. If you add `-Vd` you can see the spir-v that is generated.

The problem is that DXC is using the debug instruction as if it was a real value:

```
%3 = OpString "test_string"
...
     OpStore %param_var_str %3
```

We need to encode the string constant as an array of char, and then use that.

**Comment by s-perron** [comment]
I looked up [strings in the HLSL docs](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-scalar#string-type). This should not be allowed. If you try to pass a string directly to a function you get an error say you cannot do that. See https://godbolt.org/z/oqjr1x8eb.

Using templates is a loop hole to get around the language restriction. 

Also, if we try to represent string literals as arrays of chars, then we will break printf, which [expects an OpString for the format](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.DebugPrintf.html).

This will not be fixed. I'm not sure how hard it would be to give a better error message. I realize this works for DXIL, but that is unspecified behaviour.

**Comment by s-perron** [comment]
I'm leaving this open to see if we can generate a better error message.

**Comment by Keenuts** [comment]
Additional note: there is a spec request to support string litterals (https://github.com/microsoft/hlsl-specs/issues/279).
But yes, for now, we should print an error.

**Comment by TheRealMJP** [comment]
Hey so I know this issue is already closed, but I wanted to comment and point out that the fix for this really just renders the given code unusable for both DXIL and SPIR-V. I totally agree that HLSL has not actually provided actual support for strings yet and there are proposals for adding it, but until the distant future where string literals are a thing (it's already been two years since the proposal with no movement) the provided code was really the only way to deal with string literals at all for utilities like shader printf. While it may have been a backdoor through the template system, it did work well enough for dev-only tooling and generated the appropriate DXIL bytecode for looping over the literal and processing one char at a time.

After this change there's really only two options for rolling your own printf in HLSL, which I had pointed out already in that proposal:
* use arrays of chars, which are clunky and awkward
* write some sort of manual preprocessing step that detects string literals in the HLSL code and replaces it with something else
