### ISSUE TITLE
[SPIR-V] Generates OpCapability RayQueryKHR when an RTAS is visible (and unused) in miss shaders

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#6917]
**Description**
Certain shaders such as miss shaders don't allow further recursion when tracing rays.
A problem happens when miss and other type of shaders are mixed. A closesthit shader might access the resource, but miss shader doesn't. 
In that case, emitting OpCapability RayQueryKHR is problematic and excludes the pascal generation since they don't have this capability.

**Steps to Reproduce**

```hlsl
struct ColorPayload { float a;   };
RaytracingAccelerationStructure test;
[shader("miss")]
void mainMiss(inout ColorPayload payload) { }
```

**Actual Behavior**
Only when the miss stage (or callable if shooting rays there isn't allowed?) accesses the RTAS it should turn on this capability.

**Environment**
- DXC version: Latest from GH
- Host Operating System: N/A.

**Comment by s-perron** [comment]
I can reproduce the issue if optimizations are turned of (-O0). This is because we see the `OpTypeAccelerationStructureKHR` is still in the spir-v, and we opt to use it the RayQuery capability to enable it. This is a difficultly in DXC. When a feature can be enabled by multiple capabilities, we cannot know which one to use.

This can be worked around by specifically adding the allowed extensions on the command line: https://godbolt.org/z/nccj7fWGP.
