### ISSUE TITLE
HLSL instrinsics are not in the global namespace, and can't be disambiguated using `::`

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#7035]
**Description**

Suppose I make a method (static or not) that is called `dot`, if that calls `dot` within itself is impossible to disambiguate and force the of the global instrinsic function `dot`

**Steps to Reproduce**

```cpp
template<typename T>
struct Functor
{
    static inline float dot(const in T lhs, const in T rhs)
    {
        return ::dot(lhs,rhs);
    }
};

void main()
{
    float32_t3 v = float32_t3(4,5,6);
    vk::RawBufferStore(0xdeadbeefull,Functor<float32_t3>::dot(v,v));
}
```
https://godbolt.org/z/GTjzE511j

**Actual Behavior**

```
<source>:9:16: error: no member named 'dot' in the global namespace; did you mean simply 'dot'?
        return ::dot(lhs,rhs);
               ^~~~~
               dot
<source>:7:25: note: 'dot' declared here
    static inline float dot(const in T lhs, const in T rhs)
                        ^
```

**Environment**
- DXC version : latest trunk
- Host Operating System: Godbolt

**Comment by llvm-beanz** [comment]
HLSL isn't really C++, so this isn't expected to be valid with HLSL 2021 and earlier builtin resolution rules (which are a bit special). We do have this related proposal:

https://github.com/microsoft/hlsl-specs/blob/main/proposals/0001-hlsl-namespace.md

Which would move all the HLSL builtin functions into the `hlsl` namespace in a future language version. We're actually implementing it that way in Clang from the start, so you will have a better experience in Clang, but I don't think this is likely to be fixed in DXC.

**Comment by damyanp** [comment]
No plans to address this in DXC. The plan going forward in clang addresses this.
