### ISSUE TITLE
vcpkg support?

### ISSUE THREAD

**Issue by repi** [microsoft/DirectXShaderCompiler#715]
It would be really nice to have support for DXC in [vcpkg](https://github.com/Microsoft/vcpkg) and simplify deployment and upgrading a lot. Esp. as DXC is a fairly big stack of tech to build.
And as DXC uses CMAKE bringing it into vcpkg is likely not too complicated, and would be something we would use for sure.

Are there any plans or is anyone working on making DXC a vcpkg package?

**Comment by marcelolr** [comment]
I don't know of any work going on to get vcpkg support. What do you have in mind? Just pulling in headers and such from SDK, building parts of the project locally, or something else?

**Comment by gwihlidal** [comment]
Hey Marcelo!

Having a proper port in vcpkg for dxc where it does the usual thing of:

- Pulling in the build tree from this github repro
- Applying any patch files (if applicable, but probably not since this is used on Windows so much out of the box)
- Build debug and release targets (support for both static and dynamic libraries, and also support for both static and dynamic CRT linkage)
- Install built libraries and headers into vcpkg accessible location
- Ability to consume the artifacts from the builds in either msbuild or in cmake (standard vcpkg usage)

Let me know if you have any other questions.

-Graham

**Comment by damyanp** [comment]
vcpkg has a directx-dxc package in it now.
