### ISSUE TITLE
dxc from dxil-1.0 branch has incorrect input register mapping

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#75]
For a pixel shader that reads two texture coordinates:

```c++
void ps_main
(
  noperspective float2 tex0 : TEXCOORD0,
  noperspective float4 tex1 : TEXCOORD1,
  out float4 color : SV_Target
)
{
  color = tex0.xxyy + tex1;
}
```

I am seeing the following input signature in DXIL when using `dxc` from `dxil-1.0`:

```
;
; Input signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 1   xyzw        0     NONE   float       
; TEXCOORD                 0   xy          1     NONE   float       
;
```

Notice how index 1 maps to register 0, and index 0 maps to register 1.

If I compile the same shader using the DXIL 0.7 front-end, I see:

```
;
; Input signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 0   xy          0     NONE   float       
; TEXCOORD                 1   xyzw        1     NONE   float       
;
```

which is what I would expect.

**Comment by jholewinski** [comment]
To elaborate on this a bit, consider the following tweaked example that adds a VS:

```c++
void vs_main
(
  float4 inPos : SV_Position,
  out noperspective float2 tex0 : TEXCOORD0,
  out noperspective float4 tex1 : TEXCOORD1,
  out float4 outPos : SV_Position
)
{
  outPos = inPos;
  tex0 = inPos.xy;
  tex1 = inPos;
}

void ps_main
(
  noperspective float2 tex0 : TEXCOORD0,
  noperspective float4 tex1 : TEXCOORD1,
  out float4 color : SV_Target
)
{
  color = tex0.xxyy + tex1;
}
```

With the DXIL 1.0 compiler, the VS output signature does not match the PS input signature:

VS Output:
```
; Output signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 1   xyzw        0     NONE   float   xyzw
; SV_Position              0   xyzw        1      POS   float   xyzw
; TEXCOORD                 0   xy          2     NONE   float   xy  
```

PS Input:
```
; Input signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 1   xyzw        0     NONE   float       
; TEXCOORD                 0   xy          1     NONE   float   
```

On a side note, is it expected that the signature packing may vary between compiler versions? The real issue here is that the VS and PS do not agree on the packing. The change in packing for the PS inputs from DXIL 0.7 to 1.0 would work if the VS had the same change. But that would break compatibility between different shader stages compiled with different versions of the compiler.

**Comment by tex3d** [comment]
Input register mapping has changed for DXIL.
1. Packing is only guaranteed to be identical if the identical parameters are provided.  It's generally recommended that you use the same structure (or set of parameters) for connecting stages (minus special SGV's that do not participate in the packed signature).
2. If packing differs between connecting stages, it is legal if one is a strict subset of the other, in which case, the driver can use the packing locations of the full signature for the subset signature.
3. Packing is really only a suggestion for the purpose of guaranteeing that the given parameters fit within the specified constraints for the shader model.  Drivers are free to repack as necessary since they have the full PSO.
This allows packing to be more efficient in DXIL than DXBC (and solves some problem corner cases that were never addressed for DXBC).

**Comment by jholewinski** [comment]
So the driver can no longer rely on the row/column values in the signature to be the same across stages?

Can you elaborate on this: `Packing is only guaranteed to be identical if the identical parameters are provided.`? The parameters are identical for the posted HLSL, yet the compiler emits a different signature for the two stages.

**Comment by tex3d** [comment]
There is no SV_Position input to the pixel shader corresponding to the vertex shader output.

**Comment by tex3d** [comment]
>So the driver can no longer rely on the row/column values in the signature to be the same across stages?

Unlike DXBC, in DXIL, the row/column value only affects metadata, not the instructions, until the driver gets its hands on it.  That means it should be very cheap to update packing locations for signature elements if they are inconsistent between stages, as long as this is done before dependencies on these locations get baked into the instructions by the driver compiler.

**Comment by jholewinski** [comment]
So in DXIL land, validation errors like the following would never occur because the runtime does not check the row/col assignments between stages?

```
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Vertex Shader - Pixel Shader linkage error: Signatures between stages are incompatible. Semantic 'TEXCOORD' is defined for mismatched hardware registers between the output stage and input stage. [ STATE_CREATION ERROR #660: CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERINDEX]
```

**Comment by jholewinski** [comment]
And just to be super-pedantic, you're saying the following is allowed in DXIL?

```c++
void vs_main(..., out float4 foo : FOO, out float4 bar : BAR) {}

void ps_main(float4 bar : BAR, float4 foo : FOO, ...) {}
```

In other words, reordering of arguments is allowed and should work as expected instead of the old DXBC behavior of the runtime rejecting the shaders because the hardware register mapping is different?

**Comment by tex3d** [comment]
I have an update to my comments above here.  It turns out that D3D12 promoted the SDKLayers signature check to PSO validation.  This means that input parameters must have matching output parameters at the same locations in order to pass through to the driver.

So the subset language above will not apply (at least not in RS2).  Parameter sets must be identical, or simpler "prefix-stable" packing must be used.  We will modify the compiler to default to prefix-stable packing in order to resolve this issue.  The more optimal packer can still be made available through an option.

We may relax the signature requirements in the runtime in a future release, to enable more flexible signature linking between stages.

**Comment by jholewinski** [comment]
Thanks for the update!

**Comment by tex3d** [comment]
Pull request #90 should fix this.  Let us know if you experience additional problems.
