### ISSUE TITLE
SPIR-V: Vector shuffle after texture indexing in a single expression does not work

### ISSUE THREAD

**Issue by seppala2** [Microsoft/DirectXShaderCompiler#819]
The following example fails into the assert in line 103 in spir-v opt mem_pass.cpp

```
[[vk::binding(0, 0)]]
Texture2D<float4> Texture0;

float4 PS(in float4 pos : SV_Position) : SV_Target0
{
    int2 coord = (int2)pos.xy;
    float3 result = Texture0[coord].xyz;
    return float4(result, 1.0);
}
```

The same thing happens even if the swizzle matches the input and should not affect anything (e.g. `float4 a = Tex[coord].xyzw`).

Doing the swizzle in a separate statement works, and Texture.Load(...) does not seem to have the same issue

It looks like the cause is an additional OpLoad emitted in doHLSLVectorElementExpr before the shuffle. The case where the shuffle completely selects the original vector seems to cause an additional load that is generated elsewhere.

**Comment by antiagainst** [comment]
Thanks a lot for the bug report, @seppala2!

This actually turns out to the symptom of a deep problem: lvalue and rvalue handling. AST is sometimes a little bit "off" so we have quite a few ad-hoc checks in the CodeGen to correct lvalueness. I've done a thorough pass to do it in another way right now in #822. It should be more robust now.
