### ISSUE TITLE
SPIR-V: support SV_InnerCoverage translation to SPIR-V FullyCoveredEXT..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#999]
Hi,
DX12 and DX11.3 support optional conservative rasterization.. there are tiers of support and tier3 adds HLSL builtin SV_InnerCoverage..
now that there is a Vulkan extension (VK_EXT_conservative_rasterization) for that and SPIR-V ext SPV_EXT_fragment_fully_covered that adds equivalent new SPIR-V FullyCoveredEXT built in would be nice to have in support for it..
right now only testable in HW by NV Titan V owners..
similar request to glslang devs:
https://github.com/KhronosGroup/glslang/issues/1220

**Comment by antiagainst** [comment]
We'll need SPIRV-Tools disassembling functionality to test the CodeGen. Currently SPIRV-Tools does not recognize the `FullyCoveredEXT` bultin or the `FragmentFullyCoveredEXT` capability, since they are introduced in the [`unified1`](https://github.com/KhronosGroup/SPIRV-Headers/tree/master/include/spirv/unified1) SPIRV-Headers directory. After SPIRV-Tools migrates to use unified1 headers (https://github.com/KhronosGroup/SPIRV-Tools/issues/1195), we can add support for it.
